// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
//
// --------------------------------------------------------------------------
// $Maintainer: Timo Sachsenberg $
// $Authors: Timo Sachsenberg $
// --------------------------------------------------------------------------

#include <OpenMS/ANALYSIS/ID/BasicProteinInferenceAlgorithm.h>
#include <OpenMS/ANALYSIS/ID/BayesianProteinInferenceAlgorithm.h>
#include <OpenMS/ANALYSIS/ID/FalseDiscoveryRate.h>
#include <OpenMS/ANALYSIS/ID/IDBoostGraph.h>
#include <OpenMS/ANALYSIS/ID/IDConflictResolverAlgorithm.h>
#include <OpenMS/ANALYSIS/ID/IDScoreSwitcherAlgorithm.h>
#include <OpenMS/ANALYSIS/ID/PeptideIndexing.h>
#include <OpenMS/ANALYSIS/MAPMATCHING/ConsensusMapNormalizerAlgorithmMedian.h>
#include <OpenMS/ANALYSIS/ID/ConsensusMapMergerAlgorithm.h>
#include <OpenMS/ANALYSIS/MAPMATCHING/FeatureGroupingAlgorithmQT.h>
#include <OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.h>
#include <OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmTreeGuided.h>
#include <OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentTransformer.h>
#include <OpenMS/ANALYSIS/QUANTITATION/PeptideAndProteinQuant.h>
#include <OpenMS/ANALYSIS/QUANTITATION/DDAWorkflowCommons.h>
#include <OpenMS/APPLICATIONS/MapAlignerBase.h>
#include <OpenMS/APPLICATIONS/TOPPBase.h>
#include <OpenMS/DATASTRUCTURES/CalibrationData.h>
#include <OpenMS/PROCESSING/CALIBRATION/InternalCalibration.h>
#include <OpenMS/PROCESSING/CALIBRATION/MZTrafoModel.h>
#include <OpenMS/PROCESSING/CALIBRATION/PrecursorCorrection.h>
#include <OpenMS/FEATUREFINDER/FeatureFindingMetabo.h>
#include <OpenMS/FEATUREFINDER/MassTraceDetection.h>
#include <OpenMS/PROCESSING/ID/IDFilter.h>
#include <OpenMS/PROCESSING/FILTERING/ThresholdMower.h>
#include <OpenMS/FORMAT/ExperimentalDesignFile.h>
#include <OpenMS/FORMAT/FileHandler.h>
#include <OpenMS/CONCEPT/LogStream.h>
#include <OpenMS/METADATA/PeptideIdentificationList.h>
#include <OpenMS/METADATA/ProteinIdentification.h>
#include <OpenMS/KERNEL/ConsensusMap.h>
#include <OpenMS/FORMAT/MSstatsFile.h>
#include <OpenMS/FORMAT/MzTabFile.h>
#include <OpenMS/FORMAT/PeakTypeEstimator.h>
#include <OpenMS/FORMAT/TriqlerFile.h>
#include <OpenMS/FORMAT/FeatureXMLFile.h>
#include <OpenMS/KERNEL/ConversionHelper.h>
#include <OpenMS/KERNEL/MSExperiment.h>
#include <OpenMS/KERNEL/MassTrace.h>
#include <OpenMS/MATH/StatisticFunctions.h>
#include <OpenMS/METADATA/ExperimentalDesign.h>
#include <OpenMS/METADATA/SpectrumMetaDataLookup.h>
#include <OpenMS/SYSTEM/File.h>
#include <OpenMS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.h>
#include <OpenMS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.h>
#include <OpenMS/PROCESSING/CENTROIDING/PeakPickerHiRes.h>
#include <OpenMS/FEATUREFINDER/Biosaur2Algorithm.h>
#ifdef WITH_OPENTIMS
#include <OpenMS/FORMAT/BrukerTimsFile.h>
#endif
#include <OpenMS/ML/SVM/SimpleSVM.h>

#include <OpenMS/FORMAT/ConsensusMapArrowExport.h>
#include <OpenMS/FORMAT/ProteinGroupArrowExport.h>
#include <OpenMS/FORMAT/QPXFile.h>

using namespace OpenMS;
using namespace std;

//-------------------------------------------------------------
//Doxygen docu
//-------------------------------------------------------------

/**
@page TOPP_ProteomicsLFQ ProteomicsLFQ

ProteomicsLFQ performs label-free quantification of peptides and proteins. @n

Input: @n
  - Spectra in mzML format or Bruker .d directories (TimsTOF PASEF)
  - Identifications in idXML or mzIdentML format with posterior error probabilities
   as score type.
   To generate those we suggest to run:
    1. PeptideIndexer to annotate target and decoy information.
    2. PSMFeatureExtractor to annotate percolator features.
    3. PercolatorAdapter tool (score_type = 'q-value', -post-processing-tdc)
    4. IDFilter (pep:score = 0.01) to filter PSMs at 1% FDR

  - An experimental design file: @n
   (see @ref OpenMS::ExperimentalDesign "ExperimentalDesign" for details) @n
  - A protein database in with appended decoy sequences in FASTA format @n
   (e.g., generated by the OpenMS DecoyDatabase tool) @n

Processing: @n
ProteomicsLFQ has different methods to extract features: ID-based (targeted only), or both ID-based and untargeted.
  1. The first method uses targeted feature dectection using RT and m/z information derived from identification data to extract features.
     Note: only identifications found in a particular MS run are used to extract features in the same run.
     No transfer of IDs (match between runs) is performed.
  2. The second method adds untargeted feature detection to obtain quantities from unidentified features.
     Transfer of Ids (match between runs) is performed by transfering feature identifications to coeluting, unidentified features with similar mass and RT in other runs.

@b FAIMS (Field Asymmetric Ion Mobility Spectrometry): @n
FAIMS data is automatically detected based on compensation voltage (CV) annotations in the mzML file.
The data is split by CV and processed separately for each voltage group during feature detection.
Features representing the same analyte detected at different CV values are merged automatically.
The merged features are then aligned and linked across runs based on RT and m/z.
No special preparation of the input mzML file is required.

@b Bruker .d (TimsTOF PASEF): @n
Bruker .d directories containing DDA-PASEF data are supported directly.
When .d input is detected, the tool automatically:
  - Skips centroiding (PeakPickerHiRes) to preserve per-peak ion mobility data
  - Skips precursor mass correction (not IM-aware)
  - Forces Biosaur2Algorithm for seed generation (FeatureFinderMultiplex does not support IM_PEAK)
  - Estimates chromatographic FWHM from Biosaur2 feature extents
Identification files should be generated with SageAdapter, which annotates
ion mobility values in the idXML output. FeatureFinderIdentificationAlgorithm
uses these IM annotations for targeted 2D chromatogram extraction (m/z + IM windowing).
MS1 frames are IM-centroided during loading using BrukerTimsFile's built-in Sage algorithm,
collapsing ~245k raw peaks/frame into ~10k centroided peaks with summed intensity.
Biosaur2 defaults are tuned for ProteomicsLFQ (mini=500, minlh=3, pasefminlh=2).
On HeLa 50ng 5-min timsTOF gradient: 34k seeds, 80% model fit success, 2,809
peptides quantified (Spearman r=0.62 vs Sage LFQ), 75s runtime, 1.3 GB memory.

Normalization: @n
  - For feature-intensity-based quantification with multiple runs, ProteomicsLFQ automatically applies median normalization
    to the consensus features (using simple median scaling).
  - Normalization is DISABLED when MSstats output (-out_msstats) or Triqler output (-out_triqler) is requested,
    as these tools perform their own normalization.
  - Normalization is also DISABLED for spectral counting quantification.

Output:
  - mzTab file with analysis results
  - MSstats file with analysis results for statistical downstream analysis in MSstats
  - ConsensusXML file for visualization and further processing in OpenMS


Potential scripts to perform the search can be found under src/tests/topp/ProteomicsLFQTestScripts

<B>The command line parameters of this tool are:</B>
@verbinclude TOPP_ProteomicsLFQ.cli
<B>INI file documentation of this tool:</B>
@htmlinclude TOPP_ProteomicsLFQ.html
 **/

// We do not want this class to show up in the docu:
/// @cond TOPPCLASSES

class ProteomicsLFQ :
  public TOPPBase
{
public:
  ProteomicsLFQ() :
    TOPPBase("ProteomicsLFQ", "A standard proteomics LFQ pipeline.")
  {
  }

protected:
  void registerOptionsAndFlags_() override
  {
    registerInputFileList_("in", "<file list>", StringList(), "Input files");
    setValidFormats_("in", ListUtils::create<String>("mzML"
#ifdef WITH_OPENTIMS
      ",d"
#endif
#ifdef WITH_THERMO_RAW
      ",raw"
#endif
    ));
    registerInputFileList_("in_feat", "<files>", StringList(), "Optional input featureXML files containing pre-computed features. Bypasses internal feature finding. Must match the number of '-in' files.", false, false);
    setValidFormats_("in_feat", ListUtils::create<String>("featureXML"));
    registerInputFileList_("ids", "<file list>", StringList(),
      "Identifications filtered at PSM level (e.g., q-value < 0.01)."
      "And annotated with PEP as main score.\n"
      "We suggest using:\n"
      "1. PSMFeatureExtractor to annotate percolator features.\n"
      "2. PercolatorAdapter tool (score_type = 'q-value', -post-processing-tdc)\n"
      "3. IDFilter (pep:score = 0.05)\n"
      "To obtain well calibrated PEPs and an initial reduction of PSMs\n"
      "ID files must be provided in same order as spectra files.");
    setValidFormats_("ids", ListUtils::create<String>("idXML,mzId,idparquet"));

    registerInputFile_("design", "<file>", "", "design file", false);
    setValidFormats_("design", ListUtils::create<String>("tsv"));

    registerInputFile_("fasta", "<file>", "", "fasta file", false);
    setValidFormats_("fasta", ListUtils::create<String>("fasta"));

    registerOutputFile_("out", "<file>", "", "output mzTab file");
    setValidFormats_("out", ListUtils::create<String>("mzTab"));

    registerOutputFile_("out_msstats", "<file>", "", "output MSstats input file", false, false);
    setValidFormats_("out_msstats", ListUtils::create<String>("csv"));

    registerOutputFile_("out_triqler", "<file>", "", "output Triqler input file", false, false);
    setValidFormats_("out_triqler", ListUtils::create<String>("tsv"));

    registerOutputFile_("out_cxml", "<file>", "", "output consensusXML file", false, false);
    setValidFormats_("out_cxml", ListUtils::create<String>("consensusXML"));

    registerOutputDir_("out_qpx", "<directory>", "", "Output directory for QPX Parquet files (quantms.feature.parquet, quantms.psm.parquet, quantms.pg.parquet)", false, false);

    registerDoubleOption_("proteinFDR", "<threshold>", 0.05, "Protein FDR threshold (0.05=5%).", false);
    setMinFloat_("proteinFDR", 0.0);
    setMaxFloat_("proteinFDR", 1.0);

    //TODO test rigorously
    registerStringOption_("picked_proteinFDR", "<choice>", "false", "Use a picked protein FDR?", false);
    setValidStrings_("picked_proteinFDR", {"true","false"});

    registerDoubleOption_("psmFDR", "<threshold>", 1.0, "FDR threshold for sub-protein level (e.g. 0.05=5%). Use -FDR_type to choose the level. Cutoff is applied at the highest level."
                          " If Bayesian inference was chosen, it is equivalent with a peptide FDR", false);
    setMinFloat_("psmFDR", 0.0);
    setMaxFloat_("psmFDR", 1.0);

    registerStringOption_("FDR_type", "<threshold>", "PSM", "Sub-protein FDR level. PSM, PSM+peptide (best PSM q-value).", false);
    setValidStrings_("FDR_type", {"PSM", "PSM+peptide"});

    //TODO expose all parameters of the inference algorithms (e.g. aggregation methods etc.)?
    registerStringOption_("protein_inference", "<option>", "aggregation",
      "Infer proteins:\n"
      "aggregation  = aggregates all peptide scores across a protein (using the best score) \n"
      "bayesian     = computes a posterior probability for every protein based on a Bayesian network.\n"
      "               Note: 'bayesian' only uses and reports the best PSM per peptide.",
      false, true);
    setValidStrings_("protein_inference", ListUtils::create<String>("aggregation,bayesian"));

    registerStringOption_("protein_quantification", "<option>", "unique_peptides",
      "Quantify proteins based on:\n"
      "unique_peptides = use peptides mapping to single proteins or a group of indistinguishable proteins"
      "(according to the set of experimentally identified peptides).\n"
      "strictly_unique_peptides = use peptides mapping to a unique single protein only.\n"
      "shared_peptides = use shared peptides only for its best group (by inference score)", false, true);
    setValidStrings_("protein_quantification", ListUtils::create<String>("unique_peptides,strictly_unique_peptides,shared_peptides"));
    registerStringOption_("quantification_method", "<option>",
      "feature_intensity",
      "feature_intensity: MS1 signal.\n"
      "spectral_counting: PSM counts.", false, false);
    setValidStrings_("quantification_method", ListUtils::create<String>("feature_intensity,spectral_counting"));

    registerStringOption_("targeted_only", "<option>", "false",
      "true: Only ID based quantification.\n"
      "false: include unidentified features so they can be linked to identified ones (=match between runs).", false, false);
    setValidStrings_("targeted_only", ListUtils::create<String>("true,false"));

    registerDoubleOption_("feature_with_id_min_score", "<p-value>", 0.0, "The minimum probability (e.g.: 0.25) an identified (=id targeted) feature must have to be kept for alignment and linking (0=no filter).", false, true);
    setMinFloat_("feature_with_id_min_score", 0.0);
    setMaxFloat_("feature_with_id_min_score", 1.0);

    registerDoubleOption_("feature_without_id_min_score", "<p-value>", 0.0, "The minimum probability (e.g.: 0.75) an unidentified feature must have to be kept for alignment and linking (0=no filter).", false, true);
    setMinFloat_("feature_without_id_min_score", 0.0);
    setMaxFloat_("feature_without_id_min_score", 1.0);

    registerStringOption_("mass_recalibration", "<option>", "false", "Mass recalibration.", false, true);
    setValidStrings_("mass_recalibration", ListUtils::create<String>("true,false"));

    registerStringOption_("alignment_order", "<option>", "star", "If star, aligns all maps to the reference with most IDs. If tree_guided, aligns maps in tree order (most similar pairs first).", false, true);
    setValidStrings_("alignment_order", ListUtils::create<String>("star,tree_guided"));

    registerStringOption_("keep_feature_top_psm_only", "<option>", "true", "If false, also keeps lower ranked PSMs that have the top-scoring"
                                                                     " sequence as a candidate per feature in the same file.", false, true);
    setValidStrings_("keep_feature_top_psm_only", ListUtils::create<String>("true,false"));

    registerTOPPSubsection_("Seeding", "Parameters for seeding of untargeted features");
    registerDoubleOption_("Seeding:intThreshold", "<threshold>", 1e4, "Peak intensity threshold applied in seed detection.", false, true);
    registerStringOption_("Seeding:charge", "<minChg:maxChg>", "2:5", "Charge range considered for untargeted feature seeds.", false, true); //TODO infer from IDs?
    registerDoubleOption_("Seeding:traceRTTolerance", "<tolerance(sec)>", 3.0, "Combines all spectra in the tolerance window to stabilize identification of isotope patterns. Controls sensitivity (low value) vs. specificity (high value) of feature seeds.", false, true); //TODO infer from average MS1 cycle time?
    registerStringOption_("Seeding:algorithm", "<choice>", "multiplex",
      "Algorithm for untargeted seed feature detection.\n"
      "multiplex: FeatureFinderMultiplexAlgorithm (default, current behavior).\n"
      "biosaur2: Biosaur2Algorithm (handles IM_PEAK/PASEF data natively).",
      false, false);
    setValidStrings_("Seeding:algorithm", {"multiplex", "biosaur2"});

    /// TODO: think about export of quality control files (qcML?)

    Param pp_defaults = PeakPickerHiRes().getDefaults();
    for (const auto& s : {"report_FWHM", "report_FWHM_unit", "SignalToNoise:win_len", "SignalToNoise:bin_count", "SignalToNoise:min_required_elements", "SignalToNoise:write_log_messages"} )
    {
      pp_defaults.addTag(s, "advanced");
    }

    Param ffi_defaults = FeatureFinderIdentificationAlgorithm().getDefaults();
    ffi_defaults.setValue("svm:samples", 10000); // restrict number of samples for training
    ffi_defaults.setValue("svm:log2_C", DoubleList({-2.0, 5.0, 15.0}));
    ffi_defaults.setValue("svm:log2_gamma", DoubleList({-3.0, -1.0, 2.0}));
    ffi_defaults.setValue("svm:min_prob", 0.9); // keep only feature candidates with > 0.9 probability of correctness

    // hide entries
    for (const auto& s : {"svm:samples", "svm:log2_C", "svm:log2_gamma", "svm:min_prob", "svm:no_selection", "svm:xval_out", "svm:kernel", "svm:xval", "candidates_out", "extract:n_isotopes", "model:type"} )
    {
      ffi_defaults.addTag(s, "advanced");
    }
    ffi_defaults.remove("detect:peak_width"); // set from data

    Param ma_defaults = MapAlignmentAlgorithmTreeGuided().getDefaults();

    ma_defaults.setValue("align_algorithm:max_rt_shift", 0.1);
    ma_defaults.setValue("align_algorithm:use_unassigned_peptides", "false");
    ma_defaults.setValue("align_algorithm:use_feature_rt", "true");

    // hide entries
    for (const auto& s : {"align_algorithm:use_unassigned_peptides", "align_algorithm:use_feature_rt",
                          "align_algorithm:score_cutoff", "align_algorithm:min_score"} )
    {
      ma_defaults.addTag(s, "advanced");
    }

    //Param fl_defaults = FeatureGroupingAlgorithmKD().getDefaults();
    Param fl_defaults = FeatureGroupingAlgorithmQT().getDefaults();
    fl_defaults.setValue("distance_MZ:max_difference", 10.0);
    fl_defaults.setValue("distance_MZ:unit", "ppm");
    fl_defaults.setValue("distance_MZ:weight", 5.0);
    fl_defaults.setValue("distance_intensity:weight", 0.1);
    fl_defaults.setValue("use_identifications", "true");
    fl_defaults.remove("distance_RT:max_difference"); // estimated from data
    for (const auto& s : {"distance_MZ:weight", "distance_intensity:weight", "use_identifications", "ignore_charge", "ignore_adduct"} )
    {
      fl_defaults.addTag(s, "advanced");
    }

    Param pq_defaults = PeptideAndProteinQuant().getDefaults();
    // overwrite algorithm default, so we export everything (important for copying back MSstats results)
    pq_defaults.setValue("top:include_all", "true");
    pq_defaults.addTag("top:include_all", "advanced");

    Param bio_defaults = Biosaur2Algorithm().getDefaults();
    bio_defaults.setValue("mini", 500.0);   // filter low-intensity noise peaks (default 1.0 too permissive)
    bio_defaults.setValue("minlh", 3);      // require hills spanning >= 3 scans (default 2 keeps transient noise)
    bio_defaults.setValue("pasefminlh", 2); // require >= 2 raw points per PASEF cluster (default 1)
    for (auto it = bio_defaults.begin(); it != bio_defaults.end(); ++it)
    {
      bio_defaults.addTag(it.getName(), "advanced");
    }

    // combine parameters of the individual algorithms
    Param combined;
    combined.insert("Centroiding:", pp_defaults);
    combined.insert("PeptideQuantification:", ffi_defaults);
    combined.insert("Alignment:", ma_defaults);
    combined.insert("Linking:", fl_defaults);
    combined.insert("ProteinQuantification:", pq_defaults);
    combined.insert("Seeding:Biosaur2:", bio_defaults);

    registerFullParam_(combined);
  }

  ExitCodes loadAndPreprocess_(const String& mz_file, MSExperiment& ms_out, bool& is_im_peak_data)
  {
#ifdef WITH_OPENTIMS
    if (FileHandler::getType(mz_file) == FileTypes::BRUKER_TDF)
    {
      // .d path: load with built-in IM centroiding (Sage algorithm, Lazear 2023)
      // This collapses raw IM profiles into single centroided peaks with summed intensity,
      // matching what Sage v0.15 does internally before LFQ feature tracing.
      BrukerTimsFile tdf;
      tdf.setLogType(log_type_);
      BrukerTimsFile::Config config;
      config.ms1_centroid_mz_ppm = 5.0f;  // same as Sage default
      config.ms1_centroid_im_pct = 3.0f;  // same as Sage default
      tdf.load(mz_file, ms_out, config);
      ms_out.updateRanges();

      if (ms_out.empty())
      {
        OPENMS_LOG_WARN << "The given file does not contain any spectra.";
        return INCOMPATIBLE_INPUT_DATA;
      }

      // Remove MS2 spectra entirely and filter MS1 spectra without IM data.
      // MS2 peak data is not needed (IDs come from external search engine).
      // MS1 spectra without IM arrays cause ChromatogramExtractorAlgorithm to throw
      // during IM-windowed extraction.
      auto& spectra = ms_out.getSpectra();
      for (auto& spec : spectra)
      {
        if (!spec.isSorted())
        {
          spec.sortByPosition();
        }
      }
      spectra.erase(
        std::remove_if(spectra.begin(), spectra.end(),
          [](const MSSpectrum& spec)
          {
            return spec.getMSLevel() != 1 || !spec.containsIMData();
          }),
        spectra.end());

      // No PeakPickerHiRes — Bruker TOF data is centroid-like; IM arrays must be preserved
      // No PrecursorCorrection — findHighestInWindow() is IM-unaware
      // No clearMetaDataArrays — IM per-peak float arrays must survive
      is_im_peak_data = true;
      OPENMS_LOG_INFO << "Loaded Bruker .d file with IM_PEAK data. Skipping centroiding and precursor correction.\n";
      return EXECUTION_OK;
    }
    else
#endif
    {
      // mzML path: existing centroid + precursor correction
      is_im_peak_data = false;
      return centroidAndCorrectPrecursors_(mz_file, ms_out);
    }
  }

  ExitCodes centroidAndCorrectPrecursors_(const String & mz_file, MSExperiment & ms_centroided)
  {
    Param pp_param = getParam_().copy("Centroiding:", true);
    writeDebug_("Parameters passed to PeakPickerHiRes algorithm", pp_param, 3);

    // create scope for raw data, so it is properly freed (Note: clear() is not sufficient)
    // load raw file

    PeakMap ms_raw;
    FileHandler().loadExperiment(mz_file, ms_raw, {FileTypes::MZML, FileTypes::RAW}, log_type_);
    ms_raw.clearMetaDataArrays();
    ms_raw.updateRanges();

    if (ms_raw.empty())
    {
      OPENMS_LOG_WARN << "The given file does not contain any spectra.";
      return INCOMPATIBLE_INPUT_DATA;
    }

    // remove MS2 peak data and check if spectra are sorted
    //TODO can we load just MS1 or do we need precursor information?
    for (auto & spec : ms_raw)
    {
      if (spec.getMSLevel() == 2)
      {
        spec.clear(false);  // delete MS2 peaks
      }
      if (!spec.isSorted())
      {
        spec.sortByPosition();
        writeLogInfo_("Info: Sorted peaks by m/z.");
      }
    }

    //-------------------------------------------------------------
    // Centroiding of MS1
    //-------------------------------------------------------------
    PeakPickerHiRes pp;
    pp.setLogType(log_type_);
    pp.setParameters(pp_param);
    pp.pickExperiment(ms_raw, ms_centroided, true);

    //-------------------------------------------------------------
    // HighRes Precursor Mass Correction
    //-------------------------------------------------------------
    std::vector<double> deltaMZs, mzs, rts;
    std::set<Size> corrected_to_highest_intensity_peak = PrecursorCorrection::correctToHighestIntensityMS1Peak(
      ms_centroided,
      0.01, // check if we can estimate this from data (here it is given in m/z not ppm)
      false, // is ppm = false
      deltaMZs,
      mzs,
      rts
      );
    writeLogInfo_("Info: Corrected " + String(corrected_to_highest_intensity_peak.size()) + " precursors.");
    if (!deltaMZs.empty())
    {
      vector<double> deltaMZs_ppm, deltaMZs_ppmabs;
      for (Size i = 0; i != deltaMZs.size(); ++i)
      {
        deltaMZs_ppm.push_back(Math::getPPM(mzs[i], mzs[i] + deltaMZs[i]));
        deltaMZs_ppmabs.push_back(Math::getPPMAbs(mzs[i], mzs[i] + deltaMZs[i]));
      }

      double median = Math::median(deltaMZs_ppm.begin(), deltaMZs_ppm.end());
      double MAD =  Math::MAD(deltaMZs_ppm.begin(), deltaMZs_ppm.end(), median);
      double median_abs = Math::median(deltaMZs_ppmabs.begin(), deltaMZs_ppmabs.end());
      double MAD_abs = Math::MAD(deltaMZs_ppmabs.begin(), deltaMZs_ppmabs.end(), median_abs);
      writeLogInfo_("Precursor correction:\n  median        = "
        + String(median) + " ppm  MAD = " + String(MAD)
        + "\n  median (abs.) = " + String(median_abs)
        + " ppm  MAD = " + String(MAD_abs));
    }
    return EXECUTION_OK;
  }

  // aligns the feature maps
  double align_(
    vector<FeatureMap> & feature_maps,
    vector<TransformationDescription>& transformations
  )
  {
    if (feature_maps.size() > 1) // do we have several maps to align / link?
    {
      Param mat_param = getParam_().copy("Alignment:", true);
      writeDebug_("Parameters passed to MapAlignmentAlgorithms", mat_param, 3);

      Param model_params = MapAlignerBase::getModelDefaults("b_spline");
      String model_type = model_params.getValue("type").toString();
      model_params = model_params.copy(model_type + ":", true);

      try
      {
        if (getStringOption_("alignment_order") == "star")
        {
          // Determine reference from data, otherwise a change in order of input files
          // leads to slightly different results
          const int reference_index(-1); // set no reference (determine from data)
          Param ma_param = mat_param.copy("align_algorithm:", true);
          writeDebug_("Parameters passed to MapAlignerIdentification", ma_param, 3);
          MapAlignmentAlgorithmIdentification aligner;
          aligner.setLogType(log_type_);
          aligner.setParameters(ma_param);
          aligner.align(feature_maps, transformations, reference_index);
        }
        else //tree-guided
        {
          MapAlignmentAlgorithmTreeGuided aligner;
          aligner.setLogType(log_type_);
          aligner.setParameters(mat_param);
          aligner.align(feature_maps, transformations);
        }
      }
      catch (Exception::MissingInformation& err)
      {
        if (getFlag_("force"))
        {
          OPENMS_LOG_ERROR
            << "Error: alignment failed. Details:\n" << err.what()
            << "\nProcessing will continue using 'identity' transformations."
            << endl;
          model_type = "identity";
          transformations.resize(feature_maps.size());
        }
        else throw;
      }

      // find model parameters (if model_type == "identity" the fit is a NOP):
      vector<TransformationDescription::TransformationStatistics> alignment_stats;
      for (TransformationDescription & t : transformations)
      {
        writeDebug_("Using " + String(t.getDataPoints().size()) + " points in fit.", 1);
        if (t.getDataPoints().size() > 10)
        {
          t.fitModel(model_type, model_params);
        }
        t.printSummary(getGlobalLogDebug());
        alignment_stats.emplace_back(t.getStatistics());
      }

      // determine maximum RT shift after transformation that includes all high confidence IDs
      using TrafoStat = TransformationDescription::TransformationStatistics;
      for (auto & s : alignment_stats)
      {
        OPENMS_LOG_INFO << "Alignment differences (second) for percentiles (before & after): " << endl;
        OPENMS_LOG_INFO << ListUtils::concatenate(s.percents,"%\t") << "%" << endl;
        OPENMS_LOG_INFO << "before alignment:" << endl;
        for (const auto& p : s.percents)
        {
          OPENMS_LOG_INFO << (int)s.percentiles_before[p] << "\t";
        }
        OPENMS_LOG_INFO << endl;

        OPENMS_LOG_INFO << "after alignment:" << endl;
        for (const auto& p : s.percents)
        {
          OPENMS_LOG_INFO << (int)s.percentiles_after[p] << "\t";
        }
        OPENMS_LOG_INFO << endl;
      }

      double max_alignment_diff = std::max_element(alignment_stats.begin(), alignment_stats.end(),
              [](TrafoStat a, TrafoStat b)
              { return a.percentiles_after[100] < b.percentiles_after[100]; })->percentiles_after[100];
      // sometimes, very good alignments might lead to bad overall performance. Choose 2 minutes as minimum.
      OPENMS_LOG_INFO << "Max alignment difference (seconds): " << max_alignment_diff << endl;
      max_alignment_diff = std::max(max_alignment_diff, 120.0); // minimum 2 minutes
      max_alignment_diff = std::min(max_alignment_diff, 600.0); // maximum 10 minutes
      return max_alignment_diff;
    }
    return 0;
  }

  void transform_(
    vector<FeatureMap>& feature_maps,
    vector<TransformationDescription>& transformations
  )
  {
    if (feature_maps.size() > 1 && !transformations.empty())
    {
      // Apply transformations
      for (Size i = 0; i < feature_maps.size(); ++i)
      {
        try
        {
          MapAlignmentTransformer::transformRetentionTimes(feature_maps[i],
            transformations[i]);
        } catch (Exception::IllegalArgument& e)
        {
          OPENMS_LOG_WARN << e.what() << endl;
        }

        if (debug_level_ > 666)
        {
          // plot with e.g.:
          // Rscript ../share/OpenMS/SCRIPTS/plot_trafo.R debug_trafo_1.trafoXML debug_trafo_1.pdf
          FileHandler().storeTransformations("debug_trafo_" + String(i) + ".trafoXML", transformations[i], {FileTypes::TRANSFORMATIONXML});
        }
      }
    }
  }

  //-------------------------------------------------------------
  // Link all features of this fraction
  //-------------------------------------------------------------
  /// this method will only be used during requantification.
  void link_(
    vector<FeatureMap> & feature_maps,
    double median_fwhm,
    double max_alignment_diff,
    ConsensusMap & consensus_fraction
  )
  {
    //since requantification only happens with 2+ maps, we do not need to check/skip,
    //in case of a singleton fraction. Would throw an exception in linker.group

    Param fl_param = getParam_().copy("Linking:", true);
    writeDebug_("Parameters passed to feature grouping algorithm", fl_param, 3);

    writeDebug_("Linking: " + String(feature_maps.size()) + " features.", 1);

    // grouping tolerance = max alignment error + median FWHM
    FeatureGroupingAlgorithmQT linker;
    fl_param.setValue("distance_RT:max_difference", 2.0 * max_alignment_diff + 2.0 * median_fwhm);
    linker.setParameters(fl_param);
/*
    FeatureGroupingAlgorithmKD linker;
    fl_param.setValue("warp:rt_tol", 2.0 * max_alignment_diff + 2.0 * median_fwhm);
    fl_param.setValue("link:rt_tol", 2.0 * max_alignment_diff + 2.0 * median_fwhm);
    fl_param.setValue("link:mz_tol", 10.0);
    fl_param.setValue("mz_unit", "ppm");
    linker.setParameters(fl_param);
*/
    linker.group(feature_maps, consensus_fraction);
    OPENMS_LOG_INFO << "Size of consensus fraction: " << consensus_fraction.size() << endl;
    assert(!consensus_fraction.empty());
  }

  /// Align and link.
  void alignAndLink_(
    vector<FeatureMap> & feature_maps,
    ConsensusMap & consensus_fraction,
    vector<TransformationDescription>& transformations,
    const double median_fwhm)
  {
    double max_alignment_diff(0.0);

    if (feature_maps.size() > 1)
    {
      max_alignment_diff = align_(feature_maps, transformations);

      transform_(feature_maps, transformations);

      link_(feature_maps,
        median_fwhm,
        max_alignment_diff,
        consensus_fraction);
    }
    else // only one feature map
    {
      MapConversion::convert(0, feature_maps.back(), consensus_fraction);
    }
  }

  /// determine in which runs of the current fraction a peptide was quantified
  /// returns map sequence+charge -> map index in consensus map that have non-zero quant values
  map<pair<String, UInt>, vector<int> > getPeptideOccurrence_(const ConsensusMap &cons)
  {
    map<Size, UInt> num_consfeat_of_size;
    map<Size, UInt> num_consfeat_of_size_with_id;

    map<pair<String, UInt>, vector<int> > seq_charge2map_occurence;
    for (const ConsensusFeature& cfeature : cons)
    {
      ++num_consfeat_of_size[cfeature.size()];
      const auto& pids = cfeature.getPeptideIdentifications();
      if (!pids.empty())
      {
        ++num_consfeat_of_size_with_id[cfeature.size()];

        // count how often a peptide/charge pair has been observed in the different maps
        const vector<PeptideHit>& phits = pids[0].getHits();
        if (!phits.empty())
        {
          const String s = phits[0].getSequence().toString();
          const int z = phits[0].getCharge();

          if (seq_charge2map_occurence[make_pair(s,z)].empty())
          {
            seq_charge2map_occurence[make_pair(s,z)] = vector<int>(cons.getColumnHeaders().size(), 0);
          }

          // assign id to all dimensions in the consensus feature
          for (auto const & f : cfeature.getFeatures())
          {
            Size map_index = f.getMapIndex();
            seq_charge2map_occurence[make_pair(s,z)][map_index] += 1;
          }
        }
      }
    }
    return seq_charge2map_occurence;
  }

  ExitCodes checkSingleRunPerID_(const vector<ProteinIdentification>& protein_ids, const String& id_file_abs_path)
  {
    if (protein_ids.size() != 1)
    {
      OPENMS_LOG_FATAL_ERROR << "Exactly one protein identification run must be annotated in " << id_file_abs_path << endl;
      return ExitCodes::INCOMPATIBLE_INPUT_DATA;
    }

    StringList run_paths;
    protein_ids[0].getPrimaryMSRunPath(run_paths);
    if (run_paths.size() > 1)
    {
      OPENMS_LOG_FATAL_ERROR << "ProteomicsLFQ does not support merged ID runs. ID file: " << id_file_abs_path << endl;
      return ExitCodes::INCOMPATIBLE_INPUT_DATA;
    }
    if (run_paths.empty())
    {
      OPENMS_LOG_WARN << "Warning: No mzML origin annotated in ID file. This can lead to errors or unexpected behaviour later: " << id_file_abs_path << endl;
    }

    return EXECUTION_OK;
  }

  ExitCodes switchScoreType_(PeptideIdentificationList& peptide_ids, const String& id_file_abs_path)
  {
    // Check if score types are valid. TODO
    try
    {
      IDScoreSwitcherAlgorithm switcher;
      Size c = 0;
      switcher.switchToGeneralScoreType(peptide_ids, IDScoreSwitcherAlgorithm::ScoreType::PEP, c);
    }
    catch(Exception::MissingInformation&)
    {
      OPENMS_LOG_FATAL_ERROR << "ProteomicsLFQ expects a Posterior Error Probability score in all Peptide IDs. ID file: " << id_file_abs_path << endl;
      return ExitCodes::INCOMPATIBLE_INPUT_DATA;
    }
    return EXECUTION_OK;
  }

  ExitCodes loadAndCleanupIDFile_(
    const String& id_file_abs_path,
    const String& mz_file,
    const String& in_db,
    const Size& fraction_group,
    const Size& fraction,
    vector<ProteinIdentification>& protein_ids,
    PeptideIdentificationList& peptide_ids,
    set<String>& fixed_modifications,  // adds to
    set<String>& variable_modifications) // adds to
  {

    const String& mz_file_abs_path = File::absolutePath(mz_file);
    FileHandler().loadIdentifications(id_file_abs_path, protein_ids, peptide_ids,
        {FileTypes::IDXML, FileTypes::MZIDENTML, FileTypes::IDPARQUET}, log_type_);

    ExitCodes e = checkSingleRunPerID_(protein_ids, id_file_abs_path);
    if (e != EXECUTION_OK) return e;

    // Re-index
    if (!in_db.empty())
    {
      PeptideIndexing indexer;
      Param param_pi = indexer.getParameters();
      param_pi.setValue("missing_decoy_action", "silent");
      param_pi.setValue("write_protein_sequence", "true");
      param_pi.setValue("write_protein_description", "true");
      indexer.setParameters(param_pi);

      // stream data in fasta file
      FASTAContainer<TFI_File> fasta_db(in_db);
      PeptideIndexing::ExitCodes indexer_exit = indexer.run(fasta_db, protein_ids, peptide_ids);

      picked_decoy_string_ = indexer.getDecoyString();
      picked_decoy_prefix_ = indexer.isPrefix();
      if ((indexer_exit != PeptideIndexing::ExitCodes::EXECUTION_OK) &&
          (indexer_exit != PeptideIndexing::ExitCodes::PEPTIDE_IDS_EMPTY))
      {
        if (indexer_exit == PeptideIndexing::ExitCodes::DATABASE_EMPTY)
        {
          return INPUT_FILE_EMPTY;
        }
        else if (indexer_exit == PeptideIndexing::ExitCodes::UNEXPECTED_RESULT)
        {
          return UNEXPECTED_RESULT;
        }
        else
        {
          return UNKNOWN_ERROR;
        }
      }
    }

    e = switchScoreType_(peptide_ids, id_file_abs_path);
    if (e != EXECUTION_OK) return e;

    // TODO we could think about removing this limitation but it gets complicated quickly
    IDFilter::keepBestPeptideHits(peptide_ids, false); // strict = false

    // add to the (global) set of fixed and variable modifications
    const vector<String>& var_mods = protein_ids[0].getSearchParameters().variable_modifications;
    const vector<String>& fixed_mods = protein_ids[0].getSearchParameters().fixed_modifications;
    std::copy(var_mods.begin(), var_mods.end(), std::inserter(variable_modifications, variable_modifications.begin()));
    std::copy(fixed_mods.begin(), fixed_mods.end(), std::inserter(fixed_modifications, fixed_modifications.end()));

    // delete meta info to free some space
    for (PeptideIdentification & pid : peptide_ids)
    {
      // we currently can't clear the PeptideIdentification meta data
      // because the spectrum_reference is stored in the meta value (which it probably shouldn't)
      // TODO: pid.clearMetaInfo(); if we move it to the PeptideIdentification structure
      for (PeptideHit & ph : pid.getHits())
      {
        // TODO: we only have super inefficient meta value removal
        vector<String> keys;
        ph.getKeys(keys);
        for (const auto& k : keys)
        {
          if (!(k.hasSubstring("_score")
            || k.hasSubstring("q-value")
            || k.hasPrefix("Luciphor_global_flr")
            || k == "target_decoy") // keep target_decoy information for QC
            )
          {
            ph.removeMetaValue(k);
          }
        }
        // we only clear selected metavalues
        //ph.clearMetaInfo();
      }
    }

    ///////////////////////////////////////////////////////
    // annotate experimental design
    // check and reannotate mzML file in ID
    StringList id_msfile_ref;
    protein_ids[0].getPrimaryMSRunPath(id_msfile_ref);

    // fix other problems like missing MS run path annotations
    if (id_msfile_ref.empty())
    {
      OPENMS_LOG_WARN  << "MS run path not set in ID file: " << id_file_abs_path << endl
                       << "Resetting reference to MS file provided at same input position." << endl;
    }
    else if (id_msfile_ref.size() == 1)
    {
      // Check if the annotated primary MS run filename matches the mzML filename (comparison by base name)
      const String& in_bn = File::stemName(mz_file_abs_path);
      const String& id_primaryMSRun_bn = File::stemName(id_msfile_ref[0]);

      if (in_bn != id_primaryMSRun_bn)  // mismatch between annotation in ID file and provided mzML file
      {
        OPENMS_LOG_WARN << "MS run path referenced from ID file does not match MS file at same input position: " << id_file_abs_path << endl
                        << "Resetting reference to MS file provided at same input position." << endl;
      }
    }
    else
    {
      OPENMS_LOG_WARN << "Multiple MS files referenced from ID file: " << id_file_abs_path << endl
                      << "Resetting reference to MS file provided at same input position." << endl;
    }
    id_msfile_ref = StringList{mz_file};
    protein_ids[0].setPrimaryMSRunPath(id_msfile_ref);
    protein_ids[0].setMetaValue("fraction_group", fraction_group);
    protein_ids[0].setMetaValue("fraction", fraction);

    // update identifiers to make them unique
    // fixes some bugs related to users splitting the original mzML and id files before running the analysis
    // in that case these files might have the same identifier
    const String old_identifier = protein_ids[0].getIdentifier();
    const String new_identifier = old_identifier + "_" + String(fraction_group) + "F" + String(fraction);
    protein_ids[0].setIdentifier(new_identifier);
    for (PeptideIdentification & p : peptide_ids)
    {
      if (p.getIdentifier() == old_identifier)
      {
        p.setIdentifier(new_identifier);
      }
      else
      {
        OPENMS_LOG_WARN << "Peptide ID identifier found not present in the protein ID" << endl;
      }
    }

    bool missing_spec_ref(false);
    for (const PeptideIdentification & pid : peptide_ids)
    {
      if (!pid.metaValueExists(Constants::UserParam::SPECTRUM_REFERENCE)
        || pid.getMetaValue(Constants::UserParam::SPECTRUM_REFERENCE).toString().empty())
      {
        missing_spec_ref = true;
        break;
      }
    }
    // reannotate spectrum references if missing
    if (missing_spec_ref)
    {
      OPENMS_LOG_WARN << "Warning: Identification file " << id_file_abs_path << " contains IDs without meta value for the spectrum native id.\n"
                         "OpenMS will try to reannotate them by matching retention times between ID and spectra." << endl;

      SpectrumMetaDataLookup::addMissingSpectrumReferences(
        peptide_ids,
        mz_file_abs_path,
        true);
    }

    return EXECUTION_OK;
  }


  void printMetaValues(const FeatureMap& tmp)
  {
    if (tmp.empty())
    {
      OPENMS_LOG_WARN << "printMetaValues called with empty FeatureMap.\n";
      return;
    }

    // extract meta value keys from the first element (which might be a normal or OffsetPeptide -> extract only the common ones)
    std::vector<String> keys;
    tmp[0].getKeys(keys);
    if (auto it = std::find(keys.begin(), keys.end(), "OffsetPeptide"); it != keys.end())
    {
      keys.erase(it);
    }

    OPENMS_LOG_INFO << "keys: ";
    for (const auto& k : keys) { OPENMS_LOG_INFO << k << " "; }
    OPENMS_LOG_INFO << "\n";

    for (const auto& f : tmp)
    {
      if (f.metaValueExists("OffsetPeptide")) continue;
      for (const auto& k : keys)
      {
        OPENMS_LOG_INFO << f.getMetaValue(k) << " ";
      }
      OPENMS_LOG_INFO << "\n";
    }
  }

  ExitCodes quantifyFraction_(
    const pair<UInt, std::vector<String> > & ms_files,
    const map<String, String>& mzfile2idfile,
    const String& in_db,
    double median_fwhm,
    ConsensusMap & consensus_fraction,
    set<String>& fixed_modifications,
    set<String>& variable_modifications)
  {
    vector<TransformationDescription> transformations;
    vector<FeatureMap> feature_maps;
    const Size fraction = ms_files.first;

    const StringList in_feat_list = getStringList_("in_feat");
    const StringList in_list      = getStringList_("in");

    writeDebug_("Processing fraction number: " + String(fraction) + "\nFiles: ",  1);
    for (String const & mz_file : ms_files.second) { writeDebug_(mz_file,  1); }

    StringList id_MS_run_ref;
    StringList in_MS_run = ms_files.second;
    const auto& path_label_to_fractiongroup = design_.getPathLabelToFractionGroupMapping(true);

    for (String const & mz_file : ms_files.second)
    {
      const Size fraction_group = path_label_to_fractiongroup.at({File::basename(mz_file), 1});
      writeDebug_("Processing file: " + mz_file,  1);

      vector<ProteinIdentification> protein_ids;
      PeptideIdentificationList peptide_ids;
      const String& mz_file_abs_path = File::absolutePath(mz_file);
      const String& id_file_abs_path = File::absolutePath(mzfile2idfile.at(mz_file_abs_path));

      {
        ExitCodes e = loadAndCleanupIDFile_(id_file_abs_path, mz_file, in_db, fraction_group, fraction, protein_ids, peptide_ids, fixed_modifications, variable_modifications);
        if (e != EXECUTION_OK) return e;
      }

      MSExperiment ms_centroided;
      bool is_im_peak_data = false;
      const bool mass_recalibration = (getStringOption_("mass_recalibration") == "true");

      if (!in_feat_list.empty() && mass_recalibration)
      {
        throw Exception::InvalidParameter(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION,
          "Option '-mass_recalibration' is not supported together with '-in_feat' because pre-computed features bypass internal feature finding.");
      }

      const bool requires_ms_data = in_feat_list.empty();

      if (requires_ms_data)
      {
        ExitCodes e = loadAndPreprocess_(mz_file, ms_centroided, is_im_peak_data);
        if (e != EXECUTION_OK) { return e; }

        SpectrumMetaDataLookup::addMissingFAIMSToPeptideIDs(peptide_ids, ms_centroided);

        if (is_im_peak_data && mass_recalibration)
        {
          OPENMS_LOG_WARN << "Warning: mass_recalibration is not supported for .d input. Disabling.\n";
        }

        if (mass_recalibration && !is_im_peak_data)
        {
          String debug_output_basename = (debug_level_ > 666) ? id_file_abs_path : "";
          DDAWorkflowCommons::recalibrateMS1(ms_centroided, peptide_ids, debug_output_basename);
        }

        if (!is_im_peak_data)
        {
          median_fwhm = DDAWorkflowCommons::estimateMedianChromatographicFWHM(ms_centroided);
          OPENMS_LOG_INFO << "Median chromatographic FWHM: " << median_fwhm << "\n";
        }
        // For .d/IM_PEAK: FWHM is estimated from Biosaur2 features below (after seed generation)
      }

      // For .d/IM_PEAK + targeted_only: no Biosaur2 seeds to estimate FWHM from, use default
      if (is_im_peak_data && median_fwhm == 0.0)
      {
        median_fwhm = 30.0;
        OPENMS_LOG_INFO << "Using default FWHM of " << median_fwhm << " s for .d input (no seed-based estimate available).\n";
      }

      StringList id_msfile_ref;
      protein_ids[0].getPrimaryMSRunPath(id_msfile_ref);
      id_MS_run_ref.push_back(id_msfile_ref[0]);

      FeatureMap seeds;
      seeds.setPrimaryMSRunPath({mz_file});

      const bool targeted_only = getStringOption_("targeted_only") != "false";

      if (!targeted_only && in_feat_list.empty())
      {
        String seeding_algorithm = getStringOption_("Seeding:algorithm");

        // Force biosaur2 for IM_PEAK data (Multiplex cannot handle it)
        if (is_im_peak_data && seeding_algorithm != "biosaur2")
        {
          OPENMS_LOG_WARN << "Warning: IM_PEAK data detected. Forcing Seeding:algorithm to 'biosaur2' "
                          << "(FeatureFinderMultiplex does not support IM_PEAK format).\n";
          seeding_algorithm = "biosaur2";
        }

        if (seeding_algorithm == "biosaur2")
        {
          OPENMS_LOG_INFO << "Using Biosaur2Algorithm for seed detection.\n";
          Biosaur2Algorithm bio;
          Param bio_param = getParam_().copy("Seeding:Biosaur2:", true);
          bio.setParameters(bio_param);
          // For non-FAIMS data (including .d), Biosaur2 processes ms_data_ in-place
          // without moving it, so we can use move here and retrieve it after run().
          // For FAIMS data, ms_data_ is consumed (split by CV), but ProteomicsLFQ's
          // FAIMS path uses FFId's own FAIMS splitting, so this is not an issue.
          bio.setMSData(std::move(ms_centroided));

          bio.run(seeds);
          OPENMS_LOG_INFO << "Biosaur2 produced " << seeds.size() << " seed features.\n";

          // For .d/IM_PEAK: estimate FWHM from Biosaur2 feature convex hulls
          // Use FWHM ≈ 0.59 * (rt_end - rt_start), the Gaussian correction from base width to half-max width
          if (is_im_peak_data)
          {
            std::vector<double> fwhm_values;
            fwhm_values.reserve(seeds.size());
            for (const auto& f : seeds)
            {
              const auto& hulls = f.getConvexHulls();
              if (hulls.empty()) continue;
              const auto& bb = hulls[0].getBoundingBox();
              double base_width = bb.maxX() - bb.minX(); // full RT extent
              double fwhm = base_width * 0.59;           // Gaussian: FWHM ≈ 2.35σ, base ≈ 4σ → ratio ≈ 0.59
              if (fwhm > 0.0) { fwhm_values.push_back(fwhm); }
            }
            if (fwhm_values.size() >= 10)
            {
              median_fwhm = Math::median(fwhm_values.begin(), fwhm_values.end());
            }
            else
            {
              median_fwhm = 30.0; // fallback
              OPENMS_LOG_WARN << "Warning: Too few Biosaur2 features (" << fwhm_values.size()
                              << ") to estimate FWHM. Using default: " << median_fwhm << " seconds.\n";
            }
            OPENMS_LOG_INFO << "Median chromatographic FWHM (from Biosaur2): " << median_fwhm << "\n";
          }

          // Retrieve ms_data_ back from Biosaur2 (non-FAIMS path preserves it in-place)
          ms_centroided = std::move(bio.getMSData());
        }
        else
        {
          DDAWorkflowCommons::calculateSeeds(ms_centroided, getDoubleOption_("Seeding:intThreshold"), seeds, median_fwhm, 2, 5);
        }

        if (debug_level_ > 666)
        {
          FileHandler().storeFeatures("debug_seeds_fraction_" + String(ms_files.first) + "_" + String(fraction_group) + ".featureXML", seeds, {FileTypes::FEATUREXML}, log_type_);
        }
      }

      /////////////////////////////////////////////////
      // Feature detection or loading pre-computed features
      FeatureMap fm;

      if (!in_feat_list.empty())
      {
        OPENMS_LOG_INFO << "Bypassing FeatureFinderIdentification. Loading pre-computed features...\n";

        auto it = std::find(in_list.begin(), in_list.end(), mz_file);
        if (it == in_list.end())
        {
          throw Exception::IllegalArgument(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION, "Current mzML file not found in the -in list.");
        }
        Size file_idx = static_cast<Size>(std::distance(in_list.begin(), it));

        FileHandler().loadFeatures(in_feat_list[file_idx], fm, {FileTypes::FEATUREXML}, log_type_);

        StringList run_paths;
        fm.getPrimaryMSRunPath(run_paths);
        if (run_paths.empty())
        {
          fm.setPrimaryMSRunPath({mz_file});
        }
        else if (File::stemName(run_paths[0]) !=
                 File::stemName(mz_file))
        {
          OPENMS_LOG_WARN << "Primary MS run path in featureXML (" << run_paths[0]
                          << ") does not match the mzML at the same position (" << mz_file
                          << "). Keeping featureXML annotation.\n";
        }

        if (!fm.getProteinIdentifications().empty())
        {
          OPENMS_LOG_WARN << "Warning: Loaded featureXML already contains protein identifications. They will be overwritten.\n";
        }
        fm.setProteinIdentifications(protein_ids);

        if (!fm.getUnassignedPeptideIdentifications().empty())
        {
          OPENMS_LOG_WARN << "Warning: Loaded featureXML already contains unassigned peptide identifications. They will be overwritten.\n";
        }
        fm.setUnassignedPeptideIdentifications(peptide_ids);

        const String expected_identifier = protein_ids[0].getIdentifier();
        Size updated_feature_pid_ids = 0;
        for (Feature& feature : fm)
        {
          auto f_pids = feature.getPeptideIdentifications();
          bool updated = false;
          for (auto& pid : f_pids)
          {
            if (pid.getIdentifier() != expected_identifier)
            {
              pid.setIdentifier(expected_identifier);
              ++updated_feature_pid_ids;
              updated = true;
            }
          }
          if (updated) feature.setPeptideIdentifications(f_pids);
        }
        if (updated_feature_pid_ids > 0)
        {
          OPENMS_LOG_WARN << "Updated " << updated_feature_pid_ids
                          << " feature-level peptide identifiers to match injected run identifier.\n";
        }
      }
      else
      {
        // Run FeatureFinderIdentification
        FeatureFinderIdentificationAlgorithm ffi;
        ffi.getMSData().swap(ms_centroided);
        ffi.getProgressLogger().setLogType(log_type_);

        Param ffi_param = getParam_().copy("PeptideQuantification:", true);
        ffi_param.setValue("detect:peak_width", 5.0 * median_fwhm);
        ffi_param.setValue("debug", debug_level_); // pass down debug level

        // Note: no IM_window override needed — BrukerTimsFile loads with built-in IM centroiding
        // (ms1_centroid_mz_ppm=5, ms1_centroid_im_pct=3), so data is IM_CENTROIDED and the
        // default IM_window=0.06 is appropriate for matching centroided IM positions.

        double feature_with_id_min_score = getDoubleOption_("feature_with_id_min_score");
        double feature_without_id_min_score = getDoubleOption_("feature_without_id_min_score");
        const bool filter_by_quant_scores = (feature_with_id_min_score > 0.0) && (targeted_only ||(feature_without_id_min_score > 0.0));

        if (filter_by_quant_scores)
        {
          OPENMS_LOG_INFO << "Adding offset peptides as quant. decoys.\n";
          ffi_param.setValue("add_mass_offset_peptides", 10.005);
        }

        ffi.setParameters(ffi_param);
        writeDebug_("Parameters passed to FeatureFinderIdentification algorithm", ffi_param, 3);

        {
          vector<ProteinIdentification> ext_protein_ids;
          PeptideIdentificationList ext_peptide_ids;

          ffi.run(peptide_ids,
                  protein_ids,
                  ext_peptide_ids,
                  ext_protein_ids,
                  fm, // fills fm
                  seeds,
                  mz_file);
        }

        if (filter_by_quant_scores)
        {
          SimpleSVM::PredictorMap predictors;
          map<Size, double> labels;
          size_t current_row = 0;
          size_t quant_target{}, quant_decoy{};

          Math::RandomShuffler shuffler;
          std::vector<size_t> randomized_indices(fm.size());
          std::iota(randomized_indices.begin(), randomized_indices.end(), 0);

          for (auto & i : randomized_indices)
          {
            const auto& f = fm[i];
            predictors["var_library_sangle"].push_back(f.getMetaValue("var_library_sangle"));
            predictors["var_xcorr_shape"].push_back(f.getMetaValue("var_xcorr_shape"));
            predictors["total_xic"].push_back(f.getMetaValue("total_xic"));
            predictors["var_elution_model_fit_score"].push_back(f.getMetaValue("var_elution_model_fit_score"));

            bool is_offset = f.metaValueExists("OffsetPeptide");
            bool has_id = !f.getPeptideIdentifications().empty();
            if (is_offset)
            {
              if (quant_decoy < 1000)
              {
                labels[current_row] = 0.0;
                ++quant_decoy;
              }
            }
            else
            {
              if (has_id && quant_target < 1000)
              {
                labels[current_row] = 1.0;
                ++quant_target;
              }
            }
            ++current_row;
          }

          if (quant_decoy > 4 && quant_target > 4)
          {
            SimpleSVM svm;
            Param svm_param = svm.getParameters();
            svm_param.setValue("kernel", "linear");
            svm_param.setValue("log2_C", ListUtils::create<double>("-5,-1,1,5,7,11,15"));
            svm_param.setValue("log2_p", ListUtils::create<double>("-15,-9,-6,-3.32192809489,0,3.32192809489,6,9,15"));

            svm.setParameters(svm_param);
            svm.setup(predictors, labels);
            vector<SimpleSVM::Prediction> predictions;
            OPENMS_LOG_INFO << "Predicting class probabilities:" << endl;
            svm.predict(predictions);
            std::map<String, double> feature_weights;
            svm.getFeatureWeights(feature_weights);

            size_t current_row_pred{};
            for (auto & i : randomized_indices)
            {
              auto& f = fm[i];
              f.setMetaValue("p_quant", (double)predictions[current_row_pred].probabilities[1]);
              ++current_row_pred;
            }
          }

          if (quant_decoy > 4 && quant_target > 4)
          {
            fm.erase(std::remove_if(fm.begin(), fm.end(),
              [&](const Feature& f)
              {
                double quant_score = f.getMetaValue("p_quant");
                bool is_offset = f.metaValueExists("OffsetPeptide");
                bool has_id = !f.getPeptideIdentifications().empty();
                bool untargeted_feature = !is_offset && !has_id;
                bool is_feature_with_id = !is_offset && has_id;

                if (is_feature_with_id && quant_score < feature_with_id_min_score) return true;
                if (untargeted_feature && quant_score < feature_without_id_min_score) return true;
                if (is_offset && quant_score < feature_without_id_min_score) return true;
                return false;
              }),
              fm.end());

            fm.erase(std::remove_if(fm.begin(), fm.end(),
              [](const Feature& f){return f.metaValueExists("OffsetPeptide");}),
              fm.end());
          }
        }
      } // <--- END OF ELSE BLOCK

      unordered_set<String> keep_meta = {"OffsetPeptide", "IM_median", "IM_min", "IM_max"};
      for (auto & f : fm)
      {
        std::vector<String> keys;
        f.getKeys(keys);
        for (const auto& k : keys)
        {
          if (auto it = keep_meta.find(k); it == keep_meta.end()) f.removeMetaValue(k);
        }
        f.setSubordinates({});
        f.setConvexHulls({});
      }

      IDConflictResolverAlgorithm::resolve(fm, getStringOption_("keep_feature_top_psm_only") == "false");

      feature_maps.emplace_back(std::move(fm));

      if (debug_level_ > 666)
      {
        FileHandler().storeFeatures("debug_fraction_" + String(ms_files.first) + "_" + String(fraction_group) + ".featureXML", feature_maps.back(), {FileTypes::FEATUREXML}, log_type_);
      }
    } // <--- END OF FOR LOOP OVER MS FILES

    auto validation_result = File::validateMatchingFileNames(in_MS_run, id_MS_run_ref, true, true);
    switch(validation_result)
    {
      case File::MatchingFileListsStatus::SET_MISMATCH:
        throw Exception::IllegalArgument(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION, "MS run path reference in ID files and spectra filenames differ.");
      case File::MatchingFileListsStatus::ORDER_MISMATCH:
        throw Exception::IllegalArgument(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION, "MS run path reference in ID files and spectra filenames match but order differs.");
      case File::MatchingFileListsStatus::MATCH:
        writeLogInfo_("ID files reference same names as spectra files.");
        break;
    }

    alignAndLink_(feature_maps, consensus_fraction, transformations, median_fwhm);

    if (feature_maps.size() > 1)
    {
      addDataProcessing_(consensus_fraction, getProcessingInfo_(DataProcessing::ALIGNMENT));
      addDataProcessing_(consensus_fraction, getProcessingInfo_(DataProcessing::FEATURE_GROUPING));
    }

    Size j(0);
    const auto& path_label_to_sampleidx = design_.getPathLabelToSampleMapping(true);
    for (String const & mz_file : ms_files.second)
    {
      const Size curr_fraction_group = path_label_to_fractiongroup.at({File::basename(mz_file), 1});
      consensus_fraction.getColumnHeaders()[j].label = "label-free";
      consensus_fraction.getColumnHeaders()[j].filename = mz_file;
      consensus_fraction.getColumnHeaders()[j].unique_id = feature_maps[j].getUniqueId();
      consensus_fraction.getColumnHeaders()[j].setMetaValue("fraction", fraction);
      consensus_fraction.getColumnHeaders()[j].setMetaValue("fraction_group", curr_fraction_group);
      const auto& sample_index = path_label_to_sampleidx.at({File::basename(mz_file), 1});
      const auto& sample_name = design_.getSampleSection().getSampleName(sample_index);
      consensus_fraction.getColumnHeaders()[j].setMetaValue("sample_name", sample_name);
      ++j;
    }

    consensus_fraction.applyMemberFunction(&UniqueIdInterface::setUniqueId);
    consensus_fraction.sortPeptideIdentificationsByMapIndex();
    IDConflictResolverAlgorithm::resolve(consensus_fraction, true);

    if (getStringOption_("out_msstats").empty() && getStringOption_("out_triqler").empty())
    {
      ConsensusMapNormalizerAlgorithmMedian::normalizeMaps(consensus_fraction, ConsensusMapNormalizerAlgorithmMedian::NM_SCALE, "", "");
    }

    return EXECUTION_OK;
  }


  ExitCodes inferProteinGroups_(ConsensusMap& consensus,
    const set<String>& fixed_modifications)
  {
    // since we don't require an index as input but need to calculate e.g., coverage we reindex here (fast)

    //-------------------------------------------------------------
    // Protein inference
    //-------------------------------------------------------------
    // TODO: This needs to be rewritten to work directly on the quant data.
    //  of course we need to provide options to keep decoys and unassigned PSMs all the way through quantification.
    // TODO: Think about ProteinInference on IDs only merged per condition
    bool groups = getStringOption_("protein_quantification") != "strictly_unique_peptides";
    bool bayesian = getStringOption_("protein_inference") == "bayesian";
    bool greedy_group_resolution = getStringOption_("protein_quantification") == "shared_peptides";

    // Study-wide inference operates on a single merged ID run.
    ConsensusMapMergerAlgorithm cmerge;
    // The following will result in a SINGLE protein run for the whole consensusMap.
    cmerge.mergeAllIDRuns(consensus);

    if (!bayesian) // simple aggregation
    {
      BasicProteinInferenceAlgorithm bpia;
      auto bpiaparams = bpia.getParameters();
      bpiaparams.setValue("annotate_indistinguishable_groups", groups ? "true" : "false");
      bpiaparams.setValue("greedy_group_resolution", greedy_group_resolution ? "true" : "false");
      bpia.setParameters(bpiaparams);

      // TODO parameterize if unassigned IDs without feature should contribute?
      bpia.run(consensus, consensus.getProteinIdentifications()[0], true);
    }
    else // if (bayesian)
    {
      BayesianProteinInferenceAlgorithm bayes;
      auto bayesparams = bayes.getParameters();
      // We need all PSMs to collect all possible modifications, to do spectral counting and to do PSM FDR.
      // In theory, if none is needed we can save memory. For quantification,
      // we basically discard peptide+PSM information from inference and use the info from the cMaps.
      bayesparams.setValue("keep_best_PSM_only", "false");
      bayes.setParameters(bayesparams);
      //bayesian inference automatically annotates groups, therefore remove them later
      bayes.inferPosteriorProbabilities(consensus, greedy_group_resolution);
      if (!groups)
      {
        // should be enough to just clear the groups. Only indistinguishable will be annotated above.
        consensus.getProteinIdentifications()[0].getIndistinguishableProteins().clear();
      }
    }

    // TODO think about order of greedy resolution, FDR calc and filtering

    //-------------------------------------------------------------
    // Protein (and additional peptide?) FDR
    //-------------------------------------------------------------
    const double max_fdr = getDoubleOption_("proteinFDR");
    const bool picked = getStringOption_("picked_proteinFDR") == "true";

    //TODO use new FDR_type parameter
    const double max_psm_fdr = getDoubleOption_("psmFDR");
    FalseDiscoveryRate fdr;
    if (getFlag_("PeptideQuantification:quantify_decoys"))
    {
      Param fdr_param = fdr.getParameters();
      fdr_param.setValue("add_decoy_peptides", "true");
      fdr_param.setValue("add_decoy_proteins", "true");
      fdr.setParameters(fdr_param);
    }

    // ensure that only one final inference result is generated for now
    assert(consensus.getProteinIdentifications().size() == 1);

    auto& overall_proteins = consensus.getProteinIdentifications()[0];
    if (!picked)
    {
      fdr.applyBasic(overall_proteins);
    }
    else
    {
      fdr.applyPickedProteinFDR(overall_proteins, picked_decoy_string_, picked_decoy_prefix_);
    }

    bool pepFDR = getStringOption_("FDR_type") == "PSM+peptide";
    //TODO Think about the implications of mixing PSMs from different files and searches.
    //  Score should be PEPs here. We could extract the original search scores, depending on preprocessing. PEPs allow some normalization but will
    //  disregard the absolute score differences between runs (i.e. if scores in one run are all lower than the ones in another run,
    //  do you want to filter them out preferably or do you say: this was a faulty run, if the decoys are equally bad, I want the
    //  best targets to be treated like the best targets from the other runs, even if the absolute match scores are much lower).
    if (pepFDR)
    {
      fdr.applyBasicPeptideLevel(consensus, true);
    }
    else
    {
      fdr.applyBasic(consensus, true);
    }

    if (!getFlag_("PeptideQuantification:quantify_decoys"))
    { // FDR filtering removed all decoy proteins -> update references and remove all unreferenced (decoy) PSMs
      IDFilter::removeDanglingProteinReferences(consensus, true);
      IDFilter::removeUnreferencedProteins(consensus, true); // if we don't filter peptides for now, we don't need this
      IDFilter::updateProteinGroups(overall_proteins.getIndistinguishableProteins(),
                                    overall_proteins.getHits());
      IDFilter::updateProteinGroups(overall_proteins.getProteinGroups(),
                                    overall_proteins.getHits());
    }

    // FDR filtering
    if (max_psm_fdr < 1.) // PSM level
    {
      for (auto& f : consensus)
      {
        IDFilter::filterHitsByScore(f.getPeptideIdentifications(), max_psm_fdr);
      }
      IDFilter::filterHitsByScore(consensus.getUnassignedPeptideIdentifications(), max_psm_fdr);
    }

    if (max_fdr < 1.) // protein level
    {
      IDFilter::filterHitsByScore(overall_proteins, max_fdr);
    }

    if (max_fdr < 1. || !getFlag_("PeptideQuantification:quantify_decoys"))
    {
      IDFilter::removeDanglingProteinReferences(consensus, true);
    }

    if (max_psm_fdr < 1.)
    {
      IDFilter::removeUnreferencedProteins(consensus, true);
    }

    if (max_fdr < 1. || max_psm_fdr < 1. || !getFlag_("PeptideQuantification:quantify_decoys"))
    {
      IDFilter::updateProteinGroups(overall_proteins.getIndistinguishableProteins(), overall_proteins.getHits());
      IDFilter::updateProteinGroups(overall_proteins.getProteinGroups(), overall_proteins.getHits());
    }

    if (overall_proteins.getHits().empty())
    {
      throw Exception::MissingInformation(
          __FILE__,
          __LINE__,
          OPENMS_PRETTY_FUNCTION,
          "No proteins left after FDR filtering. Please check the log and adjust your settings.");
    }

    // do we only want to keep strictly unique peptides (e.g., no groups)?
    // This filters for the VERY initially computed theoretical uniqueness calculated by PeptideIndexer
    //  which also means that e.g., target+decoy peptides are not unique
    if (!greedy_group_resolution && !groups)
    {
      for (auto& f : consensus)
      {
        IDFilter::keepUniquePeptidesPerProtein(f.getPeptideIdentifications());
      }
      IDFilter::keepUniquePeptidesPerProtein(consensus.getUnassignedPeptideIdentifications());
    }

    // compute coverage (sequence was annotated during PeptideIndexing)
    // TODO: do you really want to compute coverage from unquantified peptides also?
    overall_proteins.computeCoverage(consensus, true);

    // TODO: this might not be correct if only the best peptidoform is kept
    // determine observed modifications (exclude fixed mods)
    overall_proteins.computeModifications(consensus, StringList(fixed_modifications.begin(), fixed_modifications.end()), true);

    return EXECUTION_OK;
  }



  ExitCodes main_(int, const char **) override
  {
    //-------------------------------------------------------------
    // Parameter handling
    //-------------------------------------------------------------

    // Read tool parameters
    StringList in = getStringList_("in");
    String out = getStringOption_("out");
    String out_msstats = getStringOption_("out_msstats");
    String out_triqler = getStringOption_("out_triqler");
    StringList in_ids = getStringList_("ids");
    String design_file = getStringOption_("design");
    String in_db = getStringOption_("fasta");
    StringList in_feat = getStringList_("in_feat");

    // Validate parameters
    if (!in_feat.empty() && in_feat.size() != in.size())
    {
      throw Exception::InvalidParameter(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION,
        "Number of featureXML files (-in_feat, " + String(in_feat.size()) +
        ") must match number of mzML files (-in, " + String(in.size()) + ").");
    }
    if (in.size() != in_ids.size())
    {
      throw Exception::InvalidParameter(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION,
        "Number of spectra files (" + String(in.size()) + ") must match number of ID files (" + String(in_ids.size()) + ").");
    }
    if (getStringOption_("quantification_method") == "spectral_counting")
    {
      if (!out_msstats.empty())
      {
        throw Exception::InvalidParameter(__FILE__, __LINE__,
          OPENMS_PRETTY_FUNCTION, "MSstats export for spectral counting data not supported. Please remove output file.");
      }
      if (!out_triqler.empty())
      {
        throw Exception::InvalidParameter(__FILE__, __LINE__,
          OPENMS_PRETTY_FUNCTION, "Triqler export for spectral counting data not supported. Please remove output file.");
      }
    }

    //-------------------------------------------------------------
    // Experimental design: read or generate default
    //-------------------------------------------------------------
    if (!design_file.empty())
    { // load from file
      design_ = ExperimentalDesignFile::load(design_file, false);
    }
    else
    {
      OPENMS_LOG_INFO << "No experimental design file provided.\n"
                      << "Assuming a label-free experiment without fractionation.\n"
                      << endl;

      TextFile design_table;
      design_table.addLine("Fraction_Group\tFraction\tSpectra_Filepath\tLabel\tSample\tMSstats_Condition\tMSstats_BioReplicate");

      Size count{1};
      for (String & s : in)
      {
        design_table.addLine(String(count) + "\t1\t" + s +"\t1\tSample" + String(count) + "\t" + String(count)+ "\t" + String(count));
        ++count;
      }
      design_ = ExperimentalDesignFile::load(design_table, "--no design file--", false);
    }

    // some sanity checks
    // extract basenames from experimental design and input files
    const auto& pl2fg = design_.getPathLabelToFractionGroupMapping(true);
    set<String> ed_basenames;
    for (const auto& p : pl2fg)
    {
      const String& filename = p.first.first;
      ed_basenames.insert(filename);
    }

    set<String> in_basenames;
    for (const auto & f : in)
    {
      const String& in_bn = File::basename(f);
      in_basenames.insert(in_bn);
    }

    if (!std::includes(ed_basenames.begin(), ed_basenames.end(), in_basenames.begin(), in_basenames.end()))
    {
      throw Exception::InvalidParameter(__FILE__, __LINE__,
        OPENMS_PRETTY_FUNCTION, "Spectra file basenames provided as input need to match a subset the experimental design file basenames.");
    }

    Size nr_filtered = design_.filterByBasenames(in_basenames);
    if (nr_filtered > 0)
    {
      OPENMS_LOG_WARN << "WARNING: " << nr_filtered << " files from experimental design were not passed as mzMLs. Continuing with subset if the fractions still match." << std::endl;
    }

    if (design_.getNumberOfLabels() != 1)
    {
      throw Exception::InvalidParameter(__FILE__, __LINE__,
        OPENMS_PRETTY_FUNCTION, "Experimental design is not label-free as it contains multiple labels.");
    }
    if (!design_.sameNrOfMSFilesPerFraction())
    {
      OPENMS_LOG_WARN << "WARNING: Different number of fractions for different samples provided. Support maybe limited in ProteomicsLFQ." << std::endl;
    }

    std::map<unsigned int, std::vector<String> > frac2ms = design_.getFractionToMSFilesMapping();

    // experimental design file could contain URLs etc. that we want to overwrite with the actual input files
    for (auto & fraction_ms_files : frac2ms)
    {
      for (auto & s : fraction_ms_files.second)
      { // for all ms files of current fraction number
        // if basename in experimental design matches to basename in input file
        // overwrite experimental design to point to existing file (and only if they were different)
        if (auto it = std::find_if(in.begin(), in.end(),
              [&s] (const String& in_filename) { return File::basename(in_filename) == File::basename(s); }); // basename matches?
                 it != in.end() && s != *it) // and differ?
        {
          OPENMS_LOG_INFO << "Path of spectra files differ between experimental design (1) and input (2). Using the path of the input file as "
                          << "we know this file exists on the file system: '" << *it << "' vs. '" << s << endl;
          s = *it; // overwrite filename in design with filename in input files
        }
      }

    }

    for (auto & f : frac2ms)
    {
      writeDebug_("Fraction " + String(f.first) + ":", 10);
      for (const String & s : f.second)
      {
        writeDebug_("MS file: " + s, 10);
      }
    }

    // Map between mzML file and corresponding id file
    // We assume that these are provided in the exact same order.
    map<String, String> mzfile2idfile = DDAWorkflowCommons::mapMzML2Ids(in, in_ids);
    map<String, String> idfile2mzfile = DDAWorkflowCommons::mapId2MzMLs(mzfile2idfile);

    // TODO maybe check if mzMLs in experimental design match to mzMLs passed as in parameter
    //  IF both are present


    Param pep_param = getParam_().copy("Posterior Error Probability:", true);
    writeDebug_("Parameters passed to PEP algorithm", pep_param, 3);

    // TODO: inference parameter

    Param pq_param = getParam_().copy("ProteinQuantification:", true);
    writeDebug_("Parameters passed to PeptideAndProteinQuant algorithm", pq_param, 3);


    Param com_param = getParam_().copy("algorithm:common:", true);
    writeDebug_("Common parameters passed to both sub-algorithms (mtd and epd)", com_param, 3);

    set<String> fixed_modifications, variable_modifications;

    //-------------------------------------------------------------
    // Loading input
    //-------------------------------------------------------------
    ConsensusMap consensus;

    //-------------------------------------------------------------
    // feature-based quantifications
    //-------------------------------------------------------------
    if (getStringOption_("quantification_method") == "feature_intensity")
    {
      OPENMS_LOG_INFO << "Performing feature intensity-based quantification." << endl;
      double median_fwhm(0);
      for (auto const & ms_files : frac2ms) // for each fraction->ms file(s)
      {
        ConsensusMap consensus_fraction; // quantitative result for this fraction identifier

        ExitCodes e = quantifyFraction_(
          ms_files,
          mzfile2idfile,
          in_db,
          median_fwhm,
          consensus_fraction,
          fixed_modifications,
          variable_modifications);

        if (e != EXECUTION_OK) { return e; }

        consensus.appendColumns(consensus_fraction);  // append consensus map calculated for this fraction number
      }  // end of scope of fraction related data

      consensus.sortByPosition();
      consensus.sortPeptideIdentificationsByMapIndex();

      if (debug_level_ >= 666)
      {
        FileHandler().storeConsensusFeatures("debug_after_normalization.consensusXML", consensus, {FileTypes::CONSENSUSXML}, log_type_);
      }
    }
    else if (getStringOption_("quantification_method") == "spectral_counting")
    {
      OPENMS_LOG_INFO << "Performing spectral counting-based quantification." << endl;

      // init consensus map with basic experimental design information
      consensus.setExperimentType("label-free");

      auto& all_protein_ids = consensus.getProteinIdentifications();
      auto& all_peptide_ids = consensus.getUnassignedPeptideIdentifications();

      Size run_index(0);
      for (auto const & ms_files : frac2ms) // for each fraction->ms file(s) e.g.: Fraction1->FileA,FileB,FileC
      {
        const Size& fraction = ms_files.first;

        // debug output
        writeDebug_("Processing fraction number: " + String(fraction) + "\nFiles: ",  1);
        for (String const & mz_file : ms_files.second) { writeDebug_(mz_file,  1); }

        // for sanity checks we collect the primary MS run basenames as well as the ones stored in the ID files (below)
        StringList id_MS_run_ref;
        StringList in_MS_run = ms_files.second;
        const auto& path_label_to_fractiongroup = design_.getPathLabelToFractionGroupMapping(true);

        // for each MS file of current fraction (e.g., all MS files that measured the n-th fraction)
        for (String const & mz_file : ms_files.second)
        {
          const Size fraction_group = path_label_to_fractiongroup.at({File::basename(mz_file), 1});
          // load and clean identification data associated with MS run
          vector<ProteinIdentification> protein_ids;
          PeptideIdentificationList peptide_ids;
          const String& mz_file_abs_path = File::absolutePath(mz_file);
          const String& id_file_abs_path = File::absolutePath(mzfile2idfile.at(mz_file_abs_path));

          {
            ExitCodes e = loadAndCleanupIDFile_(id_file_abs_path, mz_file, in_db, fraction_group, fraction, protein_ids, peptide_ids, fixed_modifications, variable_modifications);
            if (e != EXECUTION_OK) return e;
          }

          StringList id_msfile_ref;
          protein_ids[0].getPrimaryMSRunPath(id_msfile_ref);
          id_MS_run_ref.push_back(id_msfile_ref[0]);

          // append the ProteinIdentification run (contains backlink to MS file) and the PeptideIdentifications (PSMs for this fraction and MS run) to the list of UnassignedPeptideIdentifications
          all_protein_ids.emplace_back(std::move(protein_ids[0]));
          all_peptide_ids.insert(all_peptide_ids.end(),
            std::make_move_iterator(peptide_ids.begin()),
            std::make_move_iterator(peptide_ids.end()));
        }

        ////////////////////////////////////////////////////////////
        // Annotate experimental design in consensus map
        ////////////////////////////////////////////////////////////
        // for each MS file (as provided in the experimental design)
        const auto& path_label_to_sampleidx = design_.getPathLabelToSampleMapping(true);
        for (String const & mz_file : ms_files.second)
        {
          const Size curr_fraction_group = path_label_to_fractiongroup.at({File::basename(mz_file), 1});
          consensus.getColumnHeaders()[run_index].label = "label-free";
          consensus.getColumnHeaders()[run_index].filename = mz_file;
          consensus.getColumnHeaders()[run_index].unique_id = 1 + run_index;
          consensus.getColumnHeaders()[run_index].setMetaValue("fraction", fraction);
          consensus.getColumnHeaders()[run_index].setMetaValue("fraction_group", curr_fraction_group);
          consensus.getColumnHeaders()[run_index].setMetaValue("sample_name", design_.getSampleSection().getSampleName(path_label_to_sampleidx.at({File::basename(mz_file),1})));
          ++run_index;
        }
      }
    }

    //-------------------------------------------------------------
    // ID related algorithms
    //-------------------------------------------------------------

    ExitCodes e = inferProteinGroups_(consensus, fixed_modifications);
    if (e != EXECUTION_OK) return e;

    // clean up references (assigned and unassigned)
    IDFilter::removeUnreferencedProteins(consensus, true);

    // only keep best scoring ID for each consensus feature
    IDConflictResolverAlgorithm::resolve(consensus);


    //-------------------------------------------------------------
    // Peptide quantification
    //-------------------------------------------------------------
    PeptideAndProteinQuant quantifier;

    // TODO Why is there no easy quantifier.run(consensus,[inference_prot_ids]) function??
    if (getStringOption_("quantification_method") == "feature_intensity")
    {
      quantifier.setParameters(pq_param);
      quantifier.readQuantData(consensus, design_);
    }
    else if (getStringOption_("quantification_method") == "spectral_counting")
    {
      pq_param.setValue("top:aggregate", "sum");
      pq_param.setValue("top:N", 0); // all
      pq_param.setValue("consensus:normalize", "false");
      quantifier.setParameters(pq_param);

      quantifier.readQuantData(
       consensus.getProteinIdentifications(),
       consensus.getUnassignedPeptideIdentifications(),
       design_);
    }

    // nothing to filter. everything in consensus should be uptodate with inference.
    // on peptide level it does not annotate anything anyway
    quantifier.quantifyPeptides();

    //-------------------------------------------------------------
    // Protein quantification
    //-------------------------------------------------------------

    // Should always be there by now, even if just singletons
    ProteinIdentification& inferred_proteins = consensus.getProteinIdentifications()[0];
    if (inferred_proteins.getIndistinguishableProteins().empty())
    {
      throw Exception::MissingInformation(
       __FILE__,
       __LINE__,
       OPENMS_PRETTY_FUNCTION,
       "No information on indistinguishable protein groups found.");
    }

    quantifier.quantifyProteins(inferred_proteins);
    auto const & protein_quants = quantifier.getProteinResults();
    if (protein_quants.empty())
    {
     OPENMS_LOG_WARN << "Warning: No proteins were quantified." << endl;
    }

    //-------------------------------------------------------------
    // Export of MzTab file as final output
    //-------------------------------------------------------------

    // Annotate quants to protein(groups) for easier export in mzTab
    // Note: we keep protein groups that have not been quantified
    quantifier.annotateQuantificationsToProteins(
      protein_quants, inferred_proteins, false);

    // For correctness, we would need to set the run reference in the pepIDs of the consensusXML all to the first run then
    // And probably make sure that peptides that correspond to filtered out proteins are not producing errors
    // e.g. by removing them with a Filter beforehand.

    consensus.resolveUniqueIdConflicts(); // TODO: find out if this is still needed

    {
      String out_qpx = getOutputDirOption("out_qpx");
      if (!out_qpx.empty())
      {
        OPENMS_LOG_INFO << "Exporting QPX Parquet files to: " << out_qpx << std::endl;

        // Feature-level export
        if (!ConsensusMapArrowExport::exportToParquet(consensus, out_qpx + "/quantms.feature.parquet"))
        {
          OPENMS_LOG_ERROR << "Failed to write features Parquet file" << std::endl;
          return CANNOT_WRITE_OUTPUT_FILE;
        }

        // PSM-level export: collect all peptide IDs from consensus map
        PeptideIdentificationList all_pepids;
        for (const auto& feature : consensus)
        {
          for (const auto& pepid : feature.getPeptideIdentifications())
          {
            all_pepids.push_back(pepid);
          }
        }
        for (const auto& pepid : consensus.getUnassignedPeptideIdentifications())
        {
          all_pepids.push_back(pepid);
        }

        if (!QPXFile::exportToParquet(consensus.getProteinIdentifications(), all_pepids, out_qpx + "/quantms.psm.parquet"))
        {
          OPENMS_LOG_ERROR << "Failed to write PSM Parquet file" << std::endl;
          return CANNOT_WRITE_OUTPUT_FILE;
        }

        // Protein group export
        if (!ProteinGroupArrowExport::exportToParquet(consensus, out_qpx + "/quantms.pg.parquet"))
        {
          OPENMS_LOG_ERROR << "Failed to write protein groups Parquet file" << std::endl;
          return CANNOT_WRITE_OUTPUT_FILE;
        }
      }
    }

    if (!getStringOption_("out_cxml").empty())
    {
      // Note: idXML and consensusXML doesn't support writing quantification at protein groups
      // (they are nevertheless stored and passed to mzTab for proper export)
      FileHandler().storeConsensusFeatures(getStringOption_("out_cxml"), consensus, {FileTypes::CONSENSUSXML}, log_type_);
    }

    // Fill MzTab with meta data and quants annotated in identification data structure
    const bool report_unidentified_features(false);
    const bool report_unmapped(true); //TODO we should make a distinction from unassigned after conflict resolution and unassigned because unmappable
    const bool report_subfeatures(false);
    const bool report_unidentified_spectra(false);
    const bool report_not_only_best_psm_per_spectrum(false);

    MzTabFile().store(out,
                      consensus,
                      false, // first run is inference but also a properly merged run, so we don't need the hack
                      report_unidentified_features,
                      report_unmapped,
                      report_subfeatures,
                      report_unidentified_spectra,
                      report_not_only_best_psm_per_spectrum);

    if (!out_msstats.empty())
    {
      IDFilter::removeEmptyIdentifications(consensus); // MzTab stream exporter currently doesn't support IDs with empty hits.

      MSstatsFile msstats;
      // TODO: add a helper method to quickly check if experimental design file contain the right columns
      //  (and put this at start of tool)

      // shrink protein runs to the one containing the inference data
      consensus.getProteinIdentifications().resize(1);

      msstats.storeLFQ(
        out_msstats,
        consensus,
        design_,
        StringList(),
        false, //lfq
        "MSstats_BioReplicate",
        "MSstats_Condition",
        "max");
    }


    if (!out_triqler.empty())
    {
      TriqlerFile tf;

      // shrink protein runs to the one containing the inference data
      consensus.getProteinIdentifications().resize(1);

      IDScoreSwitcherAlgorithm switcher;
      Size c = 0;
      switcher.switchToGeneralScoreType(consensus, IDScoreSwitcherAlgorithm::ScoreType::PEP, c);

      tf.storeLFQ(
        out_triqler,
        consensus,
        design_,
        StringList(),
        "MSstats_Condition" // TODO: choose something more generic like "Condition" for both MSstats and Triqler export
        );
    }

    return EXECUTION_OK;
  }
  String picked_decoy_string_;
  bool picked_decoy_prefix_ = true;
  ExperimentalDesign design_;
};

int main(int argc, const char ** argv)
{
  ProteomicsLFQ tool;
  return tool.main(argc, argv);
}

/// @endcond
