pipeline {
    agent any

    stages {
        stage('Build') {
            parallel {
                stage('Test On Windows') {
                    agent {
                        label "win10"
                    }
                    steps {
                        echo 'build'
                    }
                }
                stage('Test On Mac') {
                    agent {
                        label "highsierra"
                    }
                    steps {
                        echo 'build'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
