tasks:
    - init: >
        cp -r .vscode-gitpod .vscode && echo "Welcome!" 
        git config -f .gitmodules submodule.THIRDPARTY.shallow true && 
        git submodule update --init THIRDPARTY &&
        export PATH=$PATH$( find ${PWD}/THIRDPARTY/All -type d -printf ":%p" ) &&
        export PATH=$PATH$( find ${PWD}/THIRDPARTY/Linux/64bit -type d -printf ":%p" ) &&
        mkdir -p build && pushd build &&
        cmake -DCMAKE_BUILD_TYPE=Debug -DHAS_XSERVER=OFF -DENABLE_DOCS=OFF -DWITH_GUI=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_PREFIX_PATH='/contrib-build/;/usr/;/usr/local' -DBOOST_USE_STATIC=OFF ../ &&
        make -j7 OpenMS TOPP &&
        popd
      command:  >
        export PATH=$PATH$( find ${PWD}/THIRDPARTY/All -type d -printf ":%p" ) &&
        export PATH=$PATH$( find ${PWD}/THIRDPARTY/Linux/64bit -type d -printf ":%p" ) &&
        pushd build && make -j7 all && popd
image:
  file: .gitpod.Dockerfile
github:
#foo
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: false
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
# add a check to pull requests (defaults to true)
    addCheck: false
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
vscode:
  extensions:
    #Will never be available on OpenVSX
    #- ms-vscode.cpptools
    - https://github.com/microsoft/vscode-cpptools/releases/download/1.5.1/cpptools-linux.vsix
    - hbenl.vscode-test-explorer
    #Currently not available on OpenVSX
    #- fredericbonnet.cmake-test-adapter
    - llvm-vs-code-extensions.vscode-clangd
    - ms-vscode.cmake-tools
    - mhutchie.git-graph
    - cschlosser.doxdocgen
