[tool.cibuildwheel]
before-build = """
pip install -r OpenMS/src/pyOpenMS/requirements_bld.txt
ctest --output-on-failure -VV -S OpenMS/tools/ci/cibuild.cmake -C Release
"""
build-frontend = "pip"
test-command = "ctest --output-on-failure -V -S OpenMS/tools/ci/citest.cmake -C Release"

[tool.cibuildwheel.linux]
before-all = """
yum install -y jq ninja-build ccache
"""
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"


[tool.cibuildwheel.environment]
BUILD_TYPE = "Release"
PYOPENMS = "ON"
ENABLE_TUTORIALS = "OFF"
ENABLE_DOCS = "OFF"
ENABLE_PIPELINE_TESTING = "OFF"
ENABLE_STYLE_TESTING = "OFF"
ENABLE_TOPP_TESTING = "OFF"
ENABLE_CLASS_TESTING = "OFF"
CCACHE_COMPRESS = "true"
CCACHE_COMPRESSLEVEL = "12"
CCACHE_MAXSIZE = "400M"
CI_PROVIDER = "GitHub-Actions"
CMAKE_CCACHE_EXE = "ccache"