# Generated by CMake 2.6-patch 2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  SET("OpenMS_LIB_DEPENDS" "optimized;/home/andreas/DATA/OpenMS/contrib/lib/libCGAL.a;debug;/home/andreas/DATA/OpenMS/contrib/lib/libCGAL.a;optimized;/home/andreas/DATA/OpenMS/contrib/lib/libgsl.a;debug;/home/andreas/DATA/OpenMS/contrib/lib/libgsl.a;optimized;/home/andreas/DATA/OpenMS/contrib/lib/libgslcblas.a;debug;/home/andreas/DATA/OpenMS/contrib/lib/libgslcblas.a;general;/home/andreas/DATA/OpenMS/contrib//lib/svm.o;optimized;/home/andreas/DATA/OpenMS/contrib/lib/libxerces-c.a;debug;/home/andreas/DATA/OpenMS/contrib/lib/libxerces-c.a;")
ELSE("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.4 and lower.
  SET("OpenMS_LIB_DEPENDS" "/home/andreas/DATA/OpenMS/contrib/lib/libCGAL.a;/home/andreas/DATA/OpenMS/contrib/lib/libCGAL.a;/home/andreas/DATA/OpenMS/contrib/lib/libgsl.a;/home/andreas/DATA/OpenMS/contrib/lib/libgsl.a;/home/andreas/DATA/OpenMS/contrib/lib/libgslcblas.a;/home/andreas/DATA/OpenMS/contrib/lib/libgslcblas.a;/home/andreas/DATA/OpenMS/contrib//lib/svm.o;/home/andreas/DATA/OpenMS/contrib/lib/libxerces-c.a;/home/andreas/DATA/OpenMS/contrib/lib/libxerces-c.a;")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
