# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS OpenSwathAlgo Evergreen OpenMS OpenMS_GUI)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target OpenSwathAlgo
add_library(OpenSwathAlgo SHARED IMPORTED)

set_target_properties(OpenSwathAlgo PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20;cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "-fPIC;-mssse3"
  INTERFACE_INCLUDE_DIRECTORIES "/workspaces/OpenMS/src/openswathalgo/include;/workspaces/OpenMS/src/openswathalgo/include;/contrib-build/include"
)

# Create imported target Evergreen
add_library(Evergreen INTERFACE IMPORTED)

set_target_properties(Evergreen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspaces/OpenMS/src/openms/extern/evergreen/src"
)

# Create imported target OpenMS
add_library(OpenMS SHARED IMPORTED)

set_target_properties(OpenMS PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ENABLE_TDL"
  INTERFACE_COMPILE_FEATURES "cxx_std_20;cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "-fPIC;-mssse3"
  INTERFACE_INCLUDE_DIRECTORIES "/workspaces/OpenMS/src/openms/include;/workspaces/OpenMS/src/openms/include"
  INTERFACE_LINK_LIBRARIES "OpenSwathAlgo;Evergreen;LibSVM::LibSVM;XercesC::XercesC;Eigen3::Eigen;Qt6::Core;Qt6::Network;OpenMP::OpenMP_CXX"
)

# Create imported target OpenMS_GUI
add_library(OpenMS_GUI SHARED IMPORTED)

set_target_properties(OpenMS_GUI PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20;cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "-fPIC;-mssse3"
  INTERFACE_INCLUDE_DIRECTORIES "/workspaces/OpenMS/src/openms_gui/include;/workspaces/OpenMS/src/openms_gui/include;/workspaces/OpenMS/src/openms_gui/OpenMS_GUI_autogen/include"
  INTERFACE_LINK_LIBRARIES "OpenMS;Qt6::Gui;Qt6::Widgets;Qt6::Svg;Qt6::OpenGLWidgets"
)

# Import target "OpenSwathAlgo" for configuration "Debug"
set_property(TARGET OpenSwathAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OpenSwathAlgo PROPERTIES
  IMPORTED_LOCATION_DEBUG "/workspaces/OpenMS/lib/libOpenSwathAlgo.so"
  IMPORTED_SONAME_DEBUG "libOpenSwathAlgo.so"
  )

# Import target "OpenMS" for configuration "Debug"
set_property(TARGET OpenMS APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OpenMS PROPERTIES
  IMPORTED_LOCATION_DEBUG "/workspaces/OpenMS/lib/libOpenMS.so"
  IMPORTED_SONAME_DEBUG "libOpenMS.so"
  )

# Import target "OpenMS_GUI" for configuration "Debug"
set_property(TARGET OpenMS_GUI APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(OpenMS_GUI PROPERTIES
  IMPORTED_LOCATION_DEBUG "/workspaces/OpenMS/lib/libOpenMS_GUI.so"
  IMPORTED_SONAME_DEBUG "libOpenMS_GUI.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
