[workspace]
name = "openms"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]

[dependencies]
cmake = ">=3.26,<4.0"
ninja = ">=1.11,<2.0"
eigen = ">=3.4"
boost = ">=1.74"
xerces-c = ">=3.2,<4.0"
sqlite = ">=3.43,<4.0"
hdf5 = ">=1.14,<1.16"
coin-or-clp = ">=1.17,<2.0"
coin-or-cbc = ">=2.10,<3.0"
coin-or-cgl = ">=0.60,<1.0"
coin-or-osi = ">=0.108,<1.0"
ccache = ">=4.8,<6.0"
zlib = ">=1.2.13,<1.4"
bzip2 = ">=1.0.8,<2.0"
libsvm = ">=2.91"
libcurl = ">=8.5,<9.0"
libarrow = ">=15.0,<17.0"
libparquet = ">=15.0,<17.0"
nlohmann_json = ">=3.11,<4.0"
sqlitecpp = ">=3.0,<4.0"
simde = ">=0.7,<0.9"
libxml2 = ">=2.11,<3.0"
doxygen = ">=1.9.8,<1.15"
ghostscript = ">=10.2,<11.0"
graphviz = ">=9.0,<10.0"

[target.linux-64.dependencies]
coinmp = ">=1.8,<2.0"
libtool = ">=2.4,<3.0"
autoconf = ">=2.71,<3.0"
patch = ">=2.7,<3.0"
mesalib = ">=24.0,<26.0"
qt6-main = ">=6.1"
lapack = ">=3.11,<4.0"
blas = ">=2.116,<3.0"

[target.linux-aarch64.dependencies]
coinmp = ">=1.8,<2.0"
libtool = ">=2.4,<3.0"
autoconf = ">=2.71,<3.0"
patch = ">=2.7,<3.0"
mesalib = ">=24.0,<26.0"
qt6-main = ">=6.1"
lapack = ">=3.11,<4.0"
blas = ">=2.116,<3.0"

[target.osx-arm64.dependencies]
libtool = ">=2.4,<3.0"
autoconf = ">=2.71,<3.0"
patch = ">=2.7,<3.0"
qt6-main = ">=6.1"
lapack = ">=3.11,<4.0"
blas = ">=2.116,<3.0"

[target.win-64.dependencies]
qt6-main = ">=6.1"
mkl = ">=2024.0,<2026"
mkl-devel = ">=2024.0,<2026"
intel-openmp = ">=2024.0,<2026"