[workspace]
name = "openms"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]

[dependencies]
cmake = "3.28.*"
ninja = "*"
eigen = "*"
boost = "*"
xerces-c = "*"
sqlite = "*"
hdf5 = "*"
coin-or-clp = "*"
coin-or-cbc = "*"
coin-or-cgl = "*"
coin-or-osi = "*"
ccache = "*"
zlib = "*"
bzip2 = "*"
libsvm = "*"
libcurl = "*"
libarrow = "*"
libparquet = "*"
nlohmann_json = "*"
sqlitecpp = "*"
simde = "*"
libxml2 = "*"
doxygen = "*"
ghostscript = "*"
graphviz = "*"
lapack = "*"
blas = "*"

[target.linux-64.dependencies]
coinmp = "*"
libtool = "*"
autoconf = "*"
patch = "*"
mesalib = "*"
qt6-main = "*"

[target.linux-aarch64.dependencies]
coinmp = "*"
libtool = "*"
autoconf = "*"
patch = "*"
mesalib = "*"
qt6-main = "*"

[target.osx-64.dependencies]  
cmake = ">=3.26,<4.0"
qt6-main = "*"


[target.osx-arm64.dependencies]
cmake = ">=3.26,<4.0"
libtool = "*"
autoconf = "*"
patch = "*"

qt6-main = "*"

[target.win-64.dependencies]
lapack = "*"
blas = "*"
qt6-main = "*"