[workspace]
name = "openms"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]

[dependencies]
cmake = "*"
ninja = "*"
eigen = "*"
boost = "*"
xerces-c = "*"
sqlite = "*"
hdf5 = "*"
coin-or-clp = "*"
coin-or-cbc = "*"
coin-or-cgl = "*"
coin-or-osi = "*"
ccache = "*"
zlib = "*"
bzip2 = "*"
libsvm = "*"
libcurl = "*"
nlohmann_json = "*"
sqlitecpp = "*"
simde = "*"
libparquet = "*"
doxygen = "*"
ghostscript = "*"
graphviz = "*"
qt6-main = "*"
coinmp = "*"
mesalib = "*"
libtool = "*"
autoconf = "*"
patch = "*"
libxml2 = "*"
arrow-dataset = "*"
