[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy>=1.25.0",
    "pandas",
    "matplotlib>=3.5",
    "Cython",
    "setuptools_scm",
    ]
build-backend = "setuptools.build_meta"

[project]
name = "pyopenms"
description = "Python wrapper for C++ LC-MS library OpenMS"
readme = "README.rst"
authors = [
    { name = "OpenMS team", email = "webmaster@openms.de" }
]
maintainers = [
    { name = "The OpenMS team", email = "open-ms-general@lists.sourceforge.net" }
]
license = { text = "BSD-3-Clause" }
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.25.0",
    "pandas",
    "matplotlib>=3.5"
]
keywords = ["bioinformatics", "mass spectrometry", "chemistry"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Chemistry"
]

[project.urls]
Homepage = "https://openms.de"
Documentation = "https://pyopenms.readthedocs.io"
Source = "https://github.com/OpenMS/OpenMS/tree/develop/src/pyOpenMS"
Tracker = "https://github.com/OpenMS/OpenMS/issues"
"Documentation Source" = "https://github.com/OpenMS/pyopenms-docs"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
pyopenms = ["py.typed", "*.pyi"]


[tool.setuptools_scm]
fallback_version = "3.x.x-dev"