# -*- mode: makefile; tab-width: 2; -*-
# vi: set ts=2:
#
# --------------------------------------------------------------------------
#                   OpenMS Mass Spectrometry Framework
# --------------------------------------------------------------------------
#  Copyright (C) 2003-2008 -- Oliver Kohlbacher, Knut Reinert
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# --------------------------------------------------------------------------
# $Maintainer: Andreas Bertsch $
# --------------------------------------------------------------------------

include ../../config_defs.mak

DIRECTORY=FILTERING/TRANSFORMERS

CPP_SOURCES = \
  GoodDiffFilter.C\
  NLargest.C\
  Scaler.C\
  ThresholdMower.C\
  ComplementFilter.C\
  IntensityBalanceFilter.C\
  MarkerMower.C\
  NeutralLossDiffFilter.C\
  ParentPeakMower.C\
  SqrtMower.C\
  WindowMower.C\
  FilterFunctor.C\
  IsotopeDiffFilter.C\
  PreprocessingFunctor.C\
  Normalizer.C\
  PeakDensityFilter.C\
  TICFilter.C\
  ComplementMarker.C\
  IsotopeMarker.C\
  NeutralLossMarker.C\
  PeakMarker.C\
  LinearResampler.C\
	ParentFilter.C\
	BernNorm.C


include ../../common.mak
-include .Dependencies

