#!/bin/bash
# bash script which sets the correct paths and executes TOPPAS

export OPENMS_TOPP_PATH=`dirname $0`

## setting of the OpenMS data path to the share directory
export OPENMS_DATA_PATH=${OPENMS_TOPP_PATH}/../../../share/OpenMS

## we need to set the path variable accordingly
export PATH=${OPENMS_TOPP_PATH}/../../../TOPP:$PATH
## also the search engines (if existent)
export PATH=${OPENMS_TOPP_PATH}/../../../TOPP/SEARCHENGINES/XTandem:$PATH
export PATH=${OPENMS_TOPP_PATH}/../../../TOPP/SEARCHENGINES/OMSSA:$PATH

## start TOPPAS
cd ${OPENMS_TOPP_PATH}/../../../TOPP/
TOPPAS $@


