# -*- coding: utf-8 -*-
"""
pyOpenMS setup script for wheel packaging.

This setup.py is designed to work with the CMake-based build system.
CMake handles all C++ compilation via Python_add_library, and this script
is only used for packaging the pre-built extensions into a wheel.

The typical build flow is:
1. CMake configures the build and generates env.py from env.py.in
2. CMake compiles OpenMS and the pyopenms C++ extensions
3. This setup.py packages everything into a wheel

When called via `pip wheel --no-binary=pyopenms --no-build-isolation .`,
pip will NOT try to build from source - it just packages existing files.
"""

import os
import sys

from setuptools import setup, Distribution
from setuptools.command.bdist_wheel import bdist_wheel


class BinaryDistribution(Distribution):
    """Distribution that forces platform-specific wheel."""

    def has_ext_modules(self):
        return True


class bdist_wheel_platform(bdist_wheel):
    """Custom bdist_wheel that creates platform-specific wheels.

    This is necessary because CMake pre-compiles the extension modules,
    so setuptools doesn't know about them. We need to force the wheel
    to be platform-specific (not py3-none-any).
    """

    def finalize_options(self):
        bdist_wheel.finalize_options(self)
        # Mark as not pure Python (has compiled extensions)
        self.root_is_pure = False

    def get_tag(self):
        python, abi, plat = bdist_wheel.get_tag(self)
        # Use the platform-specific tags
        return python, abi, plat


# Import version information from env.py (generated by CMake)
# This determines if we're building a nightly or release version
try:
    from env import OPEN_MS_GIT_BRANCH, OPEN_MS_VERSION, OPENMS_GIT_LC_DATE_FORMAT

    if OPEN_MS_GIT_BRANCH == "nightly":
        package_version = OPEN_MS_VERSION + ".dev" + OPENMS_GIT_LC_DATE_FORMAT
    else:
        package_version = OPEN_MS_VERSION
except ImportError as e:
    # Fallback for when env.py doesn't exist (e.g., during sdist)
    package_version = "0.0.0.dev0"
    print(f"Warning: Could not import from env.py: {e}", file=sys.stderr)
    print(f"  Current directory: {os.getcwd()}", file=sys.stderr)
    print(f"  env.py exists: {os.path.exists('env.py')}", file=sys.stderr)
    print("  Using placeholder version 0.0.0.dev0", file=sys.stderr)

# Write version file for runtime access
version_file = os.path.join(os.path.dirname(__file__), "pyopenms", "version.py")
os.makedirs(os.path.dirname(version_file), exist_ok=True)
with open(version_file, "w") as fp:
    fp.write(f"version = {package_version!r}\n")

# The actual setup call - most metadata is in pyproject.toml
# We only need to specify the dynamic version and wheel customization here
setup(
    version=package_version,
    distclass=BinaryDistribution,
    cmdclass={
        "bdist_wheel": bdist_wheel_platform,
    },
)
