#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
pyOpenMS setup script for wheel packaging.

This setup.py is designed to work with the CMake-based build system.
CMake handles all C++ compilation via Python_add_library, and this script
is only used for packaging the pre-built extensions into a wheel.

The typical build flow is:
1. CMake configures the build and generates env.py from env.py.in
2. CMake compiles OpenMS and the pyopenms C++ extensions
3. This setup.py packages everything into a wheel

When called via `pip wheel --no-binary=pyopenms --no-build-isolation .`,
pip will NOT try to build from source - it just packages existing files.
"""

import os
import sys

from setuptools import setup

# Import version information from env.py (generated by CMake)
# This determines if we're building a nightly or release version
try:
    from env import OPEN_MS_GIT_BRANCH, OPEN_MS_VERSION, OPENMS_GIT_LC_DATE_FORMAT

    if OPEN_MS_GIT_BRANCH == "nightly":
        package_version = OPEN_MS_VERSION + ".dev" + OPENMS_GIT_LC_DATE_FORMAT
    else:
        package_version = OPEN_MS_VERSION
except ImportError:
    # Fallback for when env.py doesn't exist (e.g., during sdist)
    package_version = "0.0.0.dev0"
    print("Warning: env.py not found. Using placeholder version.", file=sys.stderr)

# Write version file for runtime access
version_file = os.path.join(os.path.dirname(__file__), "pyopenms", "version.py")
os.makedirs(os.path.dirname(version_file), exist_ok=True)
with open(version_file, "w") as fp:
    fp.write(f"version = {package_version!r}\n")

# The actual setup call - most metadata is in pyproject.toml
# We only need to specify the dynamic version here
setup(
    version=package_version,
)
