#Generated with autowrap 0.23.0 and Cython (Parser) 3.1.2
#cython: c_string_encoding=ascii
#cython: embedsignature=False
from  enum            import Enum as _PyEnum
from  cpython         cimport Py_buffer
from  cpython         cimport bool as pybool_t
from  libcpp.string   cimport string as libcpp_string
from  libcpp.string   cimport string as libcpp_utf8_string
from  libcpp.string   cimport string as libcpp_utf8_output_string
from  libcpp.set      cimport set as libcpp_set
from  libcpp.vector   cimport vector as libcpp_vector
from  libcpp.pair     cimport pair as libcpp_pair
from  libcpp.map      cimport map  as libcpp_map
from  libcpp          cimport bool
from  libc.string     cimport const_char
from  cython.operator cimport dereference as deref, preincrement as inc, address as address
from  AutowrapRefHolder      cimport AutowrapRefHolder
from  AutowrapPtrHolder      cimport AutowrapPtrHolder
from  AutowrapConstPtrHolder cimport AutowrapConstPtrHolder
from  smart_ptr       cimport shared_ptr
cimport numpy as np
import numpy as np
cimport numpy as numpy
import numpy as numpy
from ._pyopenms_1 cimport convString
from ._pyopenms_1 cimport convOutputString
from InterfaceDataStructures cimport BinaryDataArrayPtr
from InterfaceDataStructures cimport ChromatogramPtr
from ConsensusMap cimport ColumnHeaders
from ConsensusMap cimport ColumnHeaders_iterator
from ChromatogramPeak cimport CoordinateType
from DataProcessing cimport DataProcessingPtr
from Types cimport Int
from Types cimport Int32
from Types cimport Int64
from ChromatogramPeak cimport IntensityType
from MasstraceCorrelator cimport MasstracePointsType
from OpenSwathDataStructures cimport OSBinaryDataArrayPtr
from OpenSwathDataStructures cimport OSChromatogramPtr
from OpenSwathDataStructures cimport OSSpectrumPtr
from ChromatogramPeak cimport PositionType
from NASequence cimport RibonucleotideChainEnd
from Types cimport SignedSize
from Types cimport Size
from InterfaceDataStructures cimport SpectrumPtr
from Types cimport Time
from Types cimport UID
from Types cimport UInt
from Types cimport UInt32
from Types cimport UInt64
from IMSIsotopeDistribution cimport abundance_type
from IMSIsotopeDistribution cimport abundances_container
from Weights cimport alphabet_mass_type
from IMSAlphabet cimport container
from IMSAlphabet cimport element_type
from IMSElement cimport isotopes_type
from IMSIsotopeDistribution cimport mass_type
from IMSIsotopeDistribution cimport masses_container
from IMSAlphabet cimport masses_type
from IMSElement cimport name_type
from IMSIsotopeDistribution cimport nominal_mass_type
from IMSIsotopeDistribution cimport peak_type
from IMSIsotopeDistribution cimport peaks_container
from IMSIsotopeDistribution cimport size_type
from Weights cimport weight_type
from Weights cimport weights_type
from IonDetector cimport AcquisitionMode as _AcquisitionMode
from XMLHandler cimport ActionMode as _ActionMode
from Precursor cimport ActivationMethod as _ActivationMethod
from BasicProteinInferenceAlgorithm cimport AggregationMethod as _AggregationMethod
from MassAnalyzer cimport AnalyzerType as _AnalyzerType
from BaseFeature cimport AnnotationState as _AnnotationState
from IsotopeModel cimport Averagines as _Averagines
from BSpline2d cimport BoundaryCondition as _BoundaryCondition
from Base64 cimport ByteOrder as _ByteOrder
from FeatureDeconvolution cimport CHARGEMODE_FD as _CHARGEMODE_FD
from MetaboliteFeatureDeconvolution cimport CHARGEMODE_MFD as _CHARGEMODE_MFD
from SourceFile cimport ChecksumType as _ChecksumType
from ChromatogramSettings cimport ChromatogramType as _ChromatogramType
from CVMappingRule cimport CombinationsLogic as _CombinationsLogic
from DRange cimport DRangeIntersection as _DRangeIntersection
from DataValue cimport DataType as _DataType
from ReactionMonitoringTransition cimport DecoyTransitionType as _DecoyTransitionType
from IsotopeLabelingMDVs cimport DerivatizationAgent as _DerivatizationAgent
from Peak2D cimport DimensionDescription as _DimensionDescription
from IMTypes cimport DriftTimeUnit as _DriftTimeUnit
from XTandemInfile cimport ErrorUnit as _ErrorUnit
from FileTypes cimport FileType as _FileType
from DataFilters cimport FilterOperation as _FilterOperation
from DataFilters cimport FilterType as _FilterType
from IMTypes cimport IMFormat as _IMFormat
from ItraqConstants cimport ITRAQ_TYPES as _ITRAQ_TYPES
from IonSource cimport InletType as _InletType
from SignalToNoiseEstimatorMeanIterative cimport IntensityThresholdCalculation as _IntensityThresholdCalculation
from SignalToNoiseEstimatorMedian cimport IntensityThresholdCalculation as _IntensityThresholdCalculation
from Instrument cimport IonOpticsType as _IonOpticsType
from IonSource cimport IonizationMethod as _IonizationMethod
from LPWrapper cimport LPWrapper_Type as _LPWrapper_Type
from ProgressLogger cimport LogType as _LogType
from MassTrace cimport MT_QUANTMETHOD as _MT_QUANTMETHOD
from MZTrafoModel cimport MZTrafoModel_MODELTYPE as _MZTrafoModel_MODELTYPE
from IsotopeLabelingMDVs cimport MassIntensityType as _MassIntensityType
from XTandemInfile cimport MassType as _MassType
from IDMapper cimport Measure as _Measure
from NASequence cimport NASFragmentType as _NASFragmentType
from ConsensusMapNormalizerAlgorithmMedian cimport NormalizationMethod as _NormalizationMethod
from MSNumpressCoder cimport NumpressCompression as _NumpressCompression
from OpenPepXLAlgorithm cimport OpenPepXLAlgorithm_ExitCodes as _OpenPepXLAlgorithm_ExitCodes
from OpenPepXLLFAlgorithm cimport OpenPepXLLFAlgorithm_ExitCodes as _OpenPepXLLFAlgorithm_ExitCodes
from IDRipper cimport OriginAnnotationFormat as _OriginAnnotationFormat
from ProteinIdentification cimport PeakMassType as _PeakMassType
from PeptideIndexing cimport PeptideIndexing_ExitCodes as _PeptideIndexing_ExitCodes
from OPXLDataStructs cimport PeptidePosition as _PeptidePosition
from PercolatorOutfile cimport PercolatorOutfile_ScoreType as _PercolatorOutfile_ScoreType
from IonSource cimport Polarity as _Polarity
from DataProcessing cimport ProcessingAction as _ProcessingAction
from OPXLDataStructs cimport ProteinProteinCrossLinkType as _ProteinProteinCrossLinkType
from String cimport QuotingMethod as _QuotingMethod
from NonNegativeLeastSquaresSolver cimport RETURN_STATUS as _RETURN_STATUS
from TargetedExperimentHelper cimport RTType as _RTType
from TargetedExperimentHelper cimport RTUnit as _RTUnit
from MassAnalyzer cimport ReflectronState as _ReflectronState
from CVMappingRule cimport RequirementLevel as _RequirementLevel
from Residue cimport ResidueType as _ResidueType
from MassAnalyzer cimport ResolutionMethod as _ResolutionMethod
from MassAnalyzer cimport ResolutionType as _ResolutionType
from Compomer cimport SIDE as _SIDE
from LPWrapper cimport SOLVER as _SOLVER
from Sample cimport SampleState as _SampleState
from MassAnalyzer cimport ScanDirection as _ScanDirection
from MassAnalyzer cimport ScanLaw as _ScanLaw
from InstrumentSettings cimport ScanMode as _ScanMode
from LPWrapper cimport Sense as _Sense
from LPWrapper cimport SolverStatus as _SolverStatus
from IsotopeDistribution cimport Sorted as _Sorted
from ResidueModification cimport SourceClassification as _SourceClassification
from EnzymaticDigestion cimport Specificity as _Specificity
from SpectrumSettings cimport SpectrumType as _SpectrumType
from ResidueModification cimport TermSpecificity as _TermSpecificity
from Ribonucleotide cimport TermSpecificityNuc as _TermSpecificityNuc
from ReactionMonitoringTransition cimport TransType as _TransType
from IonDetector cimport Type_IonDetector as _Type_IonDetector
from DataValue cimport UnitType as _UnitType
from ParamValue cimport ValueType as _ValueType
from LPWrapper cimport VariableType as _VariableType
from LPWrapper cimport WriteFormat as _WriteFormat
from XFDRAlgorithm cimport XFDRAlgorithm_ExitCodes as _XFDRAlgorithm_ExitCodes
from ControlledVocabulary cimport XRefType_CVTerm_ControlledVocabulary as _XRefType_CVTerm_ControlledVocabulary
from File cimport absolutePath as _absolutePath_File
from SpectrumMetaDataLookup cimport addMissingIMToPeptideIDs as _addMissingIMToPeptideIDs_SpectrumMetaDataLookup
from SpectrumMetaDataLookup cimport addMissingRTsToPeptideIDs as _addMissingRTsToPeptideIDs_SpectrumMetaDataLookup
from SpectrumMetaDataLookup cimport addMissingSpectrumReferences as _addMissingSpectrumReferences_SpectrumMetaDataLookup
from IonIdentityMolecularNetworking cimport annotateConsensusMap as _annotateConsensusMap_IonIdentityMolecularNetworking
from InternalCalibration cimport applyTransformation as _applyTransformation_InternalCalibration
from InternalCalibration cimport applyTransformation as _applyTransformation_InternalCalibration
from InternalCalibration cimport applyTransformation as _applyTransformation_InternalCalibration
from FeatureMapping cimport assignMS2IndexToFeature as _assignMS2IndexToFeature_FeatureMapping
from File cimport basename as _basename_File
from MRMRTNormalizer cimport chauvenet as _chauvenet_MRMRTNormalizer
from MRMRTNormalizer cimport chauvenet_probability as _chauvenet_probability_MRMRTNormalizer
from MRMRTNormalizer cimport computeBinnedCoverage as _computeBinnedCoverage_MRMRTNormalizer
from FileHandler cimport computeFileHash as _computeFileHash_FileHandler
from MetaboliteSpectralMatching cimport computeHyperScore as _computeHyperScore_MetaboliteSpectralMatching
from PrecursorCorrection cimport correctToHighestIntensityMS1Peak as _correctToHighestIntensityMS1Peak_PrecursorCorrection
from PrecursorCorrection cimport correctToNearestFeature as _correctToNearestFeature_PrecursorCorrection
from PrecursorCorrection cimport correctToNearestMS1Peak as _correctToNearestMS1Peak_PrecursorCorrection
from VersionInfo cimport create as _create_VersionInfo
from Deisotoper cimport deisotopeAndSingleCharge as _deisotopeAndSingleCharge_Deisotoper
from Deisotoper cimport deisotopeAndSingleCharge as _deisotopeAndSingleCharge_Deisotoper
from Deisotoper cimport deisotopeWithAveragineModel as _deisotopeWithAveragineModel_Deisotoper
from File cimport empty as _empty_File
from MZTrafoModel cimport enumToName as _enumToName_MZTrafoModel
from File cimport exists as _exists_File
from File cimport fileList as _fileList_File
from File cimport find as _find_File
from File cimport findDatabase as _findDatabase_File
from File cimport findDoc as _findDoc_File
from File cimport findExecutable as _findExecutable_File
from MZTrafoModel cimport findNearest as _findNearest_MZTrafoModel
from ExperimentalDesign cimport fromConsensusMap as _fromConsensusMap_ExperimentalDesign
from ExperimentalDesign cimport fromFeatureMap as _fromFeatureMap_ExperimentalDesign
from ExperimentalDesign cimport fromIdentifications as _fromIdentifications_ExperimentalDesign
from AASequence cimport fromString as _fromString_AASequence
from NASequence cimport fromString as _fromString_NASequence
from AASequence cimport fromString as _fromString_AASequence
from BuildInfo cimport getBinaryArchitecture as _getBinaryArchitecture_BuildInfo
from VersionInfo cimport getBranch as _getBranch_VersionInfo
from BuildInfo cimport getBuildType as _getBuildType_BuildInfo
from TransformationModelLowess cimport getDefaultParameters as _getDefaultParameters_TransformationModelLowess
from TransformationModelBSpline cimport getDefaultParameters as _getDefaultParameters_TransformationModelBSpline
from TransformationModelLinear cimport getDefaultParameters as _getDefaultParameters_TransformationModelLinear
from File cimport getExecutablePath as _getExecutablePath_File
from RNaseDB cimport getInstance as _getInstance_RNaseDB
from ProteaseDB cimport getInstance as _getInstance_ProteaseDB
from ResidueDB cimport getInstance as _getInstance_ResidueDB
from ModificationsDB cimport getInstance as _getInstance_ModificationsDB
from ModificationsDB cimport getInstance as _getInstance_ModificationsDB
from CrossLinksDB cimport getInstance as _getInstance_CrossLinksDB
from RibonucleotideDB cimport getInstance as _getInstance_RibonucleotideDB
from LogConfigHandler cimport getInstance as _getInstance_LogConfigHandler
from ElementDB cimport getInstance as _getInstance_ElementDB
from CalibrationData cimport getMetaValues as _getMetaValues_CalibrationData
from TransformationDescription cimport getModelTypes as _getModelTypes_TransformationDescription
from BuildInfo cimport getOSInfo as _getOSInfo_BuildInfo
from BuildInfo cimport getOpenMPMaxNumThreads as _getOpenMPMaxNumThreads_BuildInfo
from File cimport getOpenMSDataPath as _getOpenMSDataPath_File
from File cimport getOpenMSHomePath as _getOpenMSHomePath_File
from PrecursorCorrection cimport getPrecursors as _getPrecursors_PrecursorCorrection
from VersionInfo cimport getRevision as _getRevision_VersionInfo
from SpectrumMetaDataLookup cimport getSpectrumMetaData as _getSpectrumMetaData_SpectrumMetaDataLookup
from File cimport getSystemParameters as _getSystemParameters_File
from File cimport getTempDirectory as _getTempDirectory_File
from File cimport getTemporaryFile as _getTemporaryFile_File
from VersionInfo cimport getTime as _getTime_VersionInfo
from FileHandler cimport getType as _getType_FileHandler
from FileHandler cimport getTypeByContent as _getTypeByContent_FileHandler
from FileHandler cimport getTypeByFileName as _getTypeByFileName_FileHandler
from File cimport getUniqueName as _getUniqueName_File
from File cimport getUserDirectory as _getUserDirectory_File
from VersionInfo cimport getVersion as _getVersion_VersionInfo
from VersionInfo cimport getVersionStruct as _getVersionStruct_VersionInfo
from FileHandler cimport hasValidExtension as _hasValidExtension_FileHandler
from File cimport isDirectory as _isDirectory_File
from BuildInfo cimport isOpenMPEnabled as _isOpenMPEnabled_BuildInfo
from FileHandler cimport isSupported as _isSupported_FileHandler
from MZTrafoModel cimport isValidModel as _isValidModel_MZTrafoModel
from ExperimentalDesignFile cimport load as _load_ExperimentalDesignFile
from CachedmzML cimport load as _load_CachedmzML
from MZTrafoModel cimport nameToEnum as _nameToEnum_MZTrafoModel
from DateTime cimport now as _now_DateTime
from File cimport path as _path_File
from ChromatogramExtractor cimport prepare_coordinates as _prepare_coordinates_ChromatogramExtractor
from File cimport readable as _readable_File
from File cimport remove as _remove_File
from File cimport removeDirRecursively as _removeDirRecursively_File
from MRMRTNormalizer cimport removeOutliersIterative as _removeOutliersIterative_MRMRTNormalizer
from MRMRTNormalizer cimport removeOutliersRANSAC as _removeOutliersRANSAC_MRMRTNormalizer
from SpectrumHelper cimport removePeaks as _removePeaks_SpectrumHelper
from SpectrumHelper cimport removePeaks as _removePeaks_SpectrumHelper
from File cimport rename as _rename_File
from PeptideProteinResolution cimport run as _run_PeptideProteinResolution
from MZTrafoModel cimport setCoefficientLimits as _setCoefficientLimits_MZTrafoModel
from BuildInfo cimport setOpenMPNumThreads as _setOpenMPNumThreads_BuildInfo
from MZTrafoModel cimport setRANSACParams as _setRANSACParams_MZTrafoModel
from UniqueIdInterface cimport setUniqueId as _setUniqueId_UniqueIdInterface
from PercolatorInfile cimport store as _store_PercolatorInfile
from CachedmzML cimport store as _store_CachedmzML
from FileHandler cimport stripExtension as _stripExtension_FileHandler
from SpectrumHelper cimport subtractMinimumIntensity as _subtractMinimumIntensity_SpectrumHelper
from SpectrumHelper cimport subtractMinimumIntensity as _subtractMinimumIntensity_SpectrumHelper
from FileHandler cimport swapExtension as _swapExtension_FileHandler
from IMTypes cimport toDriftTimeUnit as _toDriftTimeUnit_IMTypes
from IMTypes cimport toIMFormat as _toIMFormat_IMTypes
from IMTypes cimport toString as _toString_IMTypes
from IMTypes cimport toString as _toString_IMTypes
from File cimport writable as _writable_File
from PrecursorCorrection cimport writeHist as _writeHist_PrecursorCorrection
from IonIdentityMolecularNetworking cimport writeSupplementaryPairTable as _writeSupplementaryPairTable_IonIdentityMolecularNetworking
from AAIndex cimport AAIndex as _AAIndex
from AASeqWithMass cimport AASeqWithMass as _AASeqWithMass
from AASequence cimport AASequence as _AASequence
from AdductInfo cimport AMSE_AdductInfo as _AMSE_AdductInfo
from AbsoluteQuantitationStandards cimport AQS_featureConcentration as _AQS_featureConcentration
from AbsoluteQuantitationStandards cimport AQS_runConcentration as _AQS_runConcentration
from AScore cimport AScore as _AScore
from AbsoluteQuantitation cimport AbsoluteQuantitation as _AbsoluteQuantitation
from AbsoluteQuantitationMethod cimport AbsoluteQuantitationMethod as _AbsoluteQuantitationMethod
from AbsoluteQuantitationMethodFile cimport AbsoluteQuantitationMethodFile as _AbsoluteQuantitationMethodFile
from AbsoluteQuantitationStandards cimport AbsoluteQuantitationStandards as _AbsoluteQuantitationStandards
from AbsoluteQuantitationStandardsFile cimport AbsoluteQuantitationStandardsFile as _AbsoluteQuantitationStandardsFile
from AccurateMassSearchEngine cimport AccurateMassSearchEngine as _AccurateMassSearchEngine
from AccurateMassSearchResult cimport AccurateMassSearchResult as _AccurateMassSearchResult
from Acquisition cimport Acquisition as _Acquisition
from AcquisitionInfo cimport AcquisitionInfo as _AcquisitionInfo
from Adduct cimport Adduct as _Adduct
from AnnotatedMSRun cimport AnnotatedMSRun as _AnnotatedMSRun
from AnnotationStatistics cimport AnnotationStatistics as _AnnotationStatistics
from Attachment cimport Attachment as _Attachment
from AverageLinkage cimport AverageLinkage as _AverageLinkage
from BSpline2d cimport BSpline2d as _BSpline2d
from Base64 cimport Base64 as _Base64
from BaseFeature cimport BaseFeature as _BaseFeature
from BaseGroupFinder cimport BaseGroupFinder as _BaseGroupFinder
from BasicProteinInferenceAlgorithm cimport BasicProteinInferenceAlgorithm as _BasicProteinInferenceAlgorithm
from BayesianProteinInferenceAlgorithm cimport BayesianProteinInferenceAlgorithm as _BayesianProteinInferenceAlgorithm
from BiGaussFitter1D cimport BiGaussFitter1D as _BiGaussFitter1D
from BiGaussModel cimport BiGaussModel as _BiGaussModel
from BilinearInterpolation cimport BilinearInterpolation as _BilinearInterpolation
from BinnedSpectrum cimport BinnedSpectrum as _BinnedSpectrum
from TargetedExperimentHelper cimport CV as _CV
from CVMappingFile cimport CVMappingFile as _CVMappingFile
from CVMappingRule cimport CVMappingRule as _CVMappingRule
from CVMappingTerm cimport CVMappingTerm as _CVMappingTerm
from CVMappings cimport CVMappings as _CVMappings
from CVReference cimport CVReference as _CVReference
from CVTerm cimport CVTerm as _CVTerm
from CVTermList cimport CVTermList as _CVTermList
from CVTermListInterface cimport CVTermListInterface as _CVTermListInterface
from ControlledVocabulary cimport CVTerm_ControlledVocabulary as _CVTerm_ControlledVocabulary
from CachedmzMLHandler cimport CachedMzMLHandler as _CachedMzMLHandler
from SwathFileConsumer cimport CachedSwathFileConsumer as _CachedSwathFileConsumer
from CachedmzML cimport CachedmzML as _CachedmzML
from CalibrationData cimport CalibrationData as _CalibrationData
from ItraqConstants cimport ChannelInfo as _ChannelInfo
from ChargePair cimport ChargePair as _ChargePair
from IsotopeCluster cimport ChargedIndexSet as _ChargedIndexSet
from ChromatogramExtractor cimport ChromatogramExtractor as _ChromatogramExtractor
from ChromatogramExtractorAlgorithm cimport ChromatogramExtractorAlgorithm as _ChromatogramExtractorAlgorithm
from ChromatogramPeak cimport ChromatogramPeak as _ChromatogramPeak
from ChromatogramRangeManager cimport ChromatogramRangeManager as _ChromatogramRangeManager
from ChromatogramSettings cimport ChromatogramSettings as _ChromatogramSettings
from ChromatogramTools cimport ChromatogramTools as _ChromatogramTools
from ChromeleonFile cimport ChromeleonFile as _ChromeleonFile
from ClusterProxyKD cimport ClusterProxyKD as _ClusterProxyKD
from ClusteringGrid cimport ClusteringGrid as _ClusteringGrid
from IsotopeDistribution cimport CoarseIsotopePatternGenerator as _CoarseIsotopePatternGenerator
from ConsensusMap cimport ColumnHeader as _ColumnHeader
from Compomer cimport Compomer as _Compomer
from TargetedExperimentHelper cimport Compound as _Compound
from ConfidenceScoring cimport ConfidenceScoring as _ConfidenceScoring
from TargetedExperimentHelper cimport Configuration as _Configuration
from ConsensusFeature cimport ConsensusFeature as _ConsensusFeature
from ConsensusIDAlgorithm cimport ConsensusIDAlgorithm as _ConsensusIDAlgorithm
from ConsensusIDAlgorithmAverage cimport ConsensusIDAlgorithmAverage as _ConsensusIDAlgorithmAverage
from ConsensusIDAlgorithmBest cimport ConsensusIDAlgorithmBest as _ConsensusIDAlgorithmBest
from ConsensusIDAlgorithmIdentity cimport ConsensusIDAlgorithmIdentity as _ConsensusIDAlgorithmIdentity
from ConsensusIDAlgorithmPEPIons cimport ConsensusIDAlgorithmPEPIons as _ConsensusIDAlgorithmPEPIons
from ConsensusIDAlgorithmPEPMatrix cimport ConsensusIDAlgorithmPEPMatrix as _ConsensusIDAlgorithmPEPMatrix
from ConsensusIDAlgorithmRanks cimport ConsensusIDAlgorithmRanks as _ConsensusIDAlgorithmRanks
from ConsensusIDAlgorithmSimilarity cimport ConsensusIDAlgorithmSimilarity as _ConsensusIDAlgorithmSimilarity
from ConsensusIDAlgorithmWorst cimport ConsensusIDAlgorithmWorst as _ConsensusIDAlgorithmWorst
from ConsensusMap cimport ConsensusMap as _ConsensusMap
from ConsensusMapNormalizerAlgorithmMedian cimport ConsensusMapNormalizerAlgorithmMedian as _ConsensusMapNormalizerAlgorithmMedian
from ConsensusMapNormalizerAlgorithmQuantile cimport ConsensusMapNormalizerAlgorithmQuantile as _ConsensusMapNormalizerAlgorithmQuantile
from ConsensusMapNormalizerAlgorithmThreshold cimport ConsensusMapNormalizerAlgorithmThreshold as _ConsensusMapNormalizerAlgorithmThreshold
from ConsensusXMLFile cimport ConsensusXMLFile as _ConsensusXMLFile
from TargetedExperimentHelper cimport Contact as _Contact
from ContactPerson cimport ContactPerson as _ContactPerson
from ControlledVocabulary cimport ControlledVocabulary as _ControlledVocabulary
from ConvexHull2D cimport ConvexHull2D as _ConvexHull2D
from CrossLinkSpectrumMatch cimport CrossLinkSpectrumMatch as _CrossLinkSpectrumMatch
from CrossLinksDB cimport CrossLinksDB as _CrossLinksDB
from CsvFile cimport CsvFile as _CsvFile
from CubicSpline2d cimport CubicSpline2d as _CubicSpline2d
from DBoundingBox cimport DBoundingBox2 as _DBoundingBox2
from DIAScoring cimport DIAScoring as _DIAScoring
from DPosition cimport DPosition1 as _DPosition1
from DPosition cimport DPosition2 as _DPosition2
from DRange cimport DRange1 as _DRange1
from DRange cimport DRange2 as _DRange2
from DTA2DFile cimport DTA2DFile as _DTA2DFile
from DTAFile cimport DTAFile as _DTAFile
from DataFilters cimport DataFilter as _DataFilter
from DataFilters cimport DataFilters as _DataFilters
from DataProcessing cimport DataProcessing as _DataProcessing
from DataValue cimport DataValue as _DataValue
from Date cimport Date as _Date
from DateTime cimport DateTime as _DateTime
from DecoyGenerator cimport DecoyGenerator as _DecoyGenerator
from DefaultParamHandler cimport DefaultParamHandler as _DefaultParamHandler
from Deisotoper cimport Deisotoper as _Deisotoper
from DigestionEnzyme cimport DigestionEnzyme as _DigestionEnzyme
from DigestionEnzymeProtein cimport DigestionEnzymeProtein as _DigestionEnzymeProtein
from DigestionEnzymeRNA cimport DigestionEnzymeRNA as _DigestionEnzymeRNA
from IDFilter cimport DigestionFilter as _DigestionFilter
from DistanceMatrix cimport DistanceMatrix as _DistanceMatrix
from DocumentIdentifier cimport DocumentIdentifier as _DocumentIdentifier
from EDTAFile cimport EDTAFile as _EDTAFile
from Element cimport Element as _Element
from ElementDB cimport ElementDB as _ElementDB
from ElutionModelFitter cimport ElutionModelFitter as _ElutionModelFitter
from ElutionPeakDetection cimport ElutionPeakDetection as _ElutionPeakDetection
from EmgFitter1D cimport EmgFitter1D as _EmgFitter1D
from EmgGradientDescent cimport EmgGradientDescent as _EmgGradientDescent
from EmgModel cimport EmgModel as _EmgModel
from EmgScoring cimport EmgScoring as _EmgScoring
from EmpiricalFormula cimport EmpiricalFormula as _EmpiricalFormula
from EnzymaticDigestion cimport EnzymaticDigestion as _EnzymaticDigestion
from ExperimentalDesign cimport ExperimentalDesign as _ExperimentalDesign
from ExperimentalDesignFile cimport ExperimentalDesignFile as _ExperimentalDesignFile
from ExperimentalDesign cimport ExperimentalDesign_MSFileSectionEntry as _ExperimentalDesign_MSFileSectionEntry
from ExperimentalDesign cimport ExperimentalDesign_SampleSection as _ExperimentalDesign_SampleSection
from ExperimentalSettings cimport ExperimentalSettings as _ExperimentalSettings
from ChromatogramExtractorAlgorithm cimport ExtractionCoordinates as _ExtractionCoordinates
from FASTAFile cimport FASTAEntry as _FASTAEntry
from FASTAFile cimport FASTAFile as _FASTAFile
from FIAMSDataProcessor cimport FIAMSDataProcessor as _FIAMSDataProcessor
from FIAMSScheduler cimport FIAMSScheduler as _FIAMSScheduler
from FalseDiscoveryRate cimport FalseDiscoveryRate as _FalseDiscoveryRate
from Feature cimport Feature as _Feature
from FeatureDeconvolution cimport FeatureDeconvolution as _FeatureDeconvolution
from FeatureDistance cimport FeatureDistance as _FeatureDistance
from FeatureFileOptions cimport FeatureFileOptions as _FeatureFileOptions
from FeatureFinderAlgorithmMetaboIdent cimport FeatureFinderAlgorithmMetaboIdent as _FeatureFinderAlgorithmMetaboIdent
from FeatureFinderAlgorithmPicked cimport FeatureFinderAlgorithmPicked as _FeatureFinderAlgorithmPicked
from FeatureFinderIdentificationAlgorithm cimport FeatureFinderIdentificationAlgorithm as _FeatureFinderIdentificationAlgorithm
from FeatureFinderAlgorithmMetaboIdent cimport FeatureFinderMetaboIdentCompound as _FeatureFinderMetaboIdentCompound
from FeatureFinderMultiplexAlgorithm cimport FeatureFinderMultiplexAlgorithm as _FeatureFinderMultiplexAlgorithm
from FeatureFindingMetabo cimport FeatureFindingMetabo as _FeatureFindingMetabo
from FeatureGroupingAlgorithm cimport FeatureGroupingAlgorithm as _FeatureGroupingAlgorithm
from FeatureGroupingAlgorithmKD cimport FeatureGroupingAlgorithmKD as _FeatureGroupingAlgorithmKD
from FeatureGroupingAlgorithmLabeled cimport FeatureGroupingAlgorithmLabeled as _FeatureGroupingAlgorithmLabeled
from FeatureGroupingAlgorithmQT cimport FeatureGroupingAlgorithmQT as _FeatureGroupingAlgorithmQT
from FeatureGroupingAlgorithmUnlabeled cimport FeatureGroupingAlgorithmUnlabeled as _FeatureGroupingAlgorithmUnlabeled
from FeatureHandle cimport FeatureHandle as _FeatureHandle
from FeatureMap cimport FeatureMap as _FeatureMap
from FeatureMapping cimport FeatureMapping as _FeatureMapping
from FeatureMapping cimport FeatureMapping_FeatureMappingInfo as _FeatureMapping_FeatureMappingInfo
from FeatureMapping cimport FeatureMapping_FeatureToMs2Indices as _FeatureMapping_FeatureToMs2Indices
from FeatureXMLFile cimport FeatureXMLFile as _FeatureXMLFile
from File cimport File as _File
from FileHandler cimport FileHandler as _FileHandler
from FileTypes cimport FileTypes as _FileTypes
from IsotopeDistribution cimport FineIsotopePatternGenerator as _FineIsotopePatternGenerator
from Fitter1D cimport Fitter1D as _Fitter1D
from FloatDataArray cimport FloatDataArray as _FloatDataArray
from SwathFileConsumer cimport FullSwathFileConsumer as _FullSwathFileConsumer
from GNPSMGFFile cimport GNPSMGFFile as _GNPSMGFFile
from GNPSMetaValueFile cimport GNPSMetaValueFile as _GNPSMetaValueFile
from GNPSQuantificationFile cimport GNPSQuantificationFile as _GNPSQuantificationFile
from GaussFilter cimport GaussFilter as _GaussFilter
from GaussFitter cimport GaussFitResult as _GaussFitResult
from GaussFitter cimport GaussFitter as _GaussFitter
from GaussTraceFitter cimport GaussTraceFitter as _GaussTraceFitter
from Gradient cimport Gradient as _Gradient
from GridBasedCluster cimport GridBasedCluster as _GridBasedCluster
from HPLC cimport HPLC as _HPLC
from HyperScore cimport HyperScore as _HyperScore
from IBSpectraFile cimport IBSpectraFile as _IBSpectraFile
from IDConflictResolverAlgorithm cimport IDConflictResolverAlgorithm as _IDConflictResolverAlgorithm
from IDDecoyProbability cimport IDDecoyProbability as _IDDecoyProbability
from IDFilter cimport IDFilter as _IDFilter
from IDMapper cimport IDMapper as _IDMapper
from IDMapper cimport IDMapper_PeptideIdentificationListState as _IDMapper_PeptideIdentificationListState
from IDRipper cimport IDRipper as _IDRipper
from ILPDCWrapper cimport ILPDCWrapper as _ILPDCWrapper
from IMSAlphabet cimport IMSAlphabet as _IMSAlphabet
from IMSElement cimport IMSElement as _IMSElement
from IMSIsotopeDistribution cimport IMSIsotopeDistribution as _IMSIsotopeDistribution
from IMSIsotopeDistribution cimport IMSIsotopeDistribution_Peak as _IMSIsotopeDistribution_Peak
from Weights cimport IMSWeights as _IMSWeights
from IMTypes cimport IMTypes as _IMTypes
from ISpectrumAccess cimport ISpectrumAccess as _ISpectrumAccess
from IdXMLFile cimport IdXMLFile as _IdXMLFile
from IDRipper cimport IdentificationRuns as _IdentificationRuns
from IncludeExcludeTarget cimport IncludeExcludeTarget as _IncludeExcludeTarget
from IndexedMzMLDecoder cimport IndexedMzMLDecoder as _IndexedMzMLDecoder
from IndexedMzMLFileLoader cimport IndexedMzMLFileLoader as _IndexedMzMLFileLoader
from IndexedMzMLFile cimport IndexedMzMLHandler as _IndexedMzMLHandler
from InspectInfile cimport InspectInfile as _InspectInfile
from InspectOutfile cimport InspectOutfile as _InspectOutfile
from Instrument cimport Instrument as _Instrument
from InstrumentSettings cimport InstrumentSettings as _InstrumentSettings
from IntegerDataArray cimport IntegerDataArray as _IntegerDataArray
from IntegerMassDecomposer cimport IntegerMassDecomposer as _IntegerMassDecomposer
from InternalCalibration cimport InternalCalibration as _InternalCalibration
from InternalCalibration cimport InternalCalibration_LockMass as _InternalCalibration_LockMass
from MzMLValidator cimport Internal_MzMLValidator as _Internal_MzMLValidator
from InterpolationModel cimport InterpolationModel as _InterpolationModel
from TransformationModelInterpolated cimport Interpolator as _Interpolator
from IonDetector cimport IonDetector as _IonDetector
from IonIdentityMolecularNetworking cimport IonIdentityMolecularNetworking as _IonIdentityMolecularNetworking
from IonSource cimport IonSource as _IonSource
from IsobaricChannelExtractor cimport IsobaricChannelExtractor as _IsobaricChannelExtractor
from IsobaricChannelInformation cimport IsobaricChannelInformation as _IsobaricChannelInformation
from IsobaricIsotopeCorrector cimport IsobaricIsotopeCorrector as _IsobaricIsotopeCorrector
from IsobaricNormalizer cimport IsobaricNormalizer as _IsobaricNormalizer
from IsobaricQuantifier cimport IsobaricQuantifier as _IsobaricQuantifier
from IsobaricQuantifierStatistics cimport IsobaricQuantifierStatistics as _IsobaricQuantifierStatistics
from IsobaricQuantitationMethod cimport IsobaricQuantitationMethod as _IsobaricQuantitationMethod
from IsotopeCluster cimport IsotopeCluster as _IsotopeCluster
from IsotopeDistribution cimport IsotopeDistribution as _IsotopeDistribution
from IsotopeFitter1D cimport IsotopeFitter1D as _IsotopeFitter1D
from IsotopeLabelingMDVs cimport IsotopeLabelingMDVs as _IsotopeLabelingMDVs
from IsotopeModel cimport IsotopeModel as _IsotopeModel
from FeatureFinderAlgorithmPickedHelperStructs cimport IsotopePattern as _IsotopePattern
from ItraqConstants cimport ItraqConstants as _ItraqConstants
from ItraqEightPlexQuantitationMethod cimport ItraqEightPlexQuantitationMethod as _ItraqEightPlexQuantitationMethod
from ItraqFourPlexQuantitationMethod cimport ItraqFourPlexQuantitationMethod as _ItraqFourPlexQuantitationMethod
from JavaInfo cimport JavaInfo as _JavaInfo
from KDTreeFeatureMaps cimport KDTreeFeatureMaps as _KDTreeFeatureMaps
from KDTreeFeatureNode cimport KDTreeFeatureNode as _KDTreeFeatureNode
from MassTrace cimport Kernel_MassTrace as _Kernel_MassTrace
from KroenikFile cimport KroenikFile as _KroenikFile
from LPWrapper cimport LPWrapper as _LPWrapper
from LabeledPairFinder cimport LabeledPairFinder as _LabeledPairFinder
from LevMarqFitter1D cimport LevMarqFitter1D as _LevMarqFitter1D
from LightTargetedExperiment cimport LightCompound as _LightCompound
from MRMTransitionGroup cimport MRMTransitionGroup as _MRMTransitionGroup
from LightTargetedExperiment cimport LightModification as _LightModification
from LightTargetedExperiment cimport LightProtein as _LightProtein
from LightTargetedExperiment cimport LightTargetedExperiment as _LightTargetedExperiment
from LightTargetedExperiment cimport LightTransition as _LightTransition
from LinearInterpolation cimport LinearInterpolation as _LinearInterpolation
from LinearResampler cimport LinearResampler as _LinearResampler
from LinearResamplerAlign cimport LinearResamplerAlign as _LinearResamplerAlign
from LogConfigHandler cimport LogConfigHandler as _LogConfigHandler
from LowessSmoothing cimport LowessSmoothing as _LowessSmoothing
from MRMAssay cimport MRMAssay as _MRMAssay
from MRMDecoy cimport MRMDecoy as _MRMDecoy
from MRMFeaturePicker cimport MRMFP_ComponentGroupParams as _MRMFP_ComponentGroupParams
from MRMFeaturePicker cimport MRMFP_ComponentParams as _MRMFP_ComponentParams
from MRMFeatureQC cimport MRMFQC_ComponentGroupPairQCs as _MRMFQC_ComponentGroupPairQCs
from MRMFeatureQC cimport MRMFQC_ComponentGroupQCs as _MRMFQC_ComponentGroupQCs
from MRMFeatureQC cimport MRMFQC_ComponentQCs as _MRMFQC_ComponentQCs
from MRMFeature cimport MRMFeature as _MRMFeature
from MRMFeatureFilter cimport MRMFeatureFilter as _MRMFeatureFilter
from MRMFeatureFinderScoring cimport MRMFeatureFinderScoring as _MRMFeatureFinderScoring
from MRMFeaturePicker cimport MRMFeaturePicker as _MRMFeaturePicker
from MRMFeaturePickerFile cimport MRMFeaturePickerFile as _MRMFeaturePickerFile
from MRMFeatureQC cimport MRMFeatureQC as _MRMFeatureQC
from MRMFeatureQCFile cimport MRMFeatureQCFile as _MRMFeatureQCFile
from MRMIonSeries cimport MRMIonSeries as _MRMIonSeries
from MRMMapping cimport MRMMapping as _MRMMapping
from MRMRTNormalizer cimport MRMRTNormalizer as _MRMRTNormalizer
from MRMScoring cimport MRMScoring as _MRMScoring
from MRMTransitionGroup cimport MRMTransitionGroup as _MRMTransitionGroup
from MRMTransitionGroupPicker cimport MRMTransitionGroupPicker as _MRMTransitionGroupPicker
from MS2File cimport MS2File as _MS2File
from MSChromatogram cimport MSChromatogram as _MSChromatogram
from MSDataAggregatingConsumer cimport MSDataAggregatingConsumer as _MSDataAggregatingConsumer
from MSDataCachedConsumer cimport MSDataCachedConsumer as _MSDataCachedConsumer
from MSDataSqlConsumer cimport MSDataSqlConsumer as _MSDataSqlConsumer
from MSDataStoringConsumer cimport MSDataStoringConsumer as _MSDataStoringConsumer
from MSExperiment cimport MSExperiment as _MSExperiment
from MSNumpressCoder cimport MSNumpressCoder as _MSNumpressCoder
from MSPFile cimport MSPFile as _MSPFile
from MSPGenericFile cimport MSPGenericFile as _MSPGenericFile
from MSSpectrum cimport MSSpectrum as _MSSpectrum
from MSstatsFile cimport MSstatsFile as _MSstatsFile
from MZTrafoModel cimport MZTrafoModel as _MZTrafoModel
from MapAlignmentAlgorithmIdentification cimport MapAlignmentAlgorithmIdentification as _MapAlignmentAlgorithmIdentification
from MapAlignmentAlgorithmKD cimport MapAlignmentAlgorithmKD as _MapAlignmentAlgorithmKD
from MapAlignmentAlgorithmPoseClustering cimport MapAlignmentAlgorithmPoseClustering as _MapAlignmentAlgorithmPoseClustering
from MapAlignmentEvaluationAlgorithm cimport MapAlignmentEvaluationAlgorithm as _MapAlignmentEvaluationAlgorithm
from MapAlignmentEvaluationAlgorithmPrecision cimport MapAlignmentEvaluationAlgorithmPrecision as _MapAlignmentEvaluationAlgorithmPrecision
from MapAlignmentEvaluationAlgorithmRecall cimport MapAlignmentEvaluationAlgorithmRecall as _MapAlignmentEvaluationAlgorithmRecall
from MapAlignmentTransformer cimport MapAlignmentTransformer as _MapAlignmentTransformer
from ConversionHelper cimport MapConversion as _MapConversion
from MascotGenericFile cimport MascotGenericFile as _MascotGenericFile
from MascotXMLFile cimport MascotXMLFile as _MascotXMLFile
from MassAnalyzer cimport MassAnalyzer as _MassAnalyzer
from MassDecomposition cimport MassDecomposition as _MassDecomposition
from MassDecompositionAlgorithm cimport MassDecompositionAlgorithm as _MassDecompositionAlgorithm
from MassExplainer cimport MassExplainer as _MassExplainer
from FeatureFinderAlgorithmPickedHelperStructs cimport MassTrace as _MassTrace
from MassTraceDetection cimport MassTraceDetection as _MassTraceDetection
from FeatureFinderAlgorithmPickedHelperStructs cimport MassTraces as _MassTraces
from MasstraceCorrelator cimport MasstraceCorrelator as _MasstraceCorrelator
from Matrix cimport Matrix as _Matrix
from MetaInfo cimport MetaInfo as _MetaInfo
from MetaInfoDescription cimport MetaInfoDescription as _MetaInfoDescription
from MetaInfoInterface cimport MetaInfoInterface as _MetaInfoInterface
from MetaInfoRegistry cimport MetaInfoRegistry as _MetaInfoRegistry
from MetaboTargetedAssay cimport MetaboTargetedAssay as _MetaboTargetedAssay
from MetaboTargetedAssay cimport MetaboTargetedAssay_CompoundTargetDecoyPair as _MetaboTargetedAssay_CompoundTargetDecoyPair
from MetaboTargetedTargetDecoy cimport MetaboTargetedTargetDecoy as _MetaboTargetedTargetDecoy
from MetaboTargetedTargetDecoy cimport MetaboTargetedTargetDecoy_MetaboTargetDecoyMassMapping as _MetaboTargetedTargetDecoy_MetaboTargetDecoyMassMapping
from MetaboliteFeatureDeconvolution cimport MetaboliteFeatureDeconvolution as _MetaboliteFeatureDeconvolution
from MetaboliteSpectralMatching cimport MetaboliteSpectralMatching as _MetaboliteSpectralMatching
from ModificationDefinition cimport ModificationDefinition as _ModificationDefinition
from ModificationDefinitionsSet cimport ModificationDefinitionsSet as _ModificationDefinitionsSet
from ModificationsDB cimport ModificationsDB as _ModificationsDB
from ModifiedPeptideGenerator cimport ModifiedPeptideGenerator as _ModifiedPeptideGenerator
from ModifiedPeptideGenerator cimport ModifiedPeptideGenerator_MapToResidueType as _ModifiedPeptideGenerator_MapToResidueType
from MorpheusScore cimport MorpheusScore as _MorpheusScore
from MorpheusScore cimport MorpheusScore_Result as _MorpheusScore_Result
from MorphologicalFilter cimport MorphologicalFilter as _MorphologicalFilter
from MsInspectFile cimport MsInspectFile as _MsInspectFile
from MultiplexDeltaMasses cimport MultiplexDeltaMasses as _MultiplexDeltaMasses
from MultiplexDeltaMassesGenerator cimport MultiplexDeltaMassesGenerator as _MultiplexDeltaMassesGenerator
from MultiplexDeltaMassesGenerator cimport MultiplexDeltaMassesGenerator_Label as _MultiplexDeltaMassesGenerator_Label
from MultiplexDeltaMasses cimport MultiplexDeltaMasses_DeltaMass as _MultiplexDeltaMasses_DeltaMass
from MultiplexIsotopicPeakPattern cimport MultiplexIsotopicPeakPattern as _MultiplexIsotopicPeakPattern
from MzDataFile cimport MzDataFile as _MzDataFile
from MzIdentMLFile cimport MzIdentMLFile as _MzIdentMLFile
from MzMLFile cimport MzMLFile as _MzMLFile
from MzMLSpectrumDecoder cimport MzMLSpectrumDecoder as _MzMLSpectrumDecoder
from MzMLSqliteHandler cimport MzMLSqliteHandler as _MzMLSqliteHandler
from SwathFileConsumer cimport MzMLSwathFileConsumer as _MzMLSwathFileConsumer
from MzQCFile cimport MzQCFile as _MzQCFile
from MzTab cimport MzTab as _MzTab
from MzTabFile cimport MzTabFile as _MzTabFile
from MzTabM cimport MzTabM as _MzTabM
from MzTabMFile cimport MzTabMFile as _MzTabMFile
from MzXMLFile cimport MzXMLFile as _MzXMLFile
from NASequence cimport NASequence as _NASequence
from NLargest cimport NLargest as _NLargest
from SignalToNoiseEstimatorMedianRapid cimport NoiseEstimator as _NoiseEstimator
from NonNegativeLeastSquaresSolver cimport NonNegativeLeastSquaresSolver as _NonNegativeLeastSquaresSolver
from MSDataWritingConsumer cimport NoopMSDataWritingConsumer as _NoopMSDataWritingConsumer
from Normalizer cimport Normalizer as _Normalizer
from NucleicAcidSpectrumGenerator cimport NucleicAcidSpectrumGenerator as _NucleicAcidSpectrumGenerator
from TargetedExperimentHelper cimport Nuctide as _Nuctide
from MSNumpressCoder cimport NumpressConfig as _NumpressConfig
from OMSSACSVFile cimport OMSSACSVFile as _OMSSACSVFile
from OMSSAXMLFile cimport OMSSAXMLFile as _OMSSAXMLFile
from OPXLDataStructs cimport OPXLDataStructs as _OPXLDataStructs
from OPXLHelper cimport OPXLHelper as _OPXLHelper
from OPXLSpectrumProcessingAlgorithms cimport OPXLSpectrumProcessingAlgorithms as _OPXLSpectrumProcessingAlgorithms
from PreprocessedPairSpectra cimport OPXL_PreprocessedPairSpectra as _OPXL_PreprocessedPairSpectra
from OpenSwathDataStructures cimport OSBinaryDataArray as _OSBinaryDataArray
from OpenSwathDataStructures cimport OSChromatogram as _OSChromatogram
from OSChromatogramMeta cimport OSChromatogramMeta as _OSChromatogramMeta
from OpenSwathDataStructures cimport OSSpectrum as _OSSpectrum
from OSSpectrumMeta cimport OSSpectrumMeta as _OSSpectrumMeta
from OSWFile cimport OSWFile as _OSWFile
from ChromExtractParams cimport OSW_ChromExtractParams as _OSW_ChromExtractParams
from OnDiscMSExperiment cimport OnDiscMSExperiment as _OnDiscMSExperiment
from BuildInfo cimport OpenMSBuildInfo as _OpenMSBuildInfo
from BuildInfo cimport OpenMSOSInfo as _OpenMSOSInfo
from OpenPepXLAlgorithm cimport OpenPepXLAlgorithm as _OpenPepXLAlgorithm
from OpenPepXLLFAlgorithm cimport OpenPepXLLFAlgorithm as _OpenPepXLLFAlgorithm
from OpenSwathDataAccessHelper cimport OpenSwathDataAccessHelper as _OpenSwathDataAccessHelper
from OpenSwathHelper cimport OpenSwathHelper as _OpenSwathHelper
from OpenSwathOSWWriter cimport OpenSwathOSWWriter as _OpenSwathOSWWriter
from OpenSwathScoring cimport OpenSwathScoring as _OpenSwathScoring
from OpenSwathScoring cimport OpenSwath_Scores as _OpenSwath_Scores
from OpenSwathScoring cimport OpenSwath_Scores_Usage as _OpenSwath_Scores_Usage
from PeakIntegrator cimport PI_PeakArea as _PI_PeakArea
from PeakIntegrator cimport PI_PeakBackground as _PI_PeakBackground
from PeakIntegrator cimport PI_PeakShapeMetrics as _PI_PeakShapeMetrics
from PScore cimport PScore as _PScore
from Param cimport Param as _Param
from ParamCTDFile cimport ParamCTDFile as _ParamCTDFile
from ParamEntry cimport ParamEntry as _ParamEntry
from Param cimport ParamIterator as _ParamIterator
from ParamNode cimport ParamNode as _ParamNode
from ParamValue cimport ParamValue as _ParamValue
from ParamXMLFile cimport ParamXMLFile as _ParamXMLFile
from Peak1D cimport Peak1D as _Peak1D
from Peak2D cimport Peak2D as _Peak2D
from PeakPickerHiRes cimport PeakBoundary as _PeakBoundary
from PeakFileOptions cimport PeakFileOptions as _PeakFileOptions
from PeakIndex cimport PeakIndex as _PeakIndex
from PeakIntegrator cimport PeakIntegrator as _PeakIntegrator
from PeakPickerChromatogram cimport PeakPickerChromatogram as _PeakPickerChromatogram
from PeakPickerHiRes cimport PeakPickerHiRes as _PeakPickerHiRes
from PeakPickerIterative cimport PeakPickerIterative as _PeakPickerIterative
from PeakTypeEstimator cimport PeakTypeEstimator as _PeakTypeEstimator
from PeakWidthEstimator cimport PeakWidthEstimator as _PeakWidthEstimator
from PepXMLFile cimport PepXMLFile as _PepXMLFile
from PepXMLFileMascot cimport PepXMLFileMascot as _PepXMLFileMascot
from TargetedExperimentHelper cimport Peptide as _Peptide
from PeptideAndProteinQuant cimport PeptideAndProteinQuant as _PeptideAndProteinQuant
from PeptideAndProteinQuant cimport PeptideAndProteinQuant_PeptideData as _PeptideAndProteinQuant_PeptideData
from PeptideAndProteinQuant cimport PeptideAndProteinQuant_ProteinData as _PeptideAndProteinQuant_ProteinData
from PeptideAndProteinQuant cimport PeptideAndProteinQuant_Statistics as _PeptideAndProteinQuant_Statistics
from PeptideEvidence cimport PeptideEvidence as _PeptideEvidence
from PeptideHit cimport PeptideHit as _PeptideHit
from PeptideHit cimport PeptideHit_AnalysisResult as _PeptideHit_AnalysisResult
from PeptideHit cimport PeptideHit_PeakAnnotation as _PeptideHit_PeakAnnotation
from PeptideIdentification cimport PeptideIdentification as _PeptideIdentification
from PeptideIdentificationList cimport PeptideIdentificationList as _PeptideIdentificationList
from PeptideIndexing cimport PeptideIndexing as _PeptideIndexing
from PeptideProteinResolution cimport PeptideProteinResolution as _PeptideProteinResolution
from PeptideProteinResolution cimport PeptideProteinResolution_ConnectedComponent as _PeptideProteinResolution_ConnectedComponent
from PercolatorFeatureSetHelper cimport PercolatorFeatureSetHelper as _PercolatorFeatureSetHelper
from PercolatorInfile cimport PercolatorInfile as _PercolatorInfile
from PercolatorOutfile cimport PercolatorOutfile as _PercolatorOutfile
from MSDataWritingConsumer cimport PlainMSDataWritingConsumer as _PlainMSDataWritingConsumer
from PosteriorErrorProbabilityModel cimport PosteriorErrorProbabilityModel as _PosteriorErrorProbabilityModel
from Precursor cimport Precursor as _Precursor
from PrecursorCorrection cimport PrecursorCorrection as _PrecursorCorrection
from PrecursorPurity cimport PrecursorPurity as _PrecursorPurity
from TargetedExperimentHelper cimport Prediction as _Prediction
from AScore cimport ProbablePhosphoSites as _ProbablePhosphoSites
from Product cimport Product as _Product
from ProgressLogger cimport ProgressLogger as _ProgressLogger
from ProtXMLFile cimport ProtXMLFile as _ProtXMLFile
from ProteaseDB cimport ProteaseDB as _ProteaseDB
from ProteaseDigestion cimport ProteaseDigestion as _ProteaseDigestion
from TargetedExperimentHelper cimport Protein as _Protein
from ProteinIdentification cimport ProteinGroup as _ProteinGroup
from ProteinHit cimport ProteinHit as _ProteinHit
from ProteinIdentification cimport ProteinIdentification as _ProteinIdentification
from ProteinInference cimport ProteinInference as _ProteinInference
from ProteinProteinCrossLink cimport ProteinProteinCrossLink as _ProteinProteinCrossLink
from TargetedExperimentHelper cimport Publication as _Publication
from PrecursorPurity cimport PurityScores as _PurityScores
from PythonMSDataConsumer cimport PythonMSDataConsumer as _PythonMSDataConsumer
from QTCluster cimport QTCluster as _QTCluster
from QTClusterFinder cimport QTClusterFinder as _QTClusterFinder
from QcMLFile cimport QcMLFile as _QcMLFile
from QcMLFile cimport QualityParameter as _QualityParameter
from RANSAC cimport RANSAC as _RANSAC
from RANSAC cimport RANSACParam as _RANSACParam
from RANSAC cimport RANSAC as _RANSAC
from RNaseDB cimport RNaseDB as _RNaseDB
from RNaseDigestion cimport RNaseDigestion as _RNaseDigestion
from RangeManager cimport RangeBase as _RangeBase
from RangeManager cimport RangeIntensity as _RangeIntensity
from RangeManager cimport RangeMZ as _RangeMZ
from RangeManager cimport RangeManagerMzInt as _RangeManagerMzInt
from RangeManager cimport RangeManagerRtInt as _RangeManagerRtInt
from RangeManager cimport RangeManagerRtMzInt as _RangeManagerRtMzInt
from RangeManager cimport RangeManagerRtMzIntMob as _RangeManagerRtMzIntMob
from RangeManager cimport RangeMobility as _RangeMobility
from RangeManager cimport RangeRT as _RangeRT
from RankScaler cimport RankScaler as _RankScaler
from RANSACModelLinear cimport RansacModelLinear as _RansacModelLinear
from RANSACModelQuadratic cimport RansacModelQuadratic as _RansacModelQuadratic
from ConsensusFeature cimport Ratio as _Ratio
from ReactionMonitoringTransition cimport ReactionMonitoringTransition as _ReactionMonitoringTransition
from RealMassDecomposer cimport RealMassDecomposer as _RealMassDecomposer
from SwathFileConsumer cimport RegularSwathFileConsumer as _RegularSwathFileConsumer
from Residue cimport Residue as _Residue
from ResidueDB cimport ResidueDB as _ResidueDB
from ResidueModification cimport ResidueModification as _ResidueModification
from TargetedExperimentHelper cimport RetentionTime as _RetentionTime
from Ribonucleotide cimport Ribonucleotide as _Ribonucleotide
from RibonucleotideDB cimport RibonucleotideDB as _RibonucleotideDB
from RichPeak2D cimport RichPeak2D as _RichPeak2D
from IDRipper cimport RipFileContent as _RipFileContent
from IDRipper cimport RipFileIdentifier as _RipFileIdentifier
from Sample cimport Sample as _Sample
from SavitzkyGolayFilter cimport SavitzkyGolayFilter as _SavitzkyGolayFilter
from ScanWindow cimport ScanWindow as _ScanWindow
from ProteinIdentification cimport SearchParameters as _SearchParameters
from FeatureFinderAlgorithmPickedHelperStructs cimport Seed as _Seed
from SeedListGenerator cimport SeedListGenerator as _SeedListGenerator
from SemanticValidator cimport SemanticValidator as _SemanticValidator
from SemanticValidator cimport SemanticValidator_CVTerm as _SemanticValidator_CVTerm
from SequestInfile cimport SequestInfile as _SequestInfile
from SequestOutfile cimport SequestOutfile as _SequestOutfile
from SignalToNoiseEstimatorMeanIterative cimport SignalToNoiseEstimatorMeanIterative as _SignalToNoiseEstimatorMeanIterative
from SignalToNoiseEstimatorMedian cimport SignalToNoiseEstimatorMedian as _SignalToNoiseEstimatorMedian
from SignalToNoiseEstimatorMedianRapid cimport SignalToNoiseEstimatorMedianRapid as _SignalToNoiseEstimatorMedianRapid
from SimpleOpenMSSpectraFactory cimport SimpleOpenMSSpectraFactory as _SimpleOpenMSSpectraFactory
from SimpleTSGXLMS cimport SimplePeak as _SimplePeak
from SimpleSearchEngineAlgorithm cimport SimpleSearchEngineAlgorithm as _SimpleSearchEngineAlgorithm
from SimpleTSGXLMS cimport SimpleTSGXLMS as _SimpleTSGXLMS
from SiriusExportAlgorithm cimport SiriusExportAlgorithm as _SiriusExportAlgorithm
from SiriusFragmentAnnotation cimport SiriusFragmentAnnotation as _SiriusFragmentAnnotation
from SiriusFragmentAnnotation cimport SiriusFragmentAnnotation_SiriusTargetDecoySpectra as _SiriusFragmentAnnotation_SiriusTargetDecoySpectra
from SiriusMSFile cimport SiriusMSFile as _SiriusMSFile
from SiriusMSFile cimport SiriusMSFile_AccessionInfo as _SiriusMSFile_AccessionInfo
from SiriusMSFile cimport SiriusMSFile_CompoundInfo as _SiriusMSFile_CompoundInfo
from Software cimport Software as _Software
from LPWrapper cimport SolverParam as _SolverParam
from SourceFile cimport SourceFile as _SourceFile
from SpectraMerger cimport SpectraMerger as _SpectraMerger
from SpectraSTSimilarityScore cimport SpectraSTSimilarityScore as _SpectraSTSimilarityScore
from MetaboliteSpectralMatching cimport SpectralMatch as _SpectralMatch
from SpectrumAccessOpenMS cimport SpectrumAccessOpenMS as _SpectrumAccessOpenMS
from SpectrumAccessOpenMSCached cimport SpectrumAccessOpenMSCached as _SpectrumAccessOpenMSCached
from SpectrumAccessOpenMSInMemory cimport SpectrumAccessOpenMSInMemory as _SpectrumAccessOpenMSInMemory
from SpectrumAccessQuadMZTransforming cimport SpectrumAccessQuadMZTransforming as _SpectrumAccessQuadMZTransforming
from SpectrumAccessSqMass cimport SpectrumAccessSqMass as _SpectrumAccessSqMass
from SpectrumAccessTransforming cimport SpectrumAccessTransforming as _SpectrumAccessTransforming
from SpectrumAlignment cimport SpectrumAlignment as _SpectrumAlignment
from SpectrumAlignmentScore cimport SpectrumAlignmentScore as _SpectrumAlignmentScore
from SpectrumAnnotator cimport SpectrumAnnotator as _SpectrumAnnotator
from SpectrumHelper cimport SpectrumHelper as _SpectrumHelper
from SpectrumLookup cimport SpectrumLookup as _SpectrumLookup
from SpectrumMetaDataLookup cimport SpectrumMetaData as _SpectrumMetaData
from SpectrumMetaDataLookup cimport SpectrumMetaDataLookup as _SpectrumMetaDataLookup
from SpectrumRangeManager cimport SpectrumRangeManager as _SpectrumRangeManager
from SpectrumSettings cimport SpectrumSettings as _SpectrumSettings
from SplineInterpolatedPeaks cimport SplineInterpolatedPeaks as _SplineInterpolatedPeaks
from SplinePackage cimport SplinePackage as _SplinePackage
from SplineInterpolatedPeaks cimport SplineSpectrum_Navigator as _SplineSpectrum_Navigator
from SqMassFile cimport SqMassConfig as _SqMassConfig
from SqMassFile cimport SqMassFile as _SqMassFile
from SqrtScaler cimport SqrtScaler as _SqrtScaler
from StablePairFinder cimport StablePairFinder as _StablePairFinder
from String cimport String as _String
from StringDataArray cimport StringDataArray as _StringDataArray
from StringView cimport StringView as _StringView
from SwathFile cimport SwathFile as _SwathFile
from SwathMap cimport SwathMap as _SwathMap
from SwathMapMassCorrection cimport SwathMapMassCorrection as _SwathMapMassCorrection
from SwathWindowLoader cimport SwathWindowLoader as _SwathWindowLoader
from TMTEighteenPlexQuantitationMethod cimport TMTEighteenPlexQuantitationMethod as _TMTEighteenPlexQuantitationMethod
from TMTElevenPlexQuantitationMethod cimport TMTElevenPlexQuantitationMethod as _TMTElevenPlexQuantitationMethod
from TMTSixPlexQuantitationMethod cimport TMTSixPlexQuantitationMethod as _TMTSixPlexQuantitationMethod
from TMTSixteenPlexQuantitationMethod cimport TMTSixteenPlexQuantitationMethod as _TMTSixteenPlexQuantitationMethod
from TMTTenPlexQuantitationMethod cimport TMTTenPlexQuantitationMethod as _TMTTenPlexQuantitationMethod
from TransformationModel cimport TM_DataPoint as _TM_DataPoint
from TargetedSpectraExtractor cimport TSE_Match as _TSE_Match
from Tagger cimport Tagger as _Tagger
from TargetedExperiment cimport TargetedExperiment as _TargetedExperiment
from TargetedExperimentHelper cimport TargetedExperiment_Instrument as _TargetedExperiment_Instrument
from TargetedExperimentHelper cimport TargetedExperiment_Interpretation as _TargetedExperiment_Interpretation
from TargetedExperimentHelper cimport TargetedExperiment_Modification as _TargetedExperiment_Modification
from TargetedSpectraExtractor cimport TargetedSpectraExtractor as _TargetedSpectraExtractor
from TextFile cimport TextFile as _TextFile
from FeatureFinderAlgorithmPickedHelperStructs cimport TheoreticalIsotopePattern as _TheoreticalIsotopePattern
from TheoreticalSpectrumGenerator cimport TheoreticalSpectrumGenerator as _TheoreticalSpectrumGenerator
from TheoreticalSpectrumGeneratorXLMS cimport TheoreticalSpectrumGeneratorXLMS as _TheoreticalSpectrumGeneratorXLMS
from ThresholdMower cimport ThresholdMower as _ThresholdMower
from ParamCTDFile cimport ToolInfo as _ToolInfo
from TraMLFile cimport TraMLFile as _TraMLFile
from TargetedExperimentHelper cimport TraMLProduct as _TraMLProduct
from Param cimport TraceInfo as _TraceInfo
from TransformationDescription cimport TransformationDescription as _TransformationDescription
from TransformationModel cimport TransformationModel as _TransformationModel
from TransformationModelBSpline cimport TransformationModelBSpline as _TransformationModelBSpline
from TransformationModelInterpolated cimport TransformationModelInterpolated as _TransformationModelInterpolated
from TransformationModelLinear cimport TransformationModelLinear as _TransformationModelLinear
from TransformationModelLowess cimport TransformationModelLowess as _TransformationModelLowess
from TransformationDescription cimport TransformationStatistics as _TransformationStatistics
from TransformationXMLFile cimport TransformationXMLFile as _TransformationXMLFile
from TransitionPQPFile cimport TransitionPQPFile as _TransitionPQPFile
from TransitionTSVFile cimport TransitionTSVFile as _TransitionTSVFile
from UnimodXMLFile cimport UnimodXMLFile as _UnimodXMLFile
from UniqueIdGenerator cimport UniqueIdGenerator as _UniqueIdGenerator
from UniqueIdInterface cimport UniqueIdInterface as _UniqueIdInterface
from CVTerm cimport Unit as _Unit
from VersionInfo cimport VersionDetails as _VersionDetails
from VersionInfo cimport VersionInfo as _VersionInfo
from WindowMower cimport WindowMower as _WindowMower
from XFDRAlgorithm cimport XFDRAlgorithm as _XFDRAlgorithm
from XLPrecursor cimport XLPrecursor as _XLPrecursor
from XMLFile cimport XMLFile as _XMLFile
from XMLHandler cimport XMLHandler as _XMLHandler
from XQuestResultXMLFile cimport XQuestResultXMLFile as _XQuestResultXMLFile
from XQuestScores cimport XQuestScores as _XQuestScores
from XTandemInfile cimport XTandemInfile as _XTandemInfile
from XTandemXMLFile cimport XTandemXMLFile as _XTandemXMLFile
from InterfaceDataStructures cimport BinaryDataArray as _BinaryDataArray
from InterfaceDataStructures cimport Chromatogram as _Chromatogram
from InterfaceDataStructures cimport Spectrum as _Spectrum
from streampos cimport streampos as _streampos
from ._pyopenms_1 cimport FileTypes
from ._pyopenms_1 cimport FileType
from ._pyopenms_1 cimport SemanticValidator
from ._pyopenms_1 cimport SemanticValidator_CVTerm
from ._pyopenms_1 cimport EDTAFile
from ._pyopenms_1 cimport SpectrumAlignment
from ._pyopenms_1 cimport MSPGenericFile
from ._pyopenms_1 cimport RealMassDecomposer
from ._pyopenms_1 cimport AScore
from ._pyopenms_1 cimport ProbablePhosphoSites
from ._pyopenms_1 cimport IDDecoyProbability
from ._pyopenms_1 cimport ChromatogramTools
from ._pyopenms_1 cimport KroenikFile
from ._pyopenms_1 cimport SpectrumAnnotator
from ._pyopenms_1 cimport CVTermListInterface
from ._pyopenms_1 cimport PeptideIdentificationList
from ._pyopenms_1 cimport PeakPickerIterative
from ._pyopenms_2 cimport SpectrumAccessSqMass
from ._pyopenms_2 cimport MRMFeaturePicker
from ._pyopenms_2 cimport MRMFP_ComponentParams
from ._pyopenms_2 cimport MRMFP_ComponentGroupParams
from ._pyopenms_2 cimport FloatDataArray
from ._pyopenms_2 cimport IMTypes
from ._pyopenms_2 cimport DriftTimeUnit
from ._pyopenms_2 cimport IMFormat
from ._pyopenms_2 cimport ControlledVocabulary
from ._pyopenms_2 cimport CVTerm_ControlledVocabulary
from ._pyopenms_2 cimport XRefType_CVTerm_ControlledVocabulary
from ._pyopenms_2 cimport InstrumentSettings
from ._pyopenms_2 cimport ScanMode
from ._pyopenms_2 cimport OSBinaryDataArray
from ._pyopenms_2 cimport OSSpectrum
from ._pyopenms_2 cimport OSChromatogram
from ._pyopenms_2 cimport OPXLSpectrumProcessingAlgorithms
from ._pyopenms_2 cimport MSNumpressCoder
from ._pyopenms_2 cimport NumpressConfig
from ._pyopenms_2 cimport SwathMapMassCorrection
from ._pyopenms_2 cimport MSstatsFile
from ._pyopenms_2 cimport SpectrumHelper
from ._pyopenms_2 cimport TransformationStatistics
from ._pyopenms_2 cimport TransformationDescription
from ._pyopenms_2 cimport IdentificationRuns
from ._pyopenms_2 cimport RipFileIdentifier
from ._pyopenms_2 cimport RipFileContent
from ._pyopenms_2 cimport IDRipper
from ._pyopenms_2 cimport OriginAnnotationFormat
from ._pyopenms_3 cimport IMSAlphabet
from ._pyopenms_3 cimport RichPeak2D
from ._pyopenms_3 cimport OSSpectrumMeta
from ._pyopenms_3 cimport Residue
from ._pyopenms_3 cimport TMTSixPlexQuantitationMethod
from ._pyopenms_3 cimport FASTAFile
from ._pyopenms_3 cimport FASTAEntry
from ._pyopenms_3 cimport AccurateMassSearchEngine
from ._pyopenms_3 cimport MapAlignmentAlgorithmIdentification
from ._pyopenms_3 cimport SignalToNoiseEstimatorMeanIterative
from ._pyopenms_3 cimport CVMappingFile
from ._pyopenms_3 cimport ProteaseDigestion
from ._pyopenms_3 cimport SavitzkyGolayFilter
from ._pyopenms_3 cimport PScore
from ._pyopenms_4 cimport XQuestResultXMLFile
from ._pyopenms_4 cimport XFDRAlgorithm
from ._pyopenms_4 cimport MRMScoring
from ._pyopenms_4 cimport MapAlignmentTransformer
from ._pyopenms_4 cimport CVMappingRule
from ._pyopenms_4 cimport PeakPickerHiRes
from ._pyopenms_4 cimport PeakBoundary
from ._pyopenms_4 cimport InspectOutfile
from ._pyopenms_4 cimport Fitter1D
from ._pyopenms_4 cimport PeakPickerChromatogram
from ._pyopenms_4 cimport OMSSAXMLFile
from ._pyopenms_4 cimport IntegerDataArray
from ._pyopenms_4 cimport String
from ._pyopenms_4 cimport QuotingMethod
from ._pyopenms_4 cimport OSChromatogramMeta
from ._pyopenms_4 cimport XQuestScores
from ._pyopenms_5 cimport ModificationDefinitionsSet
from ._pyopenms_5 cimport SqMassFile
from ._pyopenms_5 cimport SqMassConfig
from ._pyopenms_5 cimport SpectraSTSimilarityScore
from ._pyopenms_5 cimport CVMappingTerm
from ._pyopenms_5 cimport FeatureFinderAlgorithmMetaboIdent
from ._pyopenms_5 cimport FeatureFinderMetaboIdentCompound
from ._pyopenms_5 cimport MetaboliteSpectralMatching
from ._pyopenms_5 cimport SpectralMatch
from ._pyopenms_5 cimport ConsensusMapNormalizerAlgorithmMedian
from ._pyopenms_5 cimport NormalizationMethod
from ._pyopenms_5 cimport MapConversion
from ._pyopenms_5 cimport FeatureMap
from ._pyopenms_5 cimport ConsensusIDAlgorithmAverage
from ._pyopenms_5 cimport FeatureFinderMultiplexAlgorithm
from ._pyopenms_5 cimport GaussFilter
from ._pyopenms_5 cimport SignalToNoiseEstimatorMedianRapid
from ._pyopenms_5 cimport NoiseEstimator
from ._pyopenms_5 cimport IndexedMzMLHandler
from ._pyopenms_6 cimport Internal_MzMLValidator
from ._pyopenms_6 cimport ChromatogramSettings
from ._pyopenms_6 cimport MsInspectFile
from ._pyopenms_6 cimport SqrtScaler
from ._pyopenms_6 cimport AMSE_AdductInfo
from ._pyopenms_6 cimport CubicSpline2d
from ._pyopenms_6 cimport DistanceMatrix
from ._pyopenms_6 cimport HPLC
from ._pyopenms_6 cimport LinearResampler
from ._pyopenms_6 cimport ThresholdMower
from ._pyopenms_6 cimport PepXMLFile
from ._pyopenms_6 cimport AbsoluteQuantitation
from ._pyopenms_6 cimport ExperimentalSettings
from ._pyopenms_6 cimport IDFilter
from ._pyopenms_6 cimport __DigestionFilter
from ._pyopenms_7 cimport OpenSwathOSWWriter
from ._pyopenms_7 cimport TMTTenPlexQuantitationMethod
from ._pyopenms_7 cimport PeakTypeEstimator
from ._pyopenms_7 cimport SequestInfile
from ._pyopenms_7 cimport BiGaussModel
from ._pyopenms_7 cimport IDConflictResolverAlgorithm
from ._pyopenms_7 cimport GridBasedCluster
from ._pyopenms_7 cimport MzTab
from ._pyopenms_7 cimport EmgFitter1D
from ._pyopenms_7 cimport TheoreticalSpectrumGeneratorXLMS
from ._pyopenms_7 cimport OSW_ChromExtractParams
from ._pyopenms_7 cimport DataProcessing
from ._pyopenms_7 cimport MSExperiment
from ._pyopenms_8 cimport MRMAssay
from ._pyopenms_8 cimport MultiplexDeltaMasses
from ._pyopenms_8 cimport MultiplexDeltaMasses_DeltaMass
from ._pyopenms_8 cimport Base64
from ._pyopenms_8 cimport WindowMower
from ._pyopenms_8 cimport TargetedExperiment
from ._pyopenms_8 cimport CVTermList
from ._pyopenms_8 cimport DataFilters
from ._pyopenms_8 cimport DataFilter
from ._pyopenms_8 cimport InternalCalibration
from ._pyopenms_8 cimport InternalCalibration_LockMass
from ._pyopenms_8 cimport FeatureFinderAlgorithmPicked
from ._pyopenms_8 cimport MSDataAggregatingConsumer
from ._pyopenms_8 cimport FileHandler
from ._pyopenms_8 cimport Precursor
from ._pyopenms_8 cimport MRMFeaturePickerFile
from ._pyopenms_8 cimport IonIdentityMolecularNetworking
from ._pyopenms_9 cimport BilinearInterpolation
from ._pyopenms_9 cimport Normalizer
from ._pyopenms_9 cimport MzIdentMLFile
from ._pyopenms_9 cimport ProgressLogger
from ._pyopenms_9 cimport LogType
from ._pyopenms_9 cimport IsobaricQuantifierStatistics
from ._pyopenms_9 cimport PeptideAndProteinQuant
from ._pyopenms_9 cimport PeptideAndProteinQuant_Statistics
from ._pyopenms_9 cimport PeptideAndProteinQuant_PeptideData
from ._pyopenms_9 cimport PeptideAndProteinQuant_ProteinData
from ._pyopenms_9 cimport IndexedMzMLDecoder
from ._pyopenms_9 cimport IsobaricIsotopeCorrector
from ._pyopenms_9 cimport StringDataArray
from ._pyopenms_9 cimport OPXLDataStructs
from ._pyopenms_9 cimport SpectrumMetaDataLookup
from ._pyopenms_9 cimport SpectrumMetaData
from ._pyopenms_9 cimport MetaboliteFeatureDeconvolution
from ._pyopenms_9 cimport CachedMzMLHandler
from ._pyopenms_10 cimport RNaseDB
from ._pyopenms_10 cimport DRange1
from ._pyopenms_10 cimport DRange2
from ._pyopenms_10 cimport DRangeIntersection
from ._pyopenms_10 cimport QTClusterFinder
from ._pyopenms_10 cimport EnzymaticDigestion
from ._pyopenms_10 cimport Ribonucleotide
from ._pyopenms_10 cimport LightTransition
from ._pyopenms_10 cimport LightModification
from ._pyopenms_10 cimport LightCompound
from ._pyopenms_10 cimport LightProtein
from ._pyopenms_10 cimport LightTargetedExperiment
from ._pyopenms_10 cimport FeatureGroupingAlgorithmQT
from ._pyopenms_10 cimport PeptideIndexing
from ._pyopenms_10 cimport UnimodXMLFile
from ._pyopenms_10 cimport TMTEighteenPlexQuantitationMethod
from ._pyopenms_10 cimport MzTabM
from ._pyopenms_10 cimport ConsensusIDAlgorithmPEPMatrix
from ._pyopenms_10 cimport MRMTransitionGroupCP
from ._pyopenms_10 cimport LightMRMTransitionGroupCP
from ._pyopenms_10 cimport VersionInfo
from ._pyopenms_10 cimport VersionDetails
from ._pyopenms_12 cimport GNPSMetaValueFile
from ._pyopenms_12 cimport CalibrationData
from ._pyopenms_12 cimport OpenSwathDataAccessHelper
from ._pyopenms_12 cimport ElutionPeakDetection
from ._pyopenms_12 cimport LPWrapper
from ._pyopenms_12 cimport SolverParam
from ._pyopenms_12 cimport JavaInfo
from ._pyopenms_12 cimport FeatureXMLFile
from ._pyopenms_12 cimport AbsoluteQuantitationMethodFile
from ._pyopenms_12 cimport HyperScore
from ._pyopenms_12 cimport IsobaricNormalizer
from ._pyopenms_12 cimport ParamValue
from ._pyopenms_12 cimport ValueType
from ._pyopenms_12 cimport IMSWeights
from ._pyopenms_12 cimport DigestionEnzyme
from ._pyopenms_13 cimport ConfidenceScoring
from ._pyopenms_13 cimport ConsensusMapNormalizerAlgorithmQuantile
from ._pyopenms_13 cimport ConsensusIDAlgorithmRanks
from ._pyopenms_13 cimport DataValue
from ._pyopenms_13 cimport DataType
from ._pyopenms_13 cimport UnitType
from ._pyopenms_13 cimport MRMDecoy
from ._pyopenms_13 cimport MapAlignmentEvaluationAlgorithmPrecision
from ._pyopenms_13 cimport SpectrumLookup
from ._pyopenms_13 cimport MzMLFile
from ._pyopenms_13 cimport MzMLSpectrumDecoder
from ._pyopenms_13 cimport LabeledPairFinder
from ._pyopenms_13 cimport ProteinInference
from ._pyopenms_13 cimport SpectrumRangeManager
from ._pyopenms_13 cimport SpectrumAccessOpenMSInMemory
from ._pyopenms_14 cimport SpectrumSettings
from ._pyopenms_14 cimport MassExplainer
from ._pyopenms_14 cimport ProteinIdentification
from ._pyopenms_14 cimport ProteinGroup
from ._pyopenms_14 cimport SearchParameters
from ._pyopenms_14 cimport streampos
from ._pyopenms_14 cimport GaussFitter
from ._pyopenms_14 cimport GaussFitResult
from ._pyopenms_14 cimport MRMFQC_ComponentGroupQCs
from ._pyopenms_14 cimport MRMFQC_ComponentQCs
from ._pyopenms_14 cimport MRMFQC_ComponentGroupPairQCs
from ._pyopenms_14 cimport MRMFeatureQC
from ._pyopenms_14 cimport LowessSmoothing
from ._pyopenms_14 cimport EmgScoring
from ._pyopenms_14 cimport PrecursorPurity
from ._pyopenms_14 cimport PurityScores
from ._pyopenms_14 cimport SwathMap
from ._pyopenms_14 cimport MapAlignmentAlgorithmPoseClustering
from ._pyopenms_14 cimport MRMMapping
from ._pyopenms_14 cimport BiGaussFitter1D
from ._pyopenms_15 cimport MzDataFile
from ._pyopenms_15 cimport PeakFileOptions
from ._pyopenms_15 cimport CVTerm
from ._pyopenms_15 cimport Unit
from ._pyopenms_15 cimport OnDiscMSExperiment
from ._pyopenms_15 cimport MassAnalyzer
from ._pyopenms_15 cimport StringView
from ._pyopenms_15 cimport IsotopeModel
from ._pyopenms_15 cimport SequestOutfile
from ._pyopenms_15 cimport ConvexHull2D
from ._pyopenms_15 cimport CrossLinkSpectrumMatch
from ._pyopenms_15 cimport CsvFile
from ._pyopenms_15 cimport XMLHandler
from ._pyopenms_15 cimport NucleicAcidSpectrumGenerator
from ._pyopenms_15 cimport FeatureFindingMetabo
from ._pyopenms_16 cimport ModifiedPeptideGenerator_MapToResidueType
from ._pyopenms_16 cimport ModifiedPeptideGenerator
from ._pyopenms_16 cimport Peak2D
from ._pyopenms_16 cimport DimensionDescription
from ._pyopenms_16 cimport SimpleSearchEngineAlgorithm
from ._pyopenms_16 cimport TM_DataPoint
from ._pyopenms_16 cimport FIAMSDataProcessor
from ._pyopenms_16 cimport SpectrumAccessOpenMS
from ._pyopenms_16 cimport PercolatorFeatureSetHelper
from ._pyopenms_16 cimport Deisotoper
from ._pyopenms_16 cimport BayesianProteinInferenceAlgorithm
from ._pyopenms_16 cimport PeptideIdentification
from ._pyopenms_16 cimport AcquisitionInfo
from ._pyopenms_16 cimport OpenSwathScoring
from ._pyopenms_16 cimport OpenSwath_Scores_Usage
from ._pyopenms_16 cimport OpenSwath_Scores
from ._pyopenms_16 cimport FeatureDeconvolution
from ._pyopenms_16 cimport ElutionModelFitter
from ._pyopenms_16 cimport ResidueModification
from ._pyopenms_17 cimport StablePairFinder
from ._pyopenms_17 cimport DocumentIdentifier
from ._pyopenms_17 cimport MSDataSqlConsumer
from ._pyopenms_17 cimport ClusteringGrid
from ._pyopenms_17 cimport ResidueDB
from ._pyopenms_17 cimport ParamXMLFile
from ._pyopenms_17 cimport IsotopeDistribution
from ._pyopenms_17 cimport FineIsotopePatternGenerator
from ._pyopenms_17 cimport CoarseIsotopePatternGenerator
from ._pyopenms_17 cimport SpectrumAccessQuadMZTransforming
from ._pyopenms_17 cimport ConsensusMapNormalizerAlgorithmThreshold
from ._pyopenms_17 cimport MSPFile
from ._pyopenms_17 cimport Gradient
from ._pyopenms_17 cimport MzTabFile
from ._pyopenms_17 cimport File
from ._pyopenms_18 cimport SwathWindowLoader
from ._pyopenms_18 cimport ClusterProxyKD
from ._pyopenms_18 cimport Element
from ._pyopenms_18 cimport RangeRT
from ._pyopenms_18 cimport RangeMZ
from ._pyopenms_18 cimport RangeIntensity
from ._pyopenms_18 cimport RangeMobility
from ._pyopenms_18 cimport AbsoluteQuantitationMethod
from ._pyopenms_18 cimport MassDecomposition
from ._pyopenms_18 cimport SpectraMerger
from ._pyopenms_18 cimport ConsensusIDAlgorithmWorst
from ._pyopenms_18 cimport ParamNode
from ._pyopenms_18 cimport TransitionPQPFile
from ._pyopenms_18 cimport IonDetector
from ._pyopenms_18 cimport Peak1D
from ._pyopenms_18 cimport ContactPerson
from ._pyopenms_19 cimport BinnedSpectrum
from ._pyopenms_19 cimport RansacModelQuadratic
from ._pyopenms_19 cimport AnnotatedMSRun
from ._pyopenms_19 cimport ILPDCWrapper
from ._pyopenms_19 cimport ScanWindow
from ._pyopenms_19 cimport ProteinProteinCrossLink
from ._pyopenms_19 cimport ChromeleonFile
from ._pyopenms_19 cimport ChromatogramPeak
from ._pyopenms_19 cimport FalseDiscoveryRate
from ._pyopenms_19 cimport TMTSixteenPlexQuantitationMethod
from ._pyopenms_19 cimport ItraqEightPlexQuantitationMethod
from ._pyopenms_19 cimport MRMRTNormalizer
from ._pyopenms_19 cimport Sample
from ._pyopenms_19 cimport ModificationsDB
from ._pyopenms_20 cimport MSSpectrum
from ._pyopenms_20 cimport Acquisition
from ._pyopenms_20 cimport ExperimentalDesignFile
from ._pyopenms_20 cimport MetaInfo
from ._pyopenms_20 cimport Configuration
from ._pyopenms_20 cimport CV
from ._pyopenms_20 cimport Protein
from ._pyopenms_20 cimport RetentionTime
from ._pyopenms_20 cimport Compound
from ._pyopenms_20 cimport Peptide
from ._pyopenms_20 cimport Nuctide
from ._pyopenms_20 cimport Contact
from ._pyopenms_20 cimport Publication
from ._pyopenms_20 cimport TargetedExperiment_Instrument
from ._pyopenms_20 cimport Prediction
from ._pyopenms_20 cimport TargetedExperiment_Interpretation
from ._pyopenms_20 cimport TraMLProduct
from ._pyopenms_20 cimport TargetedExperiment_Modification
from ._pyopenms_20 cimport AASeqWithMass
from ._pyopenms_20 cimport CrossLinksDB
from ._pyopenms_20 cimport NLargest
from ._pyopenms_20 cimport MRMTransitionGroupPicker
from ._pyopenms_20 cimport ProteinHit
from ._pyopenms_20 cimport SpectrumAlignmentScore
from ._pyopenms_20 cimport TheoreticalSpectrumGenerator
from ._pyopenms_20 cimport ReactionMonitoringTransition
from ._pyopenms_20 cimport DecoyTransitionType
from ._pyopenms_20 cimport TransType
from ._pyopenms_21 cimport DTA2DFile
from ._pyopenms_21 cimport RibonucleotideDB
from ._pyopenms_21 cimport IncludeExcludeTarget
from ._pyopenms_21 cimport KDTreeFeatureMaps
from ._pyopenms_21 cimport MultiplexDeltaMassesGenerator
from ._pyopenms_21 cimport MultiplexDeltaMassesGenerator_Label
from ._pyopenms_21 cimport IsobaricChannelExtractor
from ._pyopenms_21 cimport ModificationDefinition
from ._pyopenms_21 cimport FeatureHandle
from ._pyopenms_21 cimport MzQCFile
from ._pyopenms_21 cimport KDTreeFeatureNode
from ._pyopenms_21 cimport PeptideEvidence
from ._pyopenms_21 cimport LogConfigHandler
from ._pyopenms_21 cimport PrecursorCorrection
from ._pyopenms_21 cimport DTAFile
from ._pyopenms_22 cimport ToolInfo
from ._pyopenms_22 cimport ParamCTDFile
from ._pyopenms_22 cimport MetaInfoDescription
from ._pyopenms_22 cimport IBSpectraFile
from ._pyopenms_22 cimport EmgGradientDescent
from ._pyopenms_22 cimport MapAlignmentAlgorithmKD
from ._pyopenms_22 cimport MzTabMFile
from ._pyopenms_22 cimport MetaboTargetedAssay
from ._pyopenms_22 cimport MetaboTargetedAssay_CompoundTargetDecoyPair
from ._pyopenms_22 cimport IsotopeCluster
from ._pyopenms_22 cimport ChargedIndexSet
from ._pyopenms_22 cimport MorpheusScore
from ._pyopenms_22 cimport MorpheusScore_Result
from ._pyopenms_22 cimport PercolatorInfile
from ._pyopenms_22 cimport FeatureFinderIdentificationAlgorithm
from ._pyopenms_22 cimport FeatureFileOptions
from ._pyopenms_22 cimport SiriusExportAlgorithm
from ._pyopenms_23 cimport FeatureGroupingAlgorithmKD
from ._pyopenms_23 cimport AnnotationStatistics
from ._pyopenms_23 cimport OPXL_PreprocessedPairSpectra
from ._pyopenms_23 cimport EmpiricalFormula
from ._pyopenms_23 cimport MSChromatogram
from ._pyopenms_23 cimport OpenSwathHelper
from ._pyopenms_23 cimport DecoyGenerator
from ._pyopenms_23 cimport CachedmzML
from ._pyopenms_23 cimport IsotopeLabelingMDVs
from ._pyopenms_23 cimport Kernel_MassTrace
from ._pyopenms_23 cimport MT_QUANTMETHOD
from ._pyopenms_23 cimport FeatureDistance
from ._pyopenms_23 cimport ParamEntry
from ._pyopenms_23 cimport MzXMLFile
from ._pyopenms_23 cimport PeakIntegrator
from ._pyopenms_23 cimport PI_PeakArea
from ._pyopenms_23 cimport PI_PeakBackground
from ._pyopenms_23 cimport PI_PeakShapeMetrics
from ._pyopenms_24 cimport ConsensusXMLFile
from ._pyopenms_24 cimport ConsensusFeature
from ._pyopenms_24 cimport Ratio
from ._pyopenms_24 cimport IDMapper
from ._pyopenms_24 cimport IDMapper_PeptideIdentificationListState
from ._pyopenms_24 cimport Measure
from ._pyopenms_24 cimport Adduct
from ._pyopenms_24 cimport IMSElement
from ._pyopenms_24 cimport Param
from ._pyopenms_24 cimport TraceInfo
from ._pyopenms_24 cimport GNPSQuantificationFile
from ._pyopenms_24 cimport XTandemXMLFile
from ._pyopenms_24 cimport FeatureMapping
from ._pyopenms_24 cimport FeatureMapping_FeatureMappingInfo
from ._pyopenms_24 cimport FeatureMapping_FeatureToMs2Indices
from ._pyopenms_24 cimport OpenPepXLLFAlgorithm
from ._pyopenms_24 cimport IonSource
from ._pyopenms_24 cimport Instrument
from ._pyopenms_24 cimport IonOpticsType
from ._pyopenms_24 cimport AverageLinkage
from ._pyopenms_24 cimport ChromatogramExtractorAlgorithm
from ._pyopenms_24 cimport ExtractionCoordinates
from ._pyopenms_25 cimport MzMLSqliteHandler
from ._pyopenms_25 cimport BasicProteinInferenceAlgorithm
from ._pyopenms_25 cimport MapAlignmentEvaluationAlgorithmRecall
from ._pyopenms_25 cimport Product
from ._pyopenms_25 cimport AccurateMassSearchResult
from ._pyopenms_25 cimport RankScaler
from ._pyopenms_25 cimport GNPSMGFFile
from ._pyopenms_25 cimport TheoreticalIsotopePattern
from ._pyopenms_25 cimport MassTrace
from ._pyopenms_25 cimport MassTraces
from ._pyopenms_25 cimport Seed
from ._pyopenms_25 cimport IsotopePattern
from ._pyopenms_25 cimport SourceFile
from ._pyopenms_25 cimport ChecksumType
from ._pyopenms_25 cimport InspectInfile
from ._pyopenms_25 cimport Tagger
from ._pyopenms_25 cimport PeakWidthEstimator
from ._pyopenms_25 cimport OpenPepXLAlgorithm
from ._pyopenms_25 cimport MetaboTargetedTargetDecoy
from ._pyopenms_25 cimport MetaboTargetedTargetDecoy_MetaboTargetDecoyMassMapping
from ._pyopenms_26 cimport MetaInfoInterface
from ._pyopenms_26 cimport MorphologicalFilter
from ._pyopenms_26 cimport XLPrecursor
from ._pyopenms_26 cimport EmgModel
from ._pyopenms_26 cimport MassTraceDetection
from ._pyopenms_26 cimport InterpolationModel
from ._pyopenms_26 cimport MassDecompositionAlgorithm
from ._pyopenms_26 cimport SimpleTSGXLMS
from ._pyopenms_26 cimport SimplePeak
from ._pyopenms_26 cimport BaseFeature
from ._pyopenms_26 cimport AnnotationState
from ._pyopenms_26 cimport RegularSwathFileConsumer
from ._pyopenms_26 cimport CachedSwathFileConsumer
from ._pyopenms_26 cimport MzMLSwathFileConsumer
from ._pyopenms_26 cimport GaussTraceFitter
from ._pyopenms_26 cimport Attachment
from ._pyopenms_27 cimport UniqueIdGenerator
from ._pyopenms_27 cimport ChromatogramExtractor
from ._pyopenms_27 cimport MasstraceCorrelator
from ._pyopenms_27 cimport PlainMSDataWritingConsumer
from ._pyopenms_27 cimport NoopMSDataWritingConsumer
from ._pyopenms_27 cimport MatrixDouble
from ._pyopenms_27 cimport XTandemInfile
from ._pyopenms_27 cimport TransformationModelBSpline
from ._pyopenms_27 cimport MSDataStoringConsumer
from ._pyopenms_27 cimport TransitionTSVFile
from ._pyopenms_27 cimport DIAScoring
from ._pyopenms_27 cimport QTCluster
from ._pyopenms_27 cimport TMTElevenPlexQuantitationMethod
from ._pyopenms_27 cimport SwathFile
from ._pyopenms_28 cimport IsobaricQuantifier
from ._pyopenms_28 cimport SeedListGenerator
from ._pyopenms_28 cimport ItraqConstants
from ._pyopenms_28 cimport ChannelInfo
from ._pyopenms_28 cimport ITRAQ_TYPES
from ._pyopenms_28 cimport MRMFeature
from ._pyopenms_28 cimport SignalToNoiseEstimatorMedian
from ._pyopenms_28 cimport FeatureGroupingAlgorithmLabeled
from ._pyopenms_28 cimport SiriusMSFile
from ._pyopenms_28 cimport SiriusMSFile_CompoundInfo
from ._pyopenms_28 cimport SiriusMSFile_AccessionInfo
from ._pyopenms_28 cimport DigestionEnzymeProtein
from ._pyopenms_28 cimport TransformationModelLinear
from ._pyopenms_28 cimport AbsoluteQuantitationStandardsFile
from ._pyopenms_28 cimport DBoundingBox2
from ._pyopenms_28 cimport SpectrumAccessOpenMSCached
from ._pyopenms_28 cimport FIAMSScheduler
from ._pyopenms_28 cimport MascotGenericFile
from ._pyopenms_29 cimport OSWFile
from ._pyopenms_29 cimport LinearInterpolation
from ._pyopenms_29 cimport PeptideHit
from ._pyopenms_29 cimport PeptideHit_AnalysisResult
from ._pyopenms_29 cimport PeptideHit_PeakAnnotation
from ._pyopenms_29 cimport ExperimentalDesign
from ._pyopenms_29 cimport ExperimentalDesign_MSFileSectionEntry
from ._pyopenms_29 cimport ExperimentalDesign_SampleSection
from ._pyopenms_29 cimport TransformationXMLFile
from ._pyopenms_29 cimport BSpline2d
from ._pyopenms_29 cimport BoundaryCondition
from ._pyopenms_29 cimport LinearResamplerAlign
from ._pyopenms_29 cimport RANSAC
from ._pyopenms_29 cimport RANSACQuadratic
from ._pyopenms_29 cimport RANSACParam
from ._pyopenms_29 cimport IMSIsotopeDistribution
from ._pyopenms_29 cimport IMSIsotopeDistribution_Peak
from ._pyopenms_29 cimport Software
from ._pyopenms_29 cimport MRMFeatureFinderScoring
from ._pyopenms_29 cimport MascotXMLFile
from ._pyopenms_29 cimport CVReference
from ._pyopenms_29 cimport MZTrafoModel
from ._pyopenms_29 cimport MZTrafoModel_MODELTYPE
from ._pyopenms_30 cimport DateTime
from ._pyopenms_30 cimport TextFile
from ._pyopenms_30 cimport IsotopeFitter1D
from ._pyopenms_30 cimport RNaseDigestion
from ._pyopenms_30 cimport PepXMLFileMascot
from ._pyopenms_30 cimport ConsensusIDAlgorithmBest
from ._pyopenms_30 cimport Compomer
from ._pyopenms_30 cimport SIDE
from ._pyopenms_30 cimport XMLFile
from ._pyopenms_30 cimport MetaInfoRegistry
from ._pyopenms_30 cimport AASequence
from ._pyopenms_30 cimport ElementDB
from ._pyopenms_30 cimport PosteriorErrorProbabilityModel
from ._pyopenms_30 cimport OPXLHelper
from ._pyopenms_30 cimport AAIndex
from ._pyopenms_31 cimport _Interfaces_BinaryDataArray
from ._pyopenms_31 cimport _Interfaces_Spectrum
from ._pyopenms_31 cimport _Interfaces_Chromatogram
from ._pyopenms_31 cimport QcMLFile
from ._pyopenms_31 cimport QualityParameter
from ._pyopenms_31 cimport Feature
from ._pyopenms_31 cimport SiriusFragmentAnnotation
from ._pyopenms_31 cimport SiriusFragmentAnnotation_SiriusTargetDecoySpectra
from ._pyopenms_31 cimport MRMFeatureQCFile
from ._pyopenms_31 cimport ChargePair
from ._pyopenms_31 cimport PeptideProteinResolution
from ._pyopenms_31 cimport PeptideProteinResolution_ConnectedComponent
from ._pyopenms_31 cimport MultiplexIsotopicPeakPattern
from ._pyopenms_31 cimport CVMappings
from ._pyopenms_31 cimport Date
from ._pyopenms_31 cimport SplinePackage
from ._pyopenms_31 cimport PercolatorOutfile
from ._pyopenms_31 cimport NASequence
from ._pyopenms_32 cimport DigestionEnzymeRNA
from ._pyopenms_32 cimport IdXMLFile
from ._pyopenms_32 cimport SplineInterpolatedPeaks
from ._pyopenms_32 cimport SplineSpectrum_Navigator
from ._pyopenms_32 cimport IndexedMzMLFileLoader
from ._pyopenms_32 cimport IsobaricChannelInformation
from ._pyopenms_32 cimport ChromatogramRangeManager
from ._pyopenms_32 cimport DPosition1
from ._pyopenms_32 cimport DPosition2
from ._pyopenms_32 cimport NonNegativeLeastSquaresSolver
from ._pyopenms_32 cimport ItraqFourPlexQuantitationMethod
from ._pyopenms_32 cimport ColumnHeader
from ._pyopenms_32 cimport ConsensusMap
from ._pyopenms_32 cimport FeatureGroupingAlgorithmUnlabeled
from ._pyopenms_32 cimport AbsoluteQuantitationStandards
from ._pyopenms_32 cimport AQS_runConcentration
from ._pyopenms_32 cimport AQS_featureConcentration
from ._pyopenms_32 cimport MSDataCachedConsumer
from ._pyopenms_32 cimport TraMLFile
cdef extern from "autowrap_tools.hpp":
    char * _cast_const_away(char *) 

cdef class ConsensusIDAlgorithmPEPIons:
    """
    Cython implementation of _ConsensusIDAlgorithmPEPIons

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1ConsensusIDAlgorithmPEPIons.html>`_
      -- Inherits from ['ConsensusIDAlgorithmSimilarity']
    """
    cdef shared_ptr[_ConsensusIDAlgorithmPEPIons] inst
 

cdef class MRMFeatureFilter:
    """
    Cython implementation of _MRMFeatureFilter

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1MRMFeatureFilter.html>`_
      -- Inherits from ['DefaultParamHandler']
    """
    cdef shared_ptr[_MRMFeatureFilter] inst
 

cdef class MRMIonSeries:
    """
    Cython implementation of _MRMIonSeries

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1MRMIonSeries.html>`_
    """
    cdef shared_ptr[_MRMIonSeries] inst
 

cdef class MS2File:
    """
    Cython implementation of _MS2File

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1MS2File.html>`_
      -- Inherits from ['ProgressLogger']
    """
    cdef shared_ptr[_MS2File] inst
 

cdef class OMSSACSVFile:
    """
    Cython implementation of _OMSSACSVFile

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1OMSSACSVFile.html>`_

    File adapter for OMSSACSV files
    
    The files contain the results of the OMSSA algorithm in a comma separated manner. This file adapter is able to
    load the data from such a file into the structures of OpenMS
    """
    cdef shared_ptr[_OMSSACSVFile] inst
 

cdef class OpenMSBuildInfo:
    """
    Cython implementation of _OpenMSBuildInfo

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS::Internal_1_1OpenMSBuildInfo.html>`_
    """
    cdef shared_ptr[_OpenMSBuildInfo] inst
 

cdef class OpenMSOSInfo:
    """
    Cython implementation of _OpenMSOSInfo

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS::Internal_1_1OpenMSOSInfo.html>`_
    """
    cdef shared_ptr[_OpenMSOSInfo] inst
 

cdef class PeakIndex:
    """
    Cython implementation of _PeakIndex

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1PeakIndex.html>`_

    Index of a peak or feature
    
    This struct can be used to store both peak or feature indices
    """
    cdef shared_ptr[_PeakIndex] inst
 

cdef class ProtXMLFile:
    """
    Cython implementation of _ProtXMLFile

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1ProtXMLFile.html>`_

    Used to load (storing not supported, yet) ProtXML files
    
    This class is used to load (storing not supported, yet) documents that implement
    the schema of ProtXML files
    """
    cdef shared_ptr[_ProtXMLFile] inst
 

cdef class ProteaseDB:
    """
    Cython implementation of _ProteaseDB

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1ProteaseDB.html>`_
    """
    cdef AutowrapPtrHolder[_ProteaseDB] inst
 

cdef class RansacModelLinear:
    """
    Cython implementation of _RansacModelLinear

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS::Math_1_1RansacModelLinear.html>`_
    """
    cdef shared_ptr[_RansacModelLinear] inst
 

cdef class TSE_Match:
    """
    Cython implementation of _TSE_Match

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1TSE_Match.html>`_
    """
    cdef shared_ptr[_TSE_Match] inst
 

cdef class TargetedSpectraExtractor:
    """
    Cython implementation of _TargetedSpectraExtractor

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1TargetedSpectraExtractor.html>`_
      -- Inherits from ['DefaultParamHandler']
    """
    cdef shared_ptr[_TargetedSpectraExtractor] inst
 

cdef class TransformationModelInterpolated:
    """
    Cython implementation of _TransformationModelInterpolated

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1TransformationModelInterpolated.html>`_
      -- Inherits from ['TransformationModel']
    """
    cdef shared_ptr[_TransformationModelInterpolated] inst
 

cdef class TransformationModelLowess:
    """
    Cython implementation of _TransformationModelLowess

    Original C++ documentation is available `here <http://www.openms.de/current_doxygen/html/classOpenMS_1_1TransformationModelLowess.html>`_
      -- Inherits from ['TransformationModel']
    """
    cdef shared_ptr[_TransformationModelLowess] inst
 
