if (NOT DEFINED OPERATION OR NOT DEFINED INPUT_FILE)
  message(FATAL_ERROR "OPERATION and INPUT_FILE are required")
endif()

if (OPERATION STREQUAL "prepare")
  if (NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required for prepare")
  endif()

  file(READ "${INPUT_FILE}" contents)
  set(hit_opening [=[			<PeptideHit score="0.0342" sequence="EAVPAQKERRRRGAH" charge="2" aa_before="A" aa_after="P" start="1211" end="1219" protein_refs="PH_0" >]=])
  string(FIND "${contents}" "${hit_opening}" hit_position)
  if (hit_position EQUAL -1)
    message(FATAL_ERROR "Could not find the fixture's first PeptideHit")
  endif()

  set(stamped_hit "${hit_opening}\n\t\t\t\t<UserParam type=\"float\" name=\"CalcMass\" value=\"514.125\"/>")
  string(REPLACE "${hit_opening}" "${stamped_hit}" contents "${contents}")
  file(WRITE "${OUTPUT_FILE}" "${contents}")
elseif (OPERATION STREQUAL "check")
  file(READ "${INPUT_FILE}" contents)
  string(REGEX MATCHALL "name=\"CalcMass\"" calc_mass_keys "${contents}")
  list(LENGTH calc_mass_keys calc_mass_count)
  if (NOT calc_mass_count EQUAL 1)
    message(FATAL_ERROR
      "Expected exactly the one input CalcMass in PercolatorAdapter output, found ${calc_mass_count}")
  endif()

  string(FIND "${contents}" "name=\"CalcMass\" value=\"514.125" marker_position)
  if (marker_position EQUAL -1)
    message(FATAL_ERROR "The surviving CalcMass is not the value supplied by the input")
  endif()
else()
  message(FATAL_ERROR "Unknown OPERATION: ${OPERATION}")
endif()
