# PercolatorAdapter with several -in files: each PSM's pin ScanNr must be the scan number of its
# native ID, and the pin SpecId must tell the input files apart. The adapter used to prefix the
# spectrum references with "file=<n>,", which made the extracted scan number the input file index
# and left that prefix in the output.
if (NOT DEFINED OPERATION)
  message(FATAL_ERROR "OPERATION is required")
endif()

if (OPERATION STREQUAL "prepare")
  if (NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE_1 OR NOT DEFINED OUTPUT_FILE_2)
    message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE_1 and OUTPUT_FILE_2 are required for prepare")
  endif()
  # The same search result under two file names stands in for two runs.
  file(READ "${INPUT_FILE}" contents)
  file(WRITE "${OUTPUT_FILE_1}" "${contents}")
  file(WRITE "${OUTPUT_FILE_2}" "${contents}")
elseif (OPERATION STREQUAL "check")
  if (NOT DEFINED PIN_FILE OR NOT DEFINED ID_FILE OR NOT DEFINED INPUT_NAME_1 OR NOT DEFINED INPUT_NAME_2)
    message(FATAL_ERROR "PIN_FILE, ID_FILE, INPUT_NAME_1 and INPUT_NAME_2 are required for check")
  endif()

  file(STRINGS "${PIN_FILE}" pin_lines)
  list(POP_FRONT pin_lines header)
  if (NOT header MATCHES "^SpecId\tLabel\tScanNr\t")
    message(FATAL_ERROR "Unexpected pin header: ${header}")
  endif()

  set(psms_1 0)
  set(psms_2 0)
  foreach (line IN LISTS pin_lines)
    if (NOT line MATCHES "^([^\t]*)\t[^\t]*\t([^\t]*)\t")
      message(FATAL_ERROR "Unexpected pin line: ${line}")
    endif()
    set(spec_id "${CMAKE_MATCH_1}")
    set(scan_nr "${CMAKE_MATCH_2}")
    if (NOT spec_id MATCHES "scan=([0-9]+)$")
      message(FATAL_ERROR "SpecId without a scan number: ${spec_id}")
    endif()
    if (NOT scan_nr EQUAL CMAKE_MATCH_1)
      message(FATAL_ERROR "ScanNr ${scan_nr} is not the scan number of SpecId ${spec_id}")
    endif()
    string(FIND "${spec_id}" "${INPUT_NAME_1}" position_1)
    string(FIND "${spec_id}" "${INPUT_NAME_2}" position_2)
    if (position_1 EQUAL 0)
      math(EXPR psms_1 "${psms_1} + 1")
    elseif (position_2 EQUAL 0)
      math(EXPR psms_2 "${psms_2} + 1")
    else()
      message(FATAL_ERROR "SpecId does not name its input file: ${spec_id}")
    endif()
  endforeach()
  if (psms_1 EQUAL 0 OR NOT psms_1 EQUAL psms_2)
    message(FATAL_ERROR "Expected the same number of PSMs from both inputs, found ${psms_1} and ${psms_2}")
  endif()

  file(READ "${ID_FILE}" contents)
  string(FIND "${contents}" "spectrum_reference=\"file=" prefixed_reference)
  if (NOT prefixed_reference EQUAL -1)
    message(FATAL_ERROR "The output spectrum references carry the adapter's file prefix")
  endif()
else()
  message(FATAL_ERROR "Unknown OPERATION: ${OPERATION}")
endif()
