# PercolatorAdapter with several -in files: each PSM's pin ScanNr must be the scan number of its
# native ID, and the pin SpecId and FileName must tell the input files apart. The adapter used to
# prefix the spectrum references with "file=<n>,", which made the extracted scan number the input
# file index and left that prefix in the output.
#
# OPERATION check_tdc: Percolator identifies a spectrum by spectrum file, scan number and precursor
# m/z. Both inputs are the same search, so with target-decoy competition (-post_processing_tdc)
# each of them must keep one PSM per spectrum of the input (INPUT_FILE). If the inputs shared a
# spectrum file, the spectra with the same scan number and m/z would compete across the inputs, and
# the two inputs together would keep only that many.
if (NOT DEFINED OPERATION)
  message(FATAL_ERROR "OPERATION is required")
endif()

# The lines of an idXML file as a list. Square brackets (aa_before="[") and semicolons would break up a CMake
# list, so they are replaced first.
function(read_xml_lines path result)
  file(READ "${path}" contents)
  string(REPLACE "[" "(" contents "${contents}")
  string(REPLACE "]" ")" contents "${contents}")
  string(REPLACE ";" "," contents "${contents}")
  string(REPLACE "\n" ";" contents "${contents}")
  set(${result} "${contents}" PARENT_SCOPE)
endfunction()

if (OPERATION STREQUAL "prepare")
  if (NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE_1 OR NOT DEFINED OUTPUT_FILE_2)
    message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE_1 and OUTPUT_FILE_2 are required for prepare")
  endif()
  # The same search result under two file names stands in for two runs.
  file(READ "${INPUT_FILE}" contents)
  file(WRITE "${OUTPUT_FILE_1}" "${contents}")
  file(WRITE "${OUTPUT_FILE_2}" "${contents}")
elseif (OPERATION STREQUAL "check")
  if (NOT DEFINED PIN_FILE OR NOT DEFINED ID_FILE OR NOT DEFINED INPUT_NAME_1 OR NOT DEFINED INPUT_NAME_2)
    message(FATAL_ERROR "PIN_FILE, ID_FILE, INPUT_NAME_1 and INPUT_NAME_2 are required for check")
  endif()

  file(STRINGS "${PIN_FILE}" pin_lines)
  list(POP_FRONT pin_lines header)
  # Percolator reads the optional FileName column only among the optional columns before the features
  if (NOT header MATCHES "^SpecId\tLabel\tScanNr\tExpMass\tCalcMass\tFileName\t")
    message(FATAL_ERROR "Unexpected pin header: ${header}")
  endif()

  set(psms_1 0)
  set(psms_2 0)
  foreach (line IN LISTS pin_lines)
    if (NOT line MATCHES "^([^\t]*)\t[^\t]*\t([^\t]*)\t[^\t]*\t[^\t]*\t([^\t]*)\t")
      message(FATAL_ERROR "Unexpected pin line: ${line}")
    endif()
    set(spec_id "${CMAKE_MATCH_1}")
    set(scan_nr "${CMAKE_MATCH_2}")
    set(file_name "${CMAKE_MATCH_3}")
    string(FIND "${spec_id}" "${file_name}" file_position)
    if (NOT file_name OR NOT file_position EQUAL 0)
      message(FATAL_ERROR "FileName ${file_name} is not the input file of SpecId ${spec_id}")
    endif()
    if (NOT spec_id MATCHES "scan=([0-9]+)$")
      message(FATAL_ERROR "SpecId without a scan number: ${spec_id}")
    endif()
    if (NOT scan_nr EQUAL CMAKE_MATCH_1)
      message(FATAL_ERROR "ScanNr ${scan_nr} is not the scan number of SpecId ${spec_id}")
    endif()
    string(FIND "${spec_id}" "${INPUT_NAME_1}" position_1)
    string(FIND "${spec_id}" "${INPUT_NAME_2}" position_2)
    if (position_1 EQUAL 0)
      math(EXPR psms_1 "${psms_1} + 1")
    elseif (position_2 EQUAL 0)
      math(EXPR psms_2 "${psms_2} + 1")
    else()
      message(FATAL_ERROR "SpecId does not name its input file: ${spec_id}")
    endif()
  endforeach()
  if (psms_1 EQUAL 0 OR NOT psms_1 EQUAL psms_2)
    message(FATAL_ERROR "Expected the same number of PSMs from both inputs, found ${psms_1} and ${psms_2}")
  endif()

  file(READ "${ID_FILE}" contents)
  string(FIND "${contents}" "spectrum_reference=\"file=" prefixed_reference)
  if (NOT prefixed_reference EQUAL -1)
    message(FATAL_ERROR "The output spectrum references carry the adapter's file prefix")
  endif()
elseif (OPERATION STREQUAL "check_tdc")
  if (NOT DEFINED INPUT_FILE OR NOT DEFINED ID_FILE OR NOT DEFINED INPUT_NAME_1 OR NOT DEFINED INPUT_NAME_2)
    message(FATAL_ERROR "INPUT_FILE, ID_FILE, INPUT_NAME_1 and INPUT_NAME_2 are required for check_tdc")
  endif()

  # the spectra of the input: distinct scan numbers and precursor m/z of identifications with hits
  read_xml_lines("${INPUT_FILE}" input_lines)
  set(spectra "")
  set(spectrum "")
  foreach (line IN LISTS input_lines)
    if (line MATCHES "<PeptideIdentification ")
      if (NOT line MATCHES "MZ=\"([^\"]*)\"")
        message(FATAL_ERROR "Identification without precursor m/z: ${line}")
      endif()
      set(mz "${CMAKE_MATCH_1}")
      if (NOT line MATCHES "spectrum_reference=\"[^\"]*scan=([0-9]+)")
        message(FATAL_ERROR "Identification without scan number: ${line}")
      endif()
      set(spectrum "${CMAKE_MATCH_1}/${mz}")
    elseif (line MATCHES "<PeptideHit " AND spectrum)
      list(APPEND spectra "${spectrum}")
      set(spectrum "")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES spectra)
  list(LENGTH spectra expected)

  # PSMs that took part in the competition and won it. Percolator does not report the losers, which the adapter
  # marks with q-value and PEP 1 and an SVM score of 0 (in-process) or -100 (executable).
  read_xml_lines("${ID_FILE}" output_lines)
  set(winners_1 0)
  set(winners_2 0)
  foreach (line IN LISTS output_lines)
    if (line MATCHES "<PeptideIdentification ")
      set(winners 0)
      set(origin "")
    elseif (line MATCHES "<PeptideHit ")
      set(svm "")
      set(q_value "")
      set(pep "")
    elseif (line MATCHES "name=\"MS:1001492\" value=\"([^\"]*)\"")
      set(svm "${CMAKE_MATCH_1}")
    elseif (line MATCHES "name=\"MS:1001491\" value=\"([^\"]*)\"")
      set(q_value "${CMAKE_MATCH_1}")
    elseif (line MATCHES "name=\"MS:1001493\" value=\"([^\"]*)\"")
      set(pep "${CMAKE_MATCH_1}")
    elseif (line MATCHES "</PeptideHit>")
      if (NOT svm STREQUAL "" AND NOT (q_value EQUAL 1 AND pep EQUAL 1 AND (svm EQUAL 0 OR svm EQUAL -100)))
        math(EXPR winners "${winners} + 1")
      endif()
    elseif (line MATCHES "name=\"file_origin\" value=\"([^\"]*)\"")
      set(origin "${CMAKE_MATCH_1}")
    elseif (line MATCHES "</PeptideIdentification>")
      if (origin STREQUAL INPUT_NAME_1)
        math(EXPR winners_1 "${winners_1} + ${winners}")
      elseif (origin STREQUAL INPUT_NAME_2)
        math(EXPR winners_2 "${winners_2} + ${winners}")
      else()
        message(FATAL_ERROR "Identification from an unknown input: '${origin}'")
      endif()
    endif()
  endforeach()
  if (expected EQUAL 0 OR NOT winners_1 EQUAL expected OR NOT winners_2 EQUAL expected)
    message(FATAL_ERROR "Expected ${expected} PSMs after target-decoy competition from each input, found ${winners_1} and ${winners_2}")
  endif()
else()
  message(FATAL_ERROR "Unknown OPERATION: ${OPERATION}")
endif()
