MzMLFile$$set("public","transform",function(...){
    .arg <- list(...)
    if( length(.arg)==2){
        if(!(is_scalar_character(.arg[[1]]) || is.R6(.arg[[1]]) && class(.arg[[1]])[1]=="String")) stop("arg1 path wrong type")
        if(!is.R6(.arg[[2]])) stop("arg2 transformer wrong type")
        arg2 <- r_to_py(.arg[[2]])
        if(!py_has_attr(arg2,"consumeSpectrum")) stop("expected method consumeSpectrum in arg2 transformer")
        if(!py_has_attr(arg2,"consumeChromatogram")) stop("expected method consumeChromatogram in arg2 transformer")
        if(!py_has_attr(arg2,"setExpectedSize")) stop("expected method setExpectedSize in arg2 transformer")
        if(!py_has_attr(arg2,"setExperimentalSettings")) stop("expected method setExperimentalSettings in arg2 transformer")
        private$py_obj$transform(r_to_py(.arg[[1]]),arg2)
        invisible()
    } else if (length(.arg)==3) {
        if(!(is_scalar_character(.arg[[1]]) || is.R6(.arg[[1]]) && class(.arg[[1]])[1]=="String")) stop("arg1 path wrong type")
        if(!( is.R6(.arg[[3]]) && class(.arg[[3]])[1]=="MSExperiment" )) stop("arg3 exp wrong type")
        if(!(is_scalar_character(.arg[[1]]) || is.R6(.arg[[1]]) && class(.arg[[2]])[1]=="String")) stop("arg1 path wrong type")
        if(!is.R6(.arg[[2]])) stop("arg2 transformer wrong type")
        arg2 <- r_to_py(.arg[[2]])
        if(!py_has_attr(arg2,"consumeSpectrum")) stop("expected method consumeSpectrum in arg2 transformer")
        if(!py_has_attr(arg2,"consumeChromatogram")) stop("expected method consumeChromatogram in arg2 transformer")
        if(!py_has_attr(arg2,"setExpectedSize")) stop("expected method setExpectedSize in arg2 transformer")
        if(!py_has_attr(arg2,"setExperimentalSettings")) stop("expected method setExperimentalSettings in arg2 transformer")
        private$py_obj$transform(r_to_py(.arg[[1]]),arg2,r_to_py(.arg[[3]]))
        invisible()
    } else if (length(.arg)==4) {
        if(!(is_scalar_character(.arg[[1]]) || is.R6(.arg[[1]]) && class(.arg[[1]])[1]=="String")) stop("arg1 path wrong type")
        if(!is.R6(.arg[[2]])) stop("arg2 transformer wrong type")
        arg2 <- r_to_py(.arg[[2]])
        if(!py_has_attr(arg2,"consumeSpectrum")) stop("expected method consumeSpectrum in arg2 transformer")
        if(!py_has_attr(arg2,"consumeChromatogram")) stop("expected method consumeChromatogram in arg2 transformer")
        if(!py_has_attr(arg2,"setExpectedSize")) stop("expected method setExpectedSize in arg2 transformer")
        if(!py_has_attr(arg2,"setExperimentalSettings")) stop("expected method setExperimentalSettings in arg2 transformer")
        if(isFALSE(all.equal(.arg[[3]],as.integer(.arg[[3]])))) stop("arg3 skip_full_count must be integer")
        if(isFALSE(all.equal(.arg[[4]],as.integer(.arg[[4]])))) stop("arg4 skip_first_pass must be integer")
        private$py_obj$transform(r_to_py(.arg[[1]]),arg2,as.integer(.arg[[3]]),as.integer(.arg[[4]]))
        invisible()       
    } else if (length(.arg)=5) {
        if(!( is.R6(.arg[[3]]) && class(.arg[[3]])[1]=="MSExperiment" )) stop("arg3 exp wrong type")
        if(!(is_scalar_character(.arg[[1]]) || is.R6(.arg[[1]]) && class(.arg[[1]])[1]=="String")) stop("arg1 path wrong type")
        if(!is.R6(.arg[[2]])) stop("arg2 transformer wrong type")
        arg2 <- r_to_py(.arg[[2]])
        if(!py_has_attr(arg2,"consumeSpectrum")) stop("expected method consumeSpectrum in arg2 transformer")
        if(!py_has_attr(arg2,"consumeChromatogram")) stop("expected method consumeChromatogram in arg2 transformer")
        if(!py_has_attr(arg2,"setExpectedSize")) stop("expected method setExpectedSize in arg2 transformer")
        if(!py_has_attr(arg2,"setExperimentalSettings")) stop("expected method setExperimentalSettings in arg2 transformer")
        if(isFALSE(all.equal(.arg[[4]],as.integer(.arg[[4]])))) stop("arg4 skip_full_count must be integer")
        if(isFALSE(all.equal(.arg[[5]],as.integer(.arg[[5]])))) stop("arg5 skip_first_pass must be integer")
        private$py_obj$transform(r_to_py(.arg[[1]]),arg2,r_to_py(.arg[[3]]),as.integer(.arg[[4]]),as.integer(.arg[[5]]))
        invisible()
    } else {
       stop("wrong number of arguments provided")
    }
})