language: c

os:
- linux
- osx

compiler:
  - gcc
  - clang

before_install: ./travis-before-install.sh

install: sudo apt-get install libhdf5-serial-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build . --config Release
  - ctest
