#!/bin/sh
# -*- Mode: make; tab-width: 2; -*-
# vi: set ts=2:
#
# --------------------------------------------------------------------------
#                   OpenMS Mass Spectrometry Framework
# --------------------------------------------------------------------------
#  Copyright (C) 2003-2008 -- Oliver Kohlbacher, Knut Reinert
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# --------------------------------------------------------------------------
# $Maintainer: Marc Sturm $
# --------------------------------------------------------------------------

# try to figure out which syntax we need
# to prevent a linefeed at the end of echo
# Some versions of sh use -n as an option
# others use \c at the end of the line.
# This is just for cosmetic reasons...
A=`echo "\c"|grep c`
if test "$A" != "" ; then 
	A=`echo -n "k"|grep n` 
	if test "$A" = "" ; then 
		ECHO="echo -n "
		SUFFIX=""
	else 
		ECHO="echo"
		SUFFIX=""
	fi 
else  
	ECHO="echo"
	SUFFIX="\c"
fi

if test "${1}" = "-section" ; then
	SECTION=${2}
	shift 2
	echo " "
	echo "Executing tests for section ${SECTION}:"
fi


#
# if -continue is given (after -section XX !)
# the test does not abort after the first section 
# containing failing tests
#
if test "${1}" = "-continue" ; then
	ABORT_ON_FAIL=0
	shift
else
	ABORT_ON_FAIL=1
fi

if test "${1}" = "-info" ; then
	echo " "
	echo "Now running all class tests."
	echo " "
	echo "This test suite verifies that all classes included in the test"
	echo "could be correctly compiled and checks their basic functionality."
	echo "If problems occur for one of these tests, you might want to run"
	echo "this test program manually. Any failing test will be rerun with"
	echo "verbose output to identify the subtest that caused the problem."
	echo "You may run each test manually in the verbose mode by specifying -v"
	echo "on the command line."
	echo "Running these tests may take some time...."
	echo " "
	exit 0
fi

if test "${1}" = "-success" ; then
	echo " "
	echo "====================================================="
	echo "All tests passed. Congratulations!"
	echo " "
	exit 0
fi

# remember any failed tests by setting OK=false
OK=true

# remove any core in the directory and all backtrace files
rm core *.backtrace 2>/dev/null


# loop over all tests
COUNT=1
for i in $* ; do
	# print the name of the test running
	$ECHO "`if [ ${COUNT} -le 9 ] ; then echo ' '; fi;`  (${COUNT})	$i: $SUFFIX"
	
	# remove potential log files
	rm $i.log 2>/dev/null

	# run it
	./$i > $i.output 2>&1
	
	# ... and examine its return value
	RETVAL=`echo $?`
	if test "$RETVAL" = "0"; then
		# test passed - OK
		echo "OK"
	elif test "$RETVAL" = "24" -o "$RETVAL" = "152"; then
		# test timed out (SIGXCPU signal ~ 24 (MinGW) ~ 128+24=152 (Linux) )
		echo "warning: TIMEOUT: "$i	
	else 
		# test didn't pass
		OK=false
			
		# if backtracing suport is configured, try a stack backtrace
		if test "${OPENMS_BACKTRACE}" != "" -a -f core ; then
			${OPENMS_BACKTRACE} $i
			rm core 2>/dev/null
		fi
	
		# remember this test
		FAILED_TESTS="${FAILED_TESTS} $i"

		# rerun it in verbose mode to find out which
		# subtest failed
		echo "FAILED"
		echo "--------------------------------------------"
		echo "Please check the log file: \"$i.log\"."
		echo "--------------------------------------------"
		echo "The failed lines are:"
		echo "# BEGIN failed lines"
		( ./$i -V 2>&1 |cat > $i.log ) 2>/dev/null
		grep " - $" $i.log
		echo "#  END  failed lines"
		echo "--------------------------------------------"
		echo "The last three lines are:"
		echo "# BEGIN last three lines"
		tail -3 $i.log
		echo "#  END  last three lines"
		echo "--------------------------------------------"
		if test -f core ; then
			rm core
		fi
	fi
	COUNT=`expr ${COUNT} + 1`
done
# print a line before next compilation starts
echo

# print some summary for failed tests
if test "$OK" = true ; then
	exit 0
else
	echo "============================================"
	echo " "
	echo "The following subtests failed:"

	for i in ${FAILED_TESTS} ; do 
		echo " - $i "
	done

	echo " "
	echo "Please mail the output of this run to one of the developers"
	echo "and include a detailed description of the system you use."
	echo "It is also neccessary to include the files ../config.mak ../config.h"
	echo " "

	exit ${ABORT_ON_FAIL}
fi
