from Types cimport *
from OpenSwathDataStructures cimport *
from MSSpectrum cimport *
from MSChromatogram cimport *
from MSExperiment cimport *
from ISpectrumAccess cimport *

from SpectrumAccessOpenMS cimport *
from SpectrumAccessOpenMSCached cimport *
from SpectrumAccessQuadMZTransforming cimport *

cdef extern from "<OpenMS/ANALYSIS/OPENSWATH/DATAACCESS/SpectrumAccessOpenMSInMemory.h>" namespace "OpenMS":
    
    cdef cppclass SpectrumAccessOpenMSInMemory(ISpectrumAccess) :
        # wrap-doc:
        #  An implementation of the OpenSWATH Spectrum Access interface
        #  completely in memory * * This implementation of the spectrum access
        #  interface ensures that all data * is held completely in memory and is
        #  quickly accessible. This class can be * generated by passing any
        #  object implementing the Spectrum Access interface * and guarantees to
        #  provide the same access to the raw data as the original * object with
        #  the added benefits (and downside) of keeping all data in system *
        #  memory. * * A possible example * * @code * OpenSwath::ISpectrumAccess
        #  * data_access; * fillData(data_access); // assume that data_access
        #  points to some data * OpenSwath::ISpectrumAccess *
        #  in_memory_data_access = SpectrumAccessOpenMSInMemory(data_access); *
        #  @endcode * * After executing this code, two variables exist:
        #  data_access which provides * access to the original data but does so
        #  in one of multiple ways which is * not transparent to the user.
        #  However, in_memory_data_access will provide * access to the same data
        #  but with the guarantee that the data is available * in memory and not
        #  read from the disk. *
        # wrap-inherits:
        #  ISpectrumAccess

        SpectrumAccessOpenMSInMemory() # wrap-pass-constructor

        # 'ISpectrumAccess' is not a type identifier
        SpectrumAccessOpenMSInMemory(ISpectrumAccess &) except + nogil  # wrap-ignore
        SpectrumAccessOpenMSInMemory(SpectrumAccessOpenMS &) except + nogil 
        SpectrumAccessOpenMSInMemory(SpectrumAccessOpenMSCached &) except + nogil 
        SpectrumAccessOpenMSInMemory(SpectrumAccessOpenMSInMemory &) except + nogil 
        SpectrumAccessOpenMSInMemory(SpectrumAccessQuadMZTransforming &) except + nogil 
