#!/bin/bash

# Usage example:
# cd OpenMS/source; make depend; dependencies-strip; make lib; (...etc...)


# Now "make" will traverse the directories much faster,
# because it doesn't look at many files that are not going to change anyway.
# E.g. the remaining dependencies are about 27% of original in source/TEST.


# This "sed" script does the following:
# 1. replace all files in /usr (system files) or from the contrib package by whitespace
# and after that,
# 2. delete all lines that contain only whitespace until a "\" at the very end

# Use this to remove both /usr and contrib dependencies:
echo "Stripping \"/usr/...\" and \".../contrib.../...\"  files from .Dependencies ..."
find . -name .Dependencies | xargs sed -i 's:[^ \]*/contrib[^/]*/[^ \]*::g; s:/usr/[^ \]*::g; /^[    ]*\\$/ D'

# Use this to keep contrib dependencies:
# echo "Stripping \"/usr/...\" files from .Dependencies ..."
# find . -name .Dependencies | xargs sed -i 's:/usr/[^ \]*::g; /^[    ]*\\$/ D'

echo "...done."


