// -*- mode: C++; tab-width: 2; -*-
// vi: set ts=2:
//
// --------------------------------------------------------------------------
//                   OpenMS Mass Spectrometry Framework 
// --------------------------------------------------------------------------
//  Copyright (C) 2003-2010 -- Oliver Kohlbacher, Knut Reinert
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --------------------------------------------------------------------------
// $Maintainer: Clemens Groepl, Chris Bielow $
// $Authors: $
// --------------------------------------------------------------------------
#include <OpenMS/CONCEPT/VersionInfo.h>
#include <OpenMS/DATASTRUCTURES/String.h>

#include <cstdlib>
#include <fstream>


// these headers are generated by the build system
// and therefore intentionally break the naming convention (tagging them as automatically build)
#include <OpenMS/openms_package_version.h>
#include <OpenMS/openms_svn_revision.h>

using namespace std;

namespace OpenMS
{
	

	String VersionInfo::getTime()
	{
		static bool is_initialized = false;
		static String result;
		if ( !is_initialized )
		{
			result = String(__DATE__) + ", " + __TIME__;
			is_initialized = true;
		}
		return result;
	}

	String VersionInfo::getVersion()
	{
		static bool is_initialized = false;
		static String result;
		if ( !is_initialized )
		{
			result = OPENMS_PACKAGE_VERSION;
			result.trim();
			is_initialized = true;
		}
		return result;
	}

	Int VersionInfo::getMajorVersion()
	{
		static Int major = -1;
		if (major < 0)
		{
			const String version = getVersion();
			size_t first_dot = version.find('.');
			major = atoi(version.substr(0,first_dot).c_str());
		}
		return major;
	}
	
	Int VersionInfo::getMinorVersion()
	{
		static Int minor = -1;
		if (minor < 0)
		{
			const String version = getVersion();
			size_t first_dot = version.find('.');
			size_t second_dot = version.find('.', first_dot + 1);
			if ( second_dot > 1000 ) second_dot = 1000; // avoid arithmetic overflow if there is no second dot
			minor = atoi(version.substr(first_dot+1,second_dot-first_dot+1).c_str());
		}
		return minor;
	}

	String VersionInfo::getRevision()
	{
		static bool is_initialized = false;
		static String result;
		if ( !is_initialized )
		{
			result = String(OPENMS_SVN_REVISION); // defined in svn_revision.h
			is_initialized = true;
		}
		return result;
	}

}
