# CMake generated Testfile for 
# Source directory: /workspaces/OpenMS/doc/code_examples
# Build directory: /workspaces/OpenMS/doc/code_examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Tutorial_AASequence "/workspaces/OpenMS/bin/Tutorial_AASequence")
set_tests_properties(Tutorial_AASequence PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Clustering "/workspaces/OpenMS/bin/Tutorial_Clustering")
set_tests_properties(Tutorial_Clustering PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_DPosition "/workspaces/OpenMS/bin/Tutorial_DPosition")
set_tests_properties(Tutorial_DPosition PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_DRange "/workspaces/OpenMS/bin/Tutorial_DRange")
set_tests_properties(Tutorial_DRange PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Element "/workspaces/OpenMS/bin/Tutorial_Element")
set_tests_properties(Tutorial_Element PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_EmpiricalFormula "/workspaces/OpenMS/bin/Tutorial_EmpiricalFormula")
set_tests_properties(Tutorial_EmpiricalFormula PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Enzyme "/workspaces/OpenMS/bin/Tutorial_Enzyme")
set_tests_properties(Tutorial_Enzyme PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_FeatureFinder "/workspaces/OpenMS/bin/Tutorial_FeatureFinder")
set_tests_properties(Tutorial_FeatureFinder PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_FeatureMap "/workspaces/OpenMS/bin/Tutorial_FeatureMap")
set_tests_properties(Tutorial_FeatureMap PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_FileIO "/workspaces/OpenMS/bin/Tutorial_FileIO")
set_tests_properties(Tutorial_FileIO PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_FileIO_Consumer "/workspaces/OpenMS/bin/Tutorial_FileIO_Consumer")
set_tests_properties(Tutorial_FileIO_Consumer PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_FileIO_mzML "/workspaces/OpenMS/bin/Tutorial_FileIO_mzML")
set_tests_properties(Tutorial_FileIO_mzML PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_GaussFilter "/workspaces/OpenMS/bin/Tutorial_GaussFilter")
set_tests_properties(Tutorial_GaussFilter PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_IdentificationClasses "/workspaces/OpenMS/bin/Tutorial_IdentificationClasses")
set_tests_properties(Tutorial_IdentificationClasses PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Labeled "/workspaces/OpenMS/bin/Tutorial_Labeled")
set_tests_properties(Tutorial_Labeled PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Logger "/workspaces/OpenMS/bin/Tutorial_Logger")
set_tests_properties(Tutorial_Logger PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_MapAlignment "/workspaces/OpenMS/bin/Tutorial_MapAlignment")
set_tests_properties(Tutorial_MapAlignment PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_MetaInfo "/workspaces/OpenMS/bin/Tutorial_MetaInfo")
set_tests_properties(Tutorial_MetaInfo PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_MorphologicalFilter "/workspaces/OpenMS/bin/Tutorial_MorphologicalFilter")
set_tests_properties(Tutorial_MorphologicalFilter PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_MSChromatogram "/workspaces/OpenMS/bin/Tutorial_MSChromatogram")
set_tests_properties(Tutorial_MSChromatogram PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_MSExperiment "/workspaces/OpenMS/bin/Tutorial_MSExperiment")
set_tests_properties(Tutorial_MSExperiment PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_MSSpectrum "/workspaces/OpenMS/bin/Tutorial_MSSpectrum")
set_tests_properties(Tutorial_MSSpectrum PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Param "/workspaces/OpenMS/bin/Tutorial_Param")
set_tests_properties(Tutorial_Param PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Precursor "/workspaces/OpenMS/bin/Tutorial_Precursor")
set_tests_properties(Tutorial_Precursor PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_RangeManager "/workspaces/OpenMS/bin/Tutorial_RangeManager")
set_tests_properties(Tutorial_RangeManager PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Residue "/workspaces/OpenMS/bin/Tutorial_Residue")
set_tests_properties(Tutorial_Residue PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_ResidueModification "/workspaces/OpenMS/bin/Tutorial_ResidueModification")
set_tests_properties(Tutorial_ResidueModification PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_SavitzkyGolayFilter "/workspaces/OpenMS/bin/Tutorial_SavitzkyGolayFilter")
set_tests_properties(Tutorial_SavitzkyGolayFilter PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Template "/workspaces/OpenMS/bin/Tutorial_Template")
set_tests_properties(Tutorial_Template PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_TheoreticalSpectrumGenerator "/workspaces/OpenMS/bin/Tutorial_TheoreticalSpectrumGenerator")
set_tests_properties(Tutorial_TheoreticalSpectrumGenerator PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_TOPP "/workspaces/OpenMS/bin/Tutorial_TOPP")
set_tests_properties(Tutorial_TOPP PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
add_test(Tutorial_Unlabeled "/workspaces/OpenMS/bin/Tutorial_Unlabeled")
set_tests_properties(Tutorial_Unlabeled PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;56;add_test;/workspaces/OpenMS/doc/code_examples/CMakeLists.txt;0;")
