# Install script for directory: /workspaces/OpenMS/src/openms_gui

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/opt/rh/gcc-toolset-14/root/usr/bin/objdump")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "library" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libOpenMS_GUI.so" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libOpenMS_GUI.so")
    file(RPATH_CHECK
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libOpenMS_GUI.so"
         RPATH "\$ORIGIN/../lib/")
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "/workspaces/OpenMS/lib/libOpenMS_GUI.so")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libOpenMS_GUI.so" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libOpenMS_GUI.so")
    file(RPATH_CHANGE
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libOpenMS_GUI.so"
         OLD_RPATH "/workspaces/OpenMS/lib:"
         NEW_RPATH "\$ORIGIN/../lib/")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/rh/gcc-toolset-14/root/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libOpenMS_GUI.so")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "library" OR NOT CMAKE_INSTALL_COMPONENT)
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/ANNOTATION" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DDistanceItem.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/ANNOTATION" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DItem.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/ANNOTATION" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DPeakItem.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/ANNOTATION" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DCaret.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/ANNOTATION" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DTextItem.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/ANNOTATION" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/ANNOTATION" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotations1DContainer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/APPLICATIONS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/FLASHDeconvWizardBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/APPLICATIONS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/INIFileEditorWindow.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/APPLICATIONS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/SwathWizardBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/APPLICATIONS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/APPLICATIONS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/INTERFACES" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/INTERFACES/IPeptideIds.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/MISC" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/MISC/CommonDefs.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/MISC" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/MISC/ExternalProcessMBox.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/MISC" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/MISC/FilterableList.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/MISC" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/MISC/GUIHelpers.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISITORS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISITORS/LayerStatistics.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISITORS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISITORS/LayerStoreData.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/APPLICATIONS/MISC" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/MISC/QApplicationTOPP.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/AxisTickCalculator.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/AxisPainter.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/AxisWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ColorSelector.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DataSelectionTabs.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIATreeTab.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/EnhancedTabBar.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/EnhancedTabBarWidgetInterface.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/EnhancedWorkspace.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/FilterList.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/GUIProgressLoggerImpl.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/HistogramWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/InputFile.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/InputFileList.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerListView.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerData1DBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerData1DChrom.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerData1DIonMobility.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerDataBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerDataChrom.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerDataConsensus.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerDataFeature.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerDataIdent.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerData1DPeak.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerDataPeak.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ListEditor.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LogWindow.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/MetaDataBrowser.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/MultiGradient.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/MultiGradientSelector.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/OutputDirectory.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Painter1DBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Painter2DBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/PainterBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/ParamEditor.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Plot1DCanvas.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Plot1DWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Plot2DCanvas.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Plot2DWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Plot3DCanvas.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Plot3DOpenGLCanvas.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Plot3DWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/PlotCanvas.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/PlotWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/RecentFilesMenu.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/SequenceVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/SpectraTreeTab.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/SpectraIDViewTab.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/SwathLibraryStats.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TableView.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASEdge.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASInputFileListVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASMergerVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASOutputVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASOutputFileListVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASOutputFolderVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASResource.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASResources.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASScene.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASSplitterVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASToolVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASTreeView.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASVertex.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPASWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TOPPViewMenu.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TreeView.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TVControllerBase.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TVDIATreeTabController.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TVIdentificationViewController.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TVSpectraViewController.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/TVToolDiscovery.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/DataFilterDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/FeatureEditDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/FLASHDeconvTabWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/HistogramDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/LayerStatisticsDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/ListFilterDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/PythonModuleRequirement.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/PythonSelector.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/SaveImageDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/Plot1DGoToDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/Plot1DPrefDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/Plot2DGoToDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/Plot2DPrefDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/Plot3DPrefDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/SpectrumAlignmentDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/SwathTabWidget.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASIOMappingDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASInputFileDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASInputFilesDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASOutputFilesDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASToolConfigDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASVertexNameDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPViewOpenDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPViewPrefDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TheoreticalSpectrumGenerationDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/ToolsDialog.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/DIALOGS" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/DIALOGS/WizardHelper.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/AcquisitionInfoVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/AcquisitionVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/BaseVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/BaseVisualizerGUI.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/ContactPersonVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/DataProcessingVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/DocumentIdentifierVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/ExperimentalSettingsVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/GradientVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/HPLCVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/InstrumentSettingsVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/InstrumentVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/IonDetectorVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/IonSourceVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/MassAnalyzerVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/MetaInfoDescriptionVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/MetaInfoVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/PeptideHitVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/PeptideIdentificationVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/PrecursorVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/ProteinHitVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/ProteinIdentificationVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/SampleVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/ScanWindowVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/SoftwareVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/SourceFileVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/SpectrumSettingsVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL/VISUALIZER" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/VISUALIZER/ProductVisualizer.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "OpenMS_GUI_headers" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/OpenMS/VISUAL" TYPE FILE FILES "/workspaces/OpenMS/src/openms_gui/include/OpenMS/VISUAL/OpenMS_GUIConfig.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Applications" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/FLASHDeconvWizard" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/FLASHDeconvWizard")
    file(RPATH_CHECK
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/FLASHDeconvWizard"
         RPATH "$ORIGIN/../lib/")
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "/workspaces/OpenMS/bin/FLASHDeconvWizard")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/FLASHDeconvWizard" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/FLASHDeconvWizard")
    file(RPATH_CHANGE
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/FLASHDeconvWizard"
         OLD_RPATH "/workspaces/OpenMS/lib:"
         NEW_RPATH "$ORIGIN/../lib/")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/rh/gcc-toolset-14/root/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/FLASHDeconvWizard")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Applications" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/INIFileEditor" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/INIFileEditor")
    file(RPATH_CHECK
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/INIFileEditor"
         RPATH "$ORIGIN/../lib/")
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "/workspaces/OpenMS/bin/INIFileEditor")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/INIFileEditor" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/INIFileEditor")
    file(RPATH_CHANGE
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/INIFileEditor"
         OLD_RPATH "/workspaces/OpenMS/lib:"
         NEW_RPATH "$ORIGIN/../lib/")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/rh/gcc-toolset-14/root/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/INIFileEditor")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Applications" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/SwathWizard" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/SwathWizard")
    file(RPATH_CHECK
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/SwathWizard"
         RPATH "$ORIGIN/../lib/")
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "/workspaces/OpenMS/bin/SwathWizard")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/SwathWizard" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/SwathWizard")
    file(RPATH_CHANGE
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/SwathWizard"
         OLD_RPATH "/workspaces/OpenMS/lib:"
         NEW_RPATH "$ORIGIN/../lib/")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/rh/gcc-toolset-14/root/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/SwathWizard")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Applications" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPAS" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPAS")
    file(RPATH_CHECK
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPAS"
         RPATH "$ORIGIN/../lib/")
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "/workspaces/OpenMS/bin/TOPPAS")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPAS" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPAS")
    file(RPATH_CHANGE
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPAS"
         OLD_RPATH "/workspaces/OpenMS/lib:"
         NEW_RPATH "$ORIGIN/../lib/")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/rh/gcc-toolset-14/root/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPAS")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Applications" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPView" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPView")
    file(RPATH_CHECK
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPView"
         RPATH "$ORIGIN/../lib/")
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "/workspaces/OpenMS/bin/TOPPView")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPView" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPView")
    file(RPATH_CHANGE
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPView"
         OLD_RPATH "/workspaces/OpenMS/lib:"
         NEW_RPATH "$ORIGIN/../lib/")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/rh/gcc-toolset-14/root/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/TOPPView")
    endif()
  endif()
endif()

