name: Build pyOpenMS Packages for Testing

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: OpenMS
      
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.x'

    - name: Reduce PATH
      run: echo "DISTUTILS_USE_SDK=1"

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.*'
        host: 'windows'
        target: 'desktop'
        install-deps: 'true'
        archives: 'qtsvg qtbase'
        cache: 'false'

    - name: Install Miniconda
      shell: bash
      run: |
        MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
        curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
        ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S //D=$HOME/miniconda3

    - name: Download contrib build from archive (Windows)
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd OpenMS/contrib
        gh release download -R OpenMS/contrib --pattern 'contrib_build-Windows.tar.gz'
        7z x -so contrib_build-Windows.tar.gz | 7z x -si -ttar
        rm contrib_build-Windows.tar.gz
        ls -la

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Setup conda paths
      shell: bash
      run: |
        echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
        echo "$HOME/miniconda3/Scripts" >> $GITHUB_PATH

    - name: Build pyOpenMS
      shell: bash
      run: |
        PYTHON_VERSIONS=$(cat OpenMS/.github/workflows/python_versions.json)
        CMAKE_PREFIX_PATH="$(echo $Qt6_Dir)/lib/cmake;${Qt6_Dir}"
        export CXXFLAGS="-D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR $CXXFLAGS"
        mkdir pyopenms_whls
        RESET_PATH=$PATH

        for py in $(echo "${PYTHON_VERSIONS}" | jq -r '.[]'); do
          find . -name "_pyopenms*.pyd" -exec rm -rf {} \;
          PATH=$RESET_PATH

          py=$(echo "$py" | tr -d " \r\n")
          pynodot=$(echo "$py" | tr -d ".")
          conda create -n pyoms-bld-"${pynodot}" python="${py}"
          source activate pyoms-bld-"${pynodot}"

          CURRENT_PYTHON_EXECUTABLE=$(which python)
          ${CURRENT_PYTHON_EXECUTABLE} -m pip install --upgrade pip
          ${CURRENT_PYTHON_EXECUTABLE} -m pip install -r $GITHUB_WORKSPACE/OpenMS/src/pyOpenMS/requirements_bld.txt
          
          export Python_ROOT_DIR=$(conda info --json | jq -r '.sys.prefix')
          echo "Python root directory: $Python_ROOT_DIR"

          export BUILD_NAME="pyopenms-wheels-${{ runner.arch }}-class-pyopenms-$py-${{ github.run_number }}"

          ctest --output-on-failure -VV -S $GITHUB_WORKSPACE/OpenMS/tools/ci/cibuild.cmake --config Release

          echo "Current dir is `pwd`"
          echo "wheels are in `find . | grep whl`"
          echo "current ls is `ls -la`"
          cp OpenMS/bld/pyOpenMS/dist/*.whl pyopenms_whls/
        done

      env: 
        SOURCE_DIRECTORY: "${{ github.workspace }}/OpenMS"
        CMAKE_GENERATOR: "Visual Studio 17 2022"
        CMAKE_GENERATOR_PLATFORM: "x64"
        OPENMS_CONTRIB_LIBS: "${{ github.workspace }}/OpenMS/contrib"
        BUILD_TYPE: "Release"
        CI_PROVIDER: "GitHub-Actions"
        CMAKE_CCACHE_EXE: "ccache"
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_DIR: ${{ github.workspace }}/.ccache
        CCACHE_COMPRESS: true
        CCACHE_COMPRESSLEVEL: 12
        CCACHE_MAXSIZE: 400M
        PYOPENMS: "ON"
        PY_NUM_THREADS: ${{ steps.cpu-cores.outputs.count }}
        ENABLE_TUTORIALS: "OFF"
        ENABLE_DOCS: "OFF"
        ENABLE_PIPELINE_TESTING: "OFF"
        ENABLE_STYLE_TESTING: "OFF"
        ENABLE_TOPP_TESTING: "OFF"
        ENABLE_CLASS_TESTING: "OFF"
        USE_STATIC_RUNTIME: "ON"

    - name: Run Unit Tests
      shell: bash
      run: |
        ctest --output-on-failure -V -S $GITHUB_WORKSPACE/OpenMS/tools/ci/citest.cmake -C Release
      env:
        SOURCE_DIRECTORY: "${{ github.workspace }}/OpenMS"
        CI_PROVIDER: "GitHub-Actions"
        BUILD_NAME: "${{ runner.arch }}-class-pyopenms-${{ github.run_number }}"
        BUILD_TYPE: "Release"

    - uses: actions/upload-artifact@v4
      name: Upload pyOpenMS wheels for testing
      with:
        name: pyopenms-wheels-${{ github.run_number }}
        path: pyopenms_whls
        retention-days: 7 