name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          exclude_check: ./src/openms/thirdparty
          inconclusive: disable
          other_options: -i./cmake -i./doc -i./src/tests
                  
      - name: show report    
        run: cat cppcheck_report.txt
