name: cwlcheck
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    name: cwlcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo

      - name: install schema_salad and cwltool
        run: |
          # Requires the most updated version of cwl to work around fields with the name 'id'
          pip install 'cwltool @ git+https://github.com/common-workflow-language/cwltool.git@3.1.20231016170136'

      - name: check cwl files
        run: |
          cd repo/workflow/cwl
          for i in *.cwl; do
            cwltool --validate ${i}
          done
