name: deploy-docker-images
on:
  workflow_dispatch:
  push:
    branches:        
      - nightly
      - 'release/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Define tag name
        shell: bash
        run: |
            BRANCH=${{ steps.extract_branch.outputs.branch }}
            ## use latest to follow docker conventions
            if [[ "$BRANCH" == "develop" ]]
            then 
              BRANCH="latest"
            fi
            if [[ "$BRANCH" == "nightly" ]]
            then 
              BRANCH="latest"
            fi
            ## Remove release/ from release branch name
            echo "##[set-output name=tag;]$(echo ${BRANCH#release/})"
        id: tag_name
      - name: Downcase REPO
        run: echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY,,})"
        id: downcase_repo
      - name: Checkout Dockerfiles
        shell: bash # uses git bash on windows
        run: |
            git clone https://github.com/OpenMS/dockerfiles
            cd dockerfiles
            ## for release, try to checkout the specific release branch in the dockerfiles repo first
            if [[ "${{ steps.extract_branch.outputs.branch }}" == "release/"* ]]
            then
              git checkout ${{ steps.extract_branch.outputs.branch }} || git checkout master
            fi
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: jpfeuffer
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Build and Push Docker Library Image
        uses: docker/build-push-action@v3
        with:
          push: true # Will only build if this is not here
          context: dockerfiles/library
          build-args: |
            OPENMS_TAG=latest
            OPENMS_BRANCH=${{ steps.extract_branch.outputs.branch }}
          tags: |
            ghcr.io/${{ steps.downcase_repo.outputs.repo }}-library:${{ steps.tag_name.outputs.tag }}
      - name: Build and Push Docker Tools Image
        uses: docker/build-push-action@v3
        with:
          push: true # Will only build if this is not here
          context: dockerfiles/executables
          build-args: |
            OPENMS_TAG=latest
            OPENMS_BRANCH=${{ steps.extract_branch.outputs.branch }}
          tags: |
            ghcr.io/${{ steps.downcase_repo.outputs.repo }}-executables:${{ steps.tag_name.outputs.tag }}
