name: FOR_TESTING_build_test_deploy_windows

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v6

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores

    - name: Emulate a Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Install Dependencies
      id: deps
      uses: ./.github/actions/dependencies
      with:
        os: Windows
        compiler: cl.exe
        compiler_ver: 14.51

    - name: Setup ccache cache
      uses: actions/cache@v5
      with:
        path: .ccache
        key: windows-x64-cl.exe-14.51-ccache-test-${{ github.run_number }}
        restore-keys: |
          windows-x64-cl.exe-14.51-ccache-test

    - name: Build
      shell: bash
      run: |
        set +e
        mkdir -p ${{ github.workspace }}/.ccache
        
        echo "::group::ccache statistics before build"
        CCACHE_DIR=${{ github.workspace }}/.ccache ccache -s || true
        echo "::endgroup::"
        
        mkdir bld
        bash tools/ci/capture-env.sh -v $GITHUB_WORKSPACE/bld/CMakeCache.txt
        ctest --output-on-failure -V -S $GITHUB_WORKSPACE/tools/ci/cibuild.cmake
        retVal=$?
        
        echo "::group::ccache statistics after build"
        CCACHE_DIR=${{ github.workspace }}/.ccache ccache -s || true
        echo "::endgroup::"
        
        if [ $retVal -ne 0 ]; then
          echo -e "\033[0;31m Errors in build:"
          find $GITHUB_WORKSPACE/bld/ -name "LastBuild*" -type f -exec cat {} \;
          find $GITHUB_WORKSPACE/bld/ -name "LastBuild*" -type f -exec rm {} \;
        fi
        exit $retVal
      env:
        CMAKE_CXX_COMPILER: cl.exe
        CMAKE_PREFIX_PATH: "${{ steps.deps.outputs.cmake_prefix }}"
        OPENMS_CONTRIB_LIBS: "${{ github.workspace }}/contrib/build"
        CI_PROVIDER: "GitHub-Actions"
        CMAKE_GENERATOR: "Ninja"
        SOURCE_DIRECTORY: "${{ github.workspace }}"
        BUILD_NAME: "windows-test-${{ github.run_number }}"
        ENABLE_STYLE_TESTING: "OFF"
        ENABLE_TOPP_TESTING: "ON"
        ENABLE_CLASS_TESTING: "ON"
        ENABLE_DOCS: "OFF"
        ENABLE_GCC_WERROR: "OFF"
        ENABLE_CWL: "ON"
        SEARCH_ENGINES_DIRECTORY: ${{ github.workspace }}/_thirdparty
        WITH_GUI: "ON"
        SIGNING_IDENTITY: "-"
        ADDRESS_SANITIZER: "Off"
        BUILD_TYPE: "Release"
        MT_ENABLE_OPENMP: "ON"
        BOOST_USE_STATIC: "ON"
        BUILD_FLAGS: "-j${{ steps.cpu-cores.outputs.count }}"
        CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
        CMAKE_C_COMPILER_LAUNCHER: "ccache"
        CCACHE_BASEDIR: ${{ github.workspace }}
        CCACHE_DIR: ${{ github.workspace }}/.ccache
        CCACHE_COMPRESS: true
        CCACHE_COMPRESSLEVEL: 6
        CCACHE_MAXSIZE: 1G
        CCACHE_SLOPPINESS: time_macros,include_file_ctime,include_file_mtime
        CCACHE_COMPILERCHECK: content
        WITH_THERMORAWFILEPARSER_TEST: "OFF"
        USE_EXTERNAL_JSON: "OFF"

    - name: Test
      shell: bash
      run: |
        ctest --output-on-failure -V -S $GITHUB_WORKSPACE/tools/ci/citest.cmake
      env:
        SOURCE_DIRECTORY: "${{ github.workspace }}"
        CI_PROVIDER: "GitHub-Actions"
        BUILD_NAME: "windows-test-${{ github.run_number }}"

    - name: Package
      shell: bash
      run: |
        set +e
        ctest --output-on-failure -VV -S $GITHUB_WORKSPACE/tools/ci/cipackage.cmake
        retVal=$?
        if [ $retVal -ne 0 ]; then
          echo -e "\033[0;31m Errors in packaging:"
          find $GITHUB_WORKSPACE/bld/ -name "LastBuild*" -type f -exec cat {} \;
          find $GITHUB_WORKSPACE/bld/ -name "LastBuild*" -type f -exec rm {} \;
          cat bld/_CPack_Packages/win64/NSIS/NSISOutput.log || true
        fi
        exit $retVal
      env:
        SOURCE_DIRECTORY: "${{ github.workspace }}"
        PACKAGE_TYPE: "nsis"
        SEARCH_ENGINES_DIRECTORY: "${{ github.workspace }}/_thirdparty"
        CI_PROVIDER: "GitHub-Actions"
        BUILD_NAME: "windows-test-${{ github.run_number }}"
        SIGNING_IDENTITY: "-"
        USE_EXTERNAL_JSON: "OFF"

    - name: Upload installer as artifact
      uses: actions/upload-artifact@v7
      with:
        name: installer-Windows
        path: |
          ${{ github.workspace }}/bld/*.exe
