name: test_python_versions
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-win:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: OpenMS

      - name: Build
        shell: bash
        run: |
          ls
          ls .github
          ls .github/workflows
          PYTHON_VERSIONS=$(cat .github/workflows/python_versions.json)
          
          echo $PYTHON_VERSIONS