# This builds python wheels on manylinux, macOS and Windows and uploads them
# to public pypi for release and for nightlies also to pypi.cs.uni-tuebingen.de

name: pyopenms-wheels-and-packages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      upload-to-pypi:
        type: boolean
        description: actually upload the release package to pypi.org
        default: false
  push:
    tags:
      - 'Release*'
    branches: [ nightly, py_nightly_test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            # cl.exe is currently the only supported. Needs a VS shell to be set up (especially if used without VS CMake Generator)
            # clang.exe is also installed but untested (might crash with our VS specific compiler definitions)
            # clang-cl.exe might be used instead.
            compiler: cl.exe
            compiler_ver: default

          - os: macos-13
            # Since the appleclang version is dependent on the XCode versions that are installed
            #  on the GH runners, use this as the choice for a specific version
            # TODO currently unused but XCode/appleclang is the default
            compiler: xcode
            # TODO implement support for other versions
            compiler_ver: 14.2

          - os: macos-latest
            # Since the appleclang version is dependent on the XCode versions that are installed
            #  on the GH runners, use this as the choice for a specific version
            # TODO currently unused but XCode/appleclang is the default
            compiler: xcode
            # TODO implement support for other versions
            compiler_ver: 15.0.1

          # Make sure the compilers are available in that version on the GH runners
          # We are not installing anything.
          - os: ubuntu-latest
            compiler: g++
            container: ghcr.io/openms/contrib_manylinux_2_34:latest

    runs-on: ${{ matrix.os }}
    container: 
      image: ${{ matrix.container || '' }} 
    steps:
    - uses: actions/checkout@v4
      with:
        path: OpenMS
      
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.x'

    - name: Reduce PATH # This fixes a bug described in https://github.com/facebook/watchman/commit/59bcfbf91d2a24ab580b8a78e384f133cc202383
      if: startsWith(matrix.os, 'windows')
      run: echo "DISTUTILS_USE_SDK=1"

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores

    - name: Install Qt for Windows
      if: startsWith(matrix.os, 'windows')
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.*'
        host: 'windows' # default: win64_msvc2017_64
        target: 'desktop'
        install-deps: 'true'
        archives: 'qtsvg qtbase'
        cache: 'false'

    - name: Install Miniconda
      shell: bash
      run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" == "macOS" && "${{ runner.arch }}" == "X64" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-MacOSX-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" == "macOS" && "${{ runner.arch }}" == "ARM64"  ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-MacOSX-arm64.sh
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S
          fi

 
    - name: Download contrib build from archive (Windows)
      if: startsWith(matrix.os, 'windows')
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          cd OpenMS/contrib
          # Download the file using the URL fetched from GitHub
          gh release download -R OpenMS/contrib --pattern 'contrib_build-Windows.tar.gz'
          # Extract the archive
          7z x -so contrib_build-Windows.tar.gz | 7z x -si -ttar
          rm contrib_build-Windows.tar.gz
          ls -la

    - name: Install contrib packages from brew
      if: startsWith(matrix.os, 'macos')
      run: |
          ## Needed for Qt. Install before to overwrite the default softlinks on the GH runners
          brew install ccache autoconf automake libtool ninja && brew link --overwrite ccache
          brew install libsvm xerces-c boost eigen sqlite coinutils cbc cgl clp qt@6 libomp

    - name: Install jq and ninja-build from yum
      if: startsWith(matrix.os, 'ubuntu')
      run: |
          yum install -y jq
          yum install -y ninja-build # Install Ninja for build files
          yum install -y ccache
    
    # https://github.com/marketplace/actions/visual-studio-shell
    - name: Set up Visual Studio shell
      if: startsWith(matrix.os, 'windows')
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Setup conda paths
      shell: bash
      run: |
        echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
        echo "$HOME/miniconda3/Scripts" >> $GITHUB_PATH
    
    - id: set-vars
      name: Set extra variables
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == ubuntu-* ]]; then
          echo "openms_contrib_libs=/contrib-build/" >> $GITHUB_OUTPUT
          echo "no_dependencies=ON" >> $GITHUB_OUTPUT
        else
          echo "openms_contrib_libs=${{ github.workspace }}/OpenMS/contrib" >> $GITHUB_OUTPUT
          echo "no_dependencies=OFF" >> $GITHUB_OUTPUT
        fi

        if [[ "${{ matrix.os }}" == windows-* ]]; then
          echo "build_flags=" >> $GITHUB_OUTPUT
          echo "cmake_generator=Visual Studio 17 2022" >> $GITHUB_OUTPUT
          echo "cmake_generator_platform=x64" >> $GITHUB_OUTPUT
        else
          echo "build_flags=-j${{ steps.cpu-cores.outputs.count }}" >> $GITHUB_OUTPUT
          echo "cmake_generator=Ninja" >> $GITHUB_OUTPUT
          echo "cmake_generator_platform=" >> $GITHUB_OUTPUT
        fi

        if [[ "${{ matrix.os }}" == macos-* ]]; then
          echo "boost_use_static=OFF" >> $GITHUB_OUTPUT
          echo "macosx_deployment_target=12" >> $GITHUB_OUTPUT
        else
          echo "boost_use_static=ON" >> $GITHUB_OUTPUT
          echo "macosx_deployment_target=" >> $GITHUB_OUTPUT
        fi

    - name: Build
      shell: bash
      run: |
        PYTHON_VERSIONS=$(cat OpenMS/.github/workflows/python_versions.json)

        export CMAKE_PREFIX_PATH="$(echo $Qt6_Dir)/lib/cmake;${Qt6_Dir}"
      
        mkdir pyopenms_whls

        # Set OpenMP_ROOT for macOS
        if [[ "${{ matrix.os }}" == macos-* ]]; then
          export OpenMP_ROOT=$(brew --prefix libomp)
        fi

        # The growing PATH leads to a failure in the last iteration of the pyopenms build process.
        # We will store the PATH variable in the beginning and reset it with every iteration.
        RESET_PATH=$PATH
        # TODO this is only used on linux, figure out cleaner way to do this
        LD_OLD_LIBRARY_PATH=$LD_LIBRARY_PATH

        for py in $(echo "${PYTHON_VERSIONS}" | jq -r '.[]'); do

          # reset the path
          PATH=$RESET_PATH

          # create and activate conda environment
          py=$(echo "$py" | tr -d " \r\n")
          pynodot=$(echo "$py" | tr -d ".")
          conda create -n pyoms-bld-"${pynodot}" python="${py}"
          source activate pyoms-bld-"${pynodot}"

          # set current python executable
          CURRENT_PYTHON_EXECUTABLE=$(which python)

          ${CURRENT_PYTHON_EXECUTABLE} -m pip install --upgrade pip
          # pip install all the stuff
          ${CURRENT_PYTHON_EXECUTABLE} -m pip install -r $GITHUB_WORKSPACE/OpenMS/src/pyOpenMS/requirements_bld.txt
          
          # Get the Python root directory
          export Python_ROOT_DIR=$(conda info --json | jq -r '.sys.prefix')
          echo "Python root directory: $Python_ROOT_DIR"

          export BUILD_NAME="pyopenms-wheels-${{ runner.arch }}-class-pyopenms-$py-${{ github.run_number }}" #TODO make this more expressive

          # build pyopenms distribution
          ctest --output-on-failure -VV -S $GITHUB_WORKSPACE/OpenMS/tools/ci/cibuild.cmake --config Release

          # On Linux we also need to strip the libraries and repair the wheels

          if [[ "${{ matrix.os }}" == ubuntu-* ]]; then
            # ensure auditwheel can find the libraries
            export LD_LIBRARY_PATH=$LD_OLD_LIBRARY_PATH:`pwd`/OpenMS/bld/lib

            # strip the libraries before repairing
            strip --strip-all OpenMS/bld/lib/libOpenMS.so
            strip --strip-all OpenMS/bld/lib/libOpenSwathAlgo.so

            pushd OpenMS/bld/pyOpenMS
              # Bundle stripped plus external shared libraries into the wheels
              for whl in dist/pyopenms*.whl; do
                auditwheel repair "$whl" -w wheelhouse/
              done

              mv wheelhouse/* OpenMS/bld/pyOpenMS/dist/
            popd
            export LD_LIBRARY_PATH=$LD_OLD_LIBRARY_PATH
          fi

          # copy to directory
          cp OpenMS/bld/pyOpenMS/dist/*.whl pyopenms_whls/

          # clean up
          conda deactivate
          conda remove --name "pyoms-bld-${pynodot}" --all
          
          # clean previous pyopenms libs
          find . -name "_pyopenms*.pyd" -exec rm -rf {} \;
          find . -name "_pyopenms*.so" -exec rm -rf {} \;

        done

      env: 
          SOURCE_DIRECTORY: "${{ github.workspace }}/OpenMS"
          CMAKE_GENERATOR: ${{ steps.set-vars.outputs.cmake_generator }}
          CMAKE_GENERATOR_PLATFORM: ${{ steps.set-vars.outputs.cmake_generator_platform }}
          OPENMS_CONTRIB_LIBS: ${{ steps.set-vars.outputs.openms_contrib_libs }}
          BUILD_FLAGS: ${{ steps.set-vars.outputs.build_flags }}
          BUILD_TYPE: "Release"
          NO_DEPENDENCIES: ${{ steps.set-vars.outputs.no_dependencies }}
          BOOST_USE_STATIC: ${{ steps.set-vars.outputs.boost_use_static }}
          MACOSX_DEPLOYMENT_TARGET: ${{ steps.set-vars.outputs.macosx_deployment_target }}
          CI_PROVIDER: "GitHub-Actions"
          CMAKE_CCACHE_EXE: "ccache"
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 400M
          PYOPENMS: "ON"
          PY_NUM_THREADS: ${{ steps.cpu-cores.outputs.count }}
          ENABLE_TUTORIALS: "OFF"
          ENABLE_DOCS: "OFF"
          ENABLE_PIPELINE_TESTING: "OFF"
          ENABLE_STYLE_TESTING: "OFF"
          ENABLE_TOPP_TESTING: "OFF"
          ENABLE_CLASS_TESTING: "OFF"

    - name: Run Unit Tests
      shell: bash
      run: |
           ctest --output-on-failure -V -S $GITHUB_WORKSPACE/OpenMS/tools/ci/citest.cmake -C Release
      env:
          SOURCE_DIRECTORY: "${{ github.workspace }}/OpenMS"
          CI_PROVIDER: "GitHub-Actions"
          BUILD_NAME: "${{ runner.arch }}-class-pyopenms-${{ github.run_number }}"
          BUILD_TYPE: "Release"
          # The rest of the vars should be saved in the CMakeCache

    - uses: actions/upload-artifact@v4
      name: Upload buildfiles
      if: always()
      with:
        name: ${{ runner.os }}-${{runner.arch }}-buildfiles
        path: |
              CMakeCache.txt
              pyOpenMS/env.py
          
    - uses: actions/upload-artifact@v4
      name: Upload wheels
      if: always()
      with:
        name: ${{ runner.os }}-${{ runner.arch }}-wheels
        path: pyopenms_whls


# Tests the build workflows
  test:
    needs: [build-matrix]
    runs-on: ${{ matrix.os }}
    env:
      SYSTEM_VERSION_COMPAT: 0 #courtesy of https://github.com/actions/setup-python/issues/469 in lieu of an actual solution.
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
      name: Checkout sources
      with:
        path: OpenMS

    - name: Install Miniconda
      shell: bash
      run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" == "macOS*" && "${{ runner.arch }}" == "X64" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-MacOSX-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" == "macOS" && "${{ runner.arch }}" == "ARM64"  ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-MacOSX-arm64.sh
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
            curl -o $MINICONDA_FILENAME "https://repo.anaconda.com/miniconda/$MINICONDA_FILENAME"
            ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S
          fi

    - name: Setup conda paths
      shell: bash
      run: |
        echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
        echo "$HOME/miniconda3/Scripts" >> $GITHUB_PATH

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
          name: ${{ runner.os }}-${{ runner.arch }}-wheels

    - name: Test
      shell: bash 
      run: |
        PYTHON_VERSIONS=$(cat OpenMS/.github/workflows/python_versions.json)
        echo $PYTHON_VERSIONS

        for py in $(echo "${PYTHON_VERSIONS}" | jq -r '.[]'); do
          py=$(echo "$py" | tr -d " \r\n")
          pynodot=$(echo "$py" | tr -d ".")
          conda create -n pyoms-bld-$pynodot python=$py
          source activate pyoms-bld-$pynodot

          # Find .whl for current python version
          CURRENT_VERSION=$(echo $py | sed "s/\.//g") # remove "." for find
          echo "Testing python version $CURRENT_VERSION"
          CURRENT_WHL=$(find $GITHUB_WORKSPACE -name "*cp$CURRENT_VERSION*.whl") # Probably $GITHUB_WORKSPACE
          if [[ "$CURRENT_WHL" == '' ]]; then

            continue

          fi
          echo "Found wheel $CURRENT_WHL : Testing.."

          # pip install all the stuff
          python -m pip install --upgrade pip
          python -m pip install $CURRENT_WHL

          # check if package was installed
          python -c "import importlib.util; p_name = 'pyopenms'; package = importlib.util.find_spec(p_name); print(p_name + ' was sucessfully installed! Nice one!') if package is not None else print('Something seems to be wrong!')"
          # run test
          python -c "exec(\"import pyopenms\nprint(pyopenms.EmpiricalFormula(\'C6H12O6\').getMonoWeight())\")"

          conda deactivate

          # clean up
          conda remove --name pyoms-bld-$pynodot --all

        done

  # Upload the wheels (the action only runs on ubuntu slaves)
  publish:
    needs: [test] # doesn't really NEED it but we want the tests to pass first
    runs-on: ubuntu-latest
    steps:
    # haha github is just ridiculous.. not getting their actions to do basic stuff for years
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
          name: Linux-X64-wheels
          path: /home/runner/work/OpenMS/OpenMS/Linux-X64-wheels
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
          name: Windows-X64-wheels
          path: /home/runner/work/OpenMS/OpenMS/Windows-X64-wheels
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
          name: macOS-X64-wheels
          path: /home/runner/work/OpenMS/OpenMS/macOS-X64-wheels
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
          name: macOS-ARM64-wheels
          path: /home/runner/work/OpenMS/OpenMS/macOS-ARM64-wheels

    - name: Merge all artifacts
      run: |
            mkdir wheels
            cp -lr *-wheels/* wheels/
            pwd
            ls -la wheels/

    - name: Publish package to nightly PyPI
        # Upload the wheels to our pypi server for develop, nightly and release branches (unless it's explictly stated to upload it to pypi.org)
      if: contains(github.ref, 'develop') || contains(github.ref, 'nightly') || (contains(github.ref, 'Release') && inputs.upload-to-pypi == 'false')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://pypi.cs.uni-tuebingen.de/
        user: openms
        password: ${{ secrets.abiservices_pypi_pw }}
        packages-dir: ${{ github.workspace }}/wheels

    - name: Publish package to PyPI
      if: contains(github.ref, 'Release') && inputs.upload-to-pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        repository-url: https://pypi.org/
        password: ${{ secrets.pypi_api_token_release }}
        packages-dir: ${{ github.workspace }}/wheels
