name: Spellcheck Issue-Process
on:
  issue_comment:
    types: [edited]
jobs:
  process-unknown-words:
    if: startsWith(github.event.issue.title, format('Spell-Check Results - {0}', github.actor))
    env:
      working_directory: 'tools/spellcheck/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install progress
      - name: Process issue
        run: python ${{ format('{0}github_issue_process.py', env.working_directory) }} -to ${{ secrets.GITHUB_TOKEN }} -repo $GITHUB_REPOSITORY -ti '${{ github.event.issue.title }}' -in ${{ github.event.issue.number }}