name: spellcheck - process unknown words
on:
  issues:
    types: [edited]
jobs:
  process-unknown-words:
    if: startsWith(github.event.issue.title, format('Spell-Check Results - {0}', github.actor))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: Process unknown words
        run: python ./tools/spellcheck/github_process_unknown.py -to ${{ secrets.GITHUB_TOKEN }} -repo $GITHUB_REPOSITORY -ti '${{ github.event.issue.title }}' -in ${{ github.event.issue.number }}