name: "Vcpkg integration"

on:
    push:
        branches:
            - vcpkg_linux_integration

jobs:
    configure:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v6
              with:
                submodules: recursive
                fetch-depth: 0

            - uses: lukka/get-cmake@latest

            - name: Install build dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                  ninja-build \
                  autoconf \
                  autoconf-archive \
                  automake \
                  libtool

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              id: runvcpkg

            - name: Print vcpkg info
              run: |
                echo "VCPKG_ROOT=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}"
                echo "TRIPLET=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}"
            
            - name: Configure OpenMS
              run: |
                cmake --preset linux  \
                  -DWITH_THERMO_RAW=OFF  \
                  -DWITH_GUI=OFF

            - name: Build OpenMS
              run: |
                cmake --build --preset linux-release --parallel 2

            - name: Inspect vcpkg cache archives
              if: always()
              run: |
                echo "Total files: "
                find ~/.cache/vcpkg/archives -name "*.zip" | wc -l || true

                echo "Total size: "
                du -sh ~/.cache/vcpkg/archives || true

            - name: Upload cache artifacts
              if: always()
              uses: actions/upload-artifact@v7
              with:
                name: vcpkg-cache
                path: ~/.cache/vcpkg/archives
