name: "Vcpkg integration"

on:
    push:
        branches:
            - vcpkg_linux_integration
    workflow_dispatch:

jobs:
    configure:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v6
              with:
                submodules: recursive
                fetch-depth: 0

            - uses: lukka/get-cmake@latest

            - name: Install build dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                  ninja-build \
                  autoconf \
                  autoconf-archive \
                  automake \
                  libtool

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              id: runvcpkg

            - name: Override binary cache backedn
              run: |
                mkdir -p  "$HOME/.cache/vcpkg/archives"
                echo "VCPKG_BINARY_SOURCES=clear;files,$HOME/.cache/vcpkg/archives,readwrite" >> $GITHUB_ENV
            - name: Print vcpkg info
              run: |
                echo "VCPKG_ROOT=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}"
                echo "TRIPLET=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}"
                echo "HOME=$HOME"
                echo "VCPKG_BINARY_SOURCES=$VCPKG_BINARY_SOURCES"

            - name: Runner info
              run: |
                echo "CPU: $(nproc)"
                free -h
            
            - name: Configure OpenMS
              run: |
                cmake --preset linux  \
                  -DWITH_THERMO_RAW=OFF  \
                  -DWITH_GUI=OFF

            - name: Build OpenMS
              run: |
                cmake --build --preset linux-release

            - name: Inspect vcpkg cache archives
              if: always()
              run: |
                echo "VCPKG_BINARY_SOURCES=$VCPKG_BINARY_SOURCES"

                echo
                echo "Total files: "
                find "$HOME/.cache/vcpkg/archives" -name "*.zip" | wc -l || true

                echo
                echo "Total size: "
                du -sh "$HOME/.cache/vcpkg/archives" || true

                echo
                echo "Some files"
                find "$HOME/.cache/vcpkg/archives" -name "*.zip" | head -20 || true

            # - name: Upload cache artifacts
            #   if: always()
            #   uses: actions/upload-artifact@v7
            #   with:
            #     name: vcpkg-cache
            #     path: ~/.cache/vcpkg/archives
            
            - name: Test
              shell: bash
              run: |
                cd build/linux && ninja test
